### ISSUE TITLE
File that I am having issues with - For Todd

### ISSUE THREAD

**Issue by funinthefalls** [LaserWeb/LaserWeb4#102]
[LargeGlassBox.zip](https://github.com/LaserWeb/LaserWeb4/files/671646/LargeGlassBox.zip)

**Comment by tbfleming** [comment]
Here's how it behaves on 2 of my machines. Windows 10, Chrome 55.0.2883.87 m (64-bit):

![large glass box](https://cloud.githubusercontent.com/assets/418464/21467833/dbd0e20a-c9c8-11e6-91e1-4bc68b791769.gif)

**Comment by funinthefalls** [comment]
Fixed,
