### ISSUE TITLE
Cannot select inner shape.

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#108]
Cannot pick inner shape. I suppose collision detection is taking hollow shapes as filled ones. A workaround could be working with filled shapes to reorder shape front-back, but will be very annoying working with (visualization
![pick_order](https://cloud.githubusercontent.com/assets/1706080/21530729/1749c806-cd43-11e6-9011-216f8dc9f452.gif)
)

[escaleras_a4_300.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/676185/escaleras_a4_300.svg.zip)

@tbfleming I've been experiencing performance issues again (reopened #101)

**Comment by tbfleming** [comment]
I switched it to only hit test on path outlines when paths aren't filled.

**Comment by jorgerobles** [comment]
Tested And Perfect, thank you!
