### ISSUE TITLE
Pocket operation not working 

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#115]
Attached gcode for a pocket operation; it goes into initial position , plunges but then it seems not to move. I can hear some noise coming from the steppers as its trying to move but feels more like a shake
[gcode (37) copy.gcode.txt](https://github.com/LaserWeb/LaserWeb4/files/683706/gcode.37.copy.gcode.txt)

**Comment by tbfleming** [comment]
Can you attach the workspace file?

**Comment by cojarbi** [comment]
Here you go. Mind that the above gcode is only the mill pocket operation on the attached workspace
[iTopie Final (4) copy.json.txt](https://github.com/LaserWeb/LaserWeb4/files/683801/iTopie.Final.4.copy.json.txt)

**Comment by tbfleming** [comment]
The firmware was probably choking on the tiny moves. I reduced the resolution for milling to .001 mm.

See what happens now. What firmware are you using?

**Comment by cojarbi** [comment]
This is with grbl 1.1e

**Comment by cojarbi** [comment]
Did a clear cache, reloaded the workspace, generated code only for the pocket and the result is the same. 
It moves on the decimals of only one coordinate. I can see the gcode has bein reduced to 3 decimal places
[gcode (23) copy.gcode.txt](https://github.com/LaserWeb/LaserWeb4/files/684630/gcode.23.copy.gcode.txt)

**Comment by tbfleming** [comment]
Mill operations now have a ```segment``` option (mm). The CAM trims moves less than this length. You'll have to play with this value to get a good tradeoff between accuracy and speed.

**Comment by cojarbi** [comment]
Ok thanks  will test later as I don't need super accuracy here at the moment

**Comment by cojarbi** [comment]
Used a segment of 0.5 and its seems to be working fine for this project.

**Comment by cojarbi** [comment]
I can say this is solved, thanks
