### ISSUE TITLE
Curve within curve exclusion

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#116]
Is there a current or planned method to exclude the region of a curve within another curve in fill operations?

For instance, the inside two curves in the letter 'B'.

**Comment by DarklyLabs** [comment]
I cannot see this option in the 'Laser Fill Path' settings.

**Comment by tbfleming** [comment]
Most operations need a clear definition of what's inside and what's outside; combining paths gives them that definition. "Laser Cut" doesn't need a clear definition, so it's optional.

**Comment by DarklyLabs** [comment]
@tbfleming How would we define the inner and outer curves in the letter 'B' for instance?

Other software we have worked with made an assumption that inner curves would be subtracted from the fill operation. This assumption is generally what most users would want to do and makes it very straight forward to use. If they didn't want this, then they would not include inner curves into their fill operation.

**Comment by tbfleming** [comment]
A single path object (e.g. a B) may have holes and disconnected regions. 'combine paths' does a union operation between multiple path objects.

jscut has a dropdown to select between union, difference, intersection, and xor. I didn't include it because it seemed to cause confusion. Instead I encourage people to create proper path objects using other tools.

**Comment by tbfleming** [comment]
I could switch it from union to xor. That will cover both the disconnected and the hole cases well. It may cause confusion where there's partial overlap, which is why I went with union.

**Comment by DarklyLabs** [comment]
Based on what most of our users would be doing would be handled by xor (if that means excluding the inner curve region).
If there is overlap between curves then that usually means users have to fix this problem in their designs as a 'fill' operation would not be able to be defined correctly.

**Comment by tbfleming** [comment]
This change is now live.

**Comment by DarklyLabs** [comment]
@tbfleming Just checked it. Works beautifully. Thank you.
