### ISSUE TITLE
Add CAM items scroll bar

### ISSUE THREAD

**Issue by iceblu3710** [LaserWeb/LaserWeb4#120]
As you can see below when you add a lot of items to a cam option the cam settings can be buried way down. There is a scroll bar but I think it would be beneficial to sprout a scroll bar on the "add to existing operation" area so the cam options panel doesn't sink below the screen.

![cam_scrolling](https://cloud.githubusercontent.com/assets/187394/21873956/9799f568-d837-11e6-9a84-460e36de7272.png)

**Comment by tbfleming** [comment]
I'm uneasy with scroll within a scroll. Maybe make that part collapsible instead?

**Comment by jorgerobles** [comment]
Added "Hide/Show docs" toggle below docs

**Comment by iceblu3710** [comment]
Random feature update. Thanks!
