### ISSUE TITLE
DXF not loading: filetype issue

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#121]
I heavily depend on the guitarlist sketchup dxf export in my workflow https://github.com/LaserWeb/LaserWeb3/wiki/Workflow:-Sketchup-2D

In LW3 we just look at file extension, there these work. 
In LW4 this doesnt: (note the console.log should print file.type, and its absense makes me think we arent identifying it as dxf?)
![no filetype](https://cloud.githubusercontent.com/assets/7695323/21900666/58cd5750-d8fd-11e6-8290-5edfac265ab1.PNG)

Test file:

[end-caps.dxf.txt](https://github.com/LaserWeb/LaserWeb4/files/702422/end-caps.dxf.txt)

**Comment by openhardwarecoza** [comment]
Logged the action.payload

![object](https://cloud.githubusercontent.com/assets/7695323/21900810/e5956128-d8fd-11e6-8106-d77fd9c8b4cb.PNG)

**Comment by iceblu3710** [comment]
dxf-parser outputs the dxfTree with 10 entities. They are `color: 16777215` which is white.

![end-caps](https://cloud.githubusercontent.com/assets/187394/21917441/6650778a-d90d-11e6-86ed-85e80a240c62.png)

![end-caps-console](https://cloud.githubusercontent.com/assets/187394/21917480/a2ec7784-d90d-11e6-854c-ce5b79438122.png)

**Comment by iceblu3710** [comment]
Oh, might be a problem I had after installing DraftSight. If you check the mime type of the dxf it should be `image/vnd.dxf` as the document load process checks the file extension in cam.js to choose a parser then off to the document reducer which reads the mime-type.

After install DraftSight my dxf's where `application/vnd.VAR_VENDOR_NAME.VAR_PRODUCT_NAME-dxf type (application/vnd.VAR_VENDOR_NAME.VAR_PRODUCT_NAME-dxf)` and I had to rebuild my mime types (I'm on Ubuntu)

**Comment by openhardwarecoza** [comment]
Yes,  but we cant force users to fix files via Draftsight first.  Please
install LaserWeb3,  and play with it a little (: -  dxfs of all kinds
worked really well there.  All that didn't work was splines.

**Comment by iceblu3710** [comment]
@openhardwarecoza My suggestions were to figure out if the dxf was not loading for you because of a mime type mismatch on your system. The file loads fine for me with a new git checkout so I can not reproduce the error.

**Comment by tbfleming** [comment]
The mime type comes up empty on my machine also.

**Comment by iceblu3710** [comment]
@tbfleming My screen cap is right from the `document/cam.js` at the dispatch call `dispatch(loadDocument(file, dxfTree));`

As a whole, Why do we check the extension in the documents and then the type in the reducer? It would be a lot easier to just use extensions. Mime types are pretty unreliable, DraftSight messed mine up but its not like the file actually changed or anything.

**Comment by openhardwarecoza** [comment]
"Often, the MIME type sent by the browser will be the one reported by the
OS. And this is exactly why, as stated in the question, the MIME type
reported by the browser is unreliable."
So because you have Draftsight installed,  your OS reports it.  I have QCad
and sketchup (all i will ever use) which clearly then doesnt.  When it
comes to users...  We have to handle that unpredictability.

My suggestion:

if payload.file.type == dxf || file.name == *.dxf {} (simplified of course)

On Jan 13, 2017 6:28 AM, "Todd Fleming" <notifications@github.com> wrote:

The mime type comes up empty on my machine also.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/121#issuecomment-272358442>,
or mute the thread

**Comment by openhardwarecoza** [comment]
`It would be a lot easier to just use extensions` -  amen (:

On Jan 13, 2017 6:36 AM, "iceblu3710" <notifications@github.com> wrote:

@tbfleming <https://github.com/tbfleming> My screen cap is right from the
document/cam.js at the dispatch call dispatch(loadDocument(file, dxfTree));

As a whole, Why do we check the extension in the documents and then the
type in the reducer? It would be a lot easier to just use extensions. Mime
types are pretty unreliable, DraftSight messed mine up but its not like the
file actually changed or anything.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/121#issuecomment-272359186>,
or mute the thread

**Comment by tbfleming** [comment]
The mime types for images and svg files are reliable. Only switch DXF loading to check for extensions.

**Comment by openhardwarecoza** [comment]
Thanks!
