### ISSUE TITLE
DXF: Elegantly fail for White / No stroke colors

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#124]
In LW3: we did https://github.com/LaserWeb/LaserWeb3/blob/master/public/lib/dxf/three-dxf.js#L275-L280

``` 
if (color === 0xffffff) {
        color = 0x000000;
}

if (!color) {
        color = 0x000000;
}
```

Would be wise to bring that across too.  When someone works in white, you can bet they most likely have a black BG, so failing to black is 99.99% safe. Way better than keeping white
We also have that if !color, so I recall we had a couple test dxfs in the early days where there was no color defined. Added that to fail elegantly for that exception too

**Comment by iceblu3710** [comment]
I default to black but did not think of white. I will add that in when I get home.
