### ISSUE TITLE
Need bullseye feature

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#127]
I am integrating comms module into LW4 and need the bullseye feature we had in LW3 to show the actual position. Is this feature allready in or can somebody make it available please?

**Comment by jorgerobles** [comment]
Bullseye? do you mean the Jogs G92 button?

**Comment by openhardwarecoza** [comment]
@jorgerobles: its a object in the 3D viewer that shows on the grid,  where
the DRO pos is:

Updated on every DRO change:
https://github.com/LaserWeb/LaserWeb3/blob/master/public/js/viewer.js#L27-L38

And initially drawn here
https://github.com/LaserWeb/LaserWeb3/blob/master/public/js/viewer.js#L251-L281

Used to be a 'bullseye'  in later versions we made it a cone (but the name
stuck)

**Comment by jorgerobles** [comment]
Oook, sorry, name was a bit confusing.

2017-01-15 17:25 GMT+01:00 Peter van der Walt <notifications@github.com>:

> @jorgerobles: its a object in the 3D viewer that shows on the grid, where
> the DRO pos is:
>
> Updated on every DRO change:
> https://github.com/LaserWeb/LaserWeb3/blob/master/public/
> js/viewer.js#L27-L38
>
> And initially drawn here
> https://github.com/LaserWeb/LaserWeb3/blob/master/public/
> js/viewer.js#L251-L281
>
> Used to be a 'bullseye' in later versions we made it a cone (but the name
> stuck)
>

**Comment by openhardwarecoza** [comment]
(: yip sorry.  Thats why i explained the history too. Hehe.  Feel free to
rename

**Comment by tbfleming** [comment]
Added. I put an example in com.js showing how to set it.

**Comment by cprezzi** [comment]
Perfect thanks!
