### ISSUE TITLE
Gcode Preview

### ISSUE THREAD

**Issue by iceblu3710** [LaserWeb/LaserWeb4#128]
I think G0 and G1 should be previewed on screen in different colors, say red for G1 and green for G0?

**Comment by tbfleming** [comment]
They are.

**Comment by iceblu3710** [comment]
Not for me. just did a pull and both are just green.

![untitled](https://cloud.githubusercontent.com/assets/187394/21965252/c0a4c5e0-db21-11e6-850e-a687dc2276b6.png)

**Comment by tbfleming** [comment]
Can you attach your gcode file?

![image](https://cloud.githubusercontent.com/assets/418464/21965297/33320f10-db2b-11e6-947f-3d22833991d5.png)

**Comment by iceblu3710** [comment]
[gcode.gcode.txt](https://github.com/LaserWeb/LaserWeb4/files/706815/gcode.gcode.txt)

**Comment by tbfleming** [comment]
Very odd. This is with your settings file:

![image](https://cloud.githubusercontent.com/assets/418464/21965410/5dd51c24-db2d-11e6-92d8-fbfdca4b734c.png)

**Comment by iceblu3710** [comment]
What's the last commit on your working version? 
`048bd1f 2017-01-15 | #127: add work pos marker (HEAD -> dev-es6, origin/dev-es6, origin/HEAD) [Todd Fleming]`

I don't get different colors with any file type or importing settings.

**Comment by iceblu3710** [comment]
Just tried to reset my settings to the GRBL default and then the initial G0 move did not show up at all and everything was still red.

[gcode (1).gcode.txt](https://github.com/LaserWeb/LaserWeb4/files/706846/gcode.1.gcode.txt)
[laserweb-snapshot (1).json.txt](https://github.com/LaserWeb/LaserWeb4/files/706847/laserweb-snapshot.1.json.txt)
[laserweb-settings (1).json.txt](https://github.com/LaserWeb/LaserWeb4/files/706848/laserweb-settings.1.json.txt)

**Comment by tbfleming** [comment]
I'm also on 048bd1f.

The (1) files also work on my machine. Which OS and Chrome version are you on?

I'm on Windows 10 with Chrome 55.0.2883.87 m (64-bit).

**Comment by iceblu3710** [comment]
Not working on:
Ubuntu Linux 4.4.0-57-generic Chrome Version 55.0.2883.87 (64-bit)

Just tested on my HTPC and its working:
Windows 10 with Chrome Version 55.0.2883.87 m (64-bit)

**Comment by iceblu3710** [comment]
There are reports of the `m` sub version causing things to act differently. Searching github issues for the `m` version shows 661 open issues.

Maybe it's in the browsers canvas rending or something?

**Comment by iceblu3710** [comment]
Will wait for a Linux Chrome update. Closed for now.
