### ISSUE TITLE
Laser preview not rendering

### ISSUE THREAD

**Issue by iceblu3710** [LaserWeb/LaserWeb4#129]
Laser preview does not render on any cam functions.

**Comment by tbfleming** [comment]
It should. Please save your workspace and your settings (2 different files) and attach them.

**Comment by iceblu3710** [comment]
[laserweb-settings.json.txt](https://github.com/LaserWeb/LaserWeb4/files/706809/laserweb-settings.json.txt)
[laserweb-snapshot.json.txt](https://github.com/LaserWeb/LaserWeb4/files/706810/laserweb-snapshot.json.txt)

**Comment by tbfleming** [comment]
This is with your settings and snapshot:

![image](https://cloud.githubusercontent.com/assets/418464/21965437/b9367770-db2d-11e6-8bd8-0609368626ce.png)

It draws the laser at the width in the settings, which is thinner than the gcode preview. For it to show up you need to turn off both Show Gcode and Show Documents.

**Comment by iceblu3710** [comment]
I don't get any laser preview.

In the workspace json `laserDiameter": 0,` I changed to `laserDiameter": 1.0,` and increased the `"machineBeamDiameter": 0.2,` in the settings json.

Once imported I still do not get any laser preview.

**Comment by openhardwarecoza** [comment]
Beam Dia in Settings tab?

**Comment by iceblu3710** [comment]
Increased to 1.0 as well and no changes

**Comment by iceblu3710** [comment]
Problem traced to a minor version difference in Chrome between Linux and Windows.

Not working on:
Ubuntu Linux 4.4.0-57-generic Chrome Version 55.0.2883.87 (64-bit)

Working on:
Windows 10 with Chrome Version 55.0.2883.87 m (64-bit)

Will wait for a Linux Chrome update. Closed for now.
