### ISSUE TITLE
Floating Controls fails to appear

### ISSUE THREAD

**Issue by rilliam** [LaserWeb/LaserWeb4#137]
**Problem description:** Floating Controls fails to appear until the window zoom is changed.

**Chrome versions:**  55.0.2883.87 and 56.0.2924.87
**Platform:** Windows 7 x64 (xeon)
**Notes:** 
Tested on 1280x014 and 1900x1200 screen resolutions.
Disable all extensions.

**To reproduce this problem:**

1. Click Add Document, and add a DXF document.
2. Select Document from Document List.
3. Note that floating controls is unavailable.
4. Note that Document shape is highlighted in workspace.

**Comment by tbfleming** [comment]
fixed
