### ISSUE TITLE
Floating controls input box values fail to update

### ISSUE THREAD

**Issue by rilliam** [LaserWeb/LaserWeb4#138]
**Problem description:** Floating controls input box values fail to update after selection of Document other than first Document in list.

**Chrome versions:**  55.0.2883.87 and 56.0.2924.87
**Platform:** Windows 7 x64

Tested on 1280x014 and 1900x1200 screen resolutions.
Document type tested: DXF

**To reproduce this problem:**

1. Click Add Document, and add a DXF document
2. Adjust drop-in coordinates of Document to 0,0
3. Click Add Document, and the same DXF document again
4. Select second instance of Document from Document list
5. Note that the input box values in the Floating Controls fails to update to the new drop-in coordinates of the second Document in the Document List

**Comment by tbfleming** [comment]
fixed
