### ISSUE TITLE
Chrome 'Page Unresponsive' message

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#141]
The 'Page Unresponsive' message regularly appears during long gcode generation operations.
Often pressing the 'wait' button results in incorrectly generated gcode.

Can this be overcome?

![screen shot 2017-02-04 at 4 22 11 pm](https://cloud.githubusercontent.com/assets/14358950/22615973/e2f200d8-eaf6-11e6-896e-2cbab40a33f4.png)

**Comment by jorgerobles** [comment]
@lautr3k?

**Comment by tbfleming** [comment]
Not @lautr3k's problem. Gcode generation needs to eventually move to a web worker.

**Comment by lautr3k** [comment]
@DarklyLabs you can use the [lw.raster-to-gcode demo page](https://lautr3k.github.io/lw.raster-to-gcode/dist/example/) until the worker is implemented, the demo use a timer to avoid blocking the UI.
PS.: @tbfleming you can enable it with the `nonBlocking` setting ;)

**Comment by jorgerobles** [comment]
@DarklyLabs non blocking implemented!

**Comment by DarklyLabs** [comment]
@jorgerobles Just ran a few tests. Didn't get a non-responsive message at all.
The only thing we noticed is the need to keep an eye on the amount of ram Chrome is using during big rastering tasks. We managed to lock up OSX a few times by running our of ram.

**Comment by DarklyLabs** [comment]
@jorgerobles By the way, the progress indicator is AWESOME!
Well done.

**Comment by openhardwarecoza** [comment]
@DarklyLabs made me do a git pull to see what he is talking about... Had to make a gif, to confirm AWESOME indeed

![progress bar](https://cloud.githubusercontent.com/assets/7695323/22822868/dd527e22-ef89-11e6-84a2-54ce16e61561.gif)

**Comment by cprezzi** [comment]
@jorgerobles Is it possible that generation of raster gcode is much faster since you added this feature?
It seems so to me!

**Comment by jorgerobles** [comment]
I wish! :smile:
