### ISSUE TITLE
Cannot access settings section

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#144]
OSX / Chrome Version 56.0.2924.87 (64-bit)

http://recordit.co/zJH6ltHtlh/gif/notify

**Comment by tbfleming** [comment]
@jorgerobles 

![image](https://cloud.githubusercontent.com/assets/418464/22676622/8d6d9e68-ecba-11e6-8a0e-e988d2aa85bd.png)

**Comment by jorgerobles** [comment]
Thank you @cojarbi, @tbfleming seems webcam settings are getting messy all the time. Should be fixed by now :|

**Comment by cojarbi** [comment]
i can access now, thanks
