### ISSUE TITLE
Failure to render all SVG

### ISSUE THREAD

**Issue by maudette01432** [LaserWeb/LaserWeb4#146]
Having an issue with LW4 rendering SVG.   I have provided a simple test case out of inkscape with the letters TUIT as closed paths as written out of inkscape.  The cam operations can see the paths but they are not rendered in the viewer.  One letter is red the others are black.  

See screen shot below (prior to changing fill of first "T" to red.

![screen shot 2017-02-08 at 3 31 42 pm](https://cloud.githubusercontent.com/assets/2135887/22757439/bd150d36-ee18-11e6-95a1-ca5a91be4e8c.png)

Source file having issues with.  Because it's so simple hopefully it can be used to resolve the problem.  The "T"s in question have only 32 nodes.

[tuit.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/761945/tuit.svg.zip)

This renders improperly on both Mac OS X Sierra w/ chrome and Windows 10 w/ chrome.

**Comment by maudette01432** [comment]
Interestingly the operations seem to work even though it doesn't render like this laser_fill_path operation which does a crosshatch.

![screen shot 2017-02-08 at 4 28 44 pm](https://cloud.githubusercontent.com/assets/2135887/22758542/1c0519c2-ee1d-11e6-8766-4598f5f99e67.png)

The vcarve operation...while it seems to engave the letters OK seems to also have some big vertical lines rendered.

![screen shot 2017-02-08 at 4 32 26 pm](https://cloud.githubusercontent.com/assets/2135887/22758567/389cc67a-ee1d-11e6-945b-c80c7430001b.png)

The GCODE on this is definitely bad.  Path 18 seems to be off in la-la land.

**Comment by jorgerobles** [comment]
@lautr3k got this on console loading up the file attached. Could be of help?

![image](https://cloud.githubusercontent.com/assets/1706080/22759618/58f50906-ee53-11e6-9245-a22ce4e0fd12.png)

**Comment by lautr3k** [comment]
Work great on the lw.svg-parser demo page (https://lautr3k.github.io/lw.svg-parser/dist/example/) :
![image](https://cloud.githubusercontent.com/assets/796149/22772431/dc9154c4-ee9c-11e6-98a6-1b62a97fb863.png)

**Comment by jorgerobles** [comment]
@lautr3k, @tbfleming  After a while I've tracked down the problem to LW4 gets choked with relative coordinates. "m" coordinates are not rendered properly. 
AI converts to "M" coordinates and run ok, Inkscape use "m" ones and shows nothing, I think it goes outside GL object bounds.

[tuit_original_AI.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/763607/tuit_original_AI.svg.txt)

**Comment by tbfleming** [comment]
Laser Fill Paths won't work if there's a problem with lw.svg-parser. The bugs happen after that stage.

Bug 1:  some shapes hit a limitation in the poly2tri library. This only affects the canvas. We need a replacement, but every triangulation library I've tried (even three's) hits issues, they just vary with which conditions cause them to fail.

Bug 2: some shapes cause vcarve to mess up badly. It may be a while before I get around to looking at vcarve again.

**Comment by tbfleming** [comment]
Bug 1: I added a workaround until someone gets a round TUIT for making a decent triangulation library. It now shows a red stroke if poly2tri fails and the original stroke is invisible.

Bug 2: track in #143 

![image](https://cloud.githubusercontent.com/assets/418464/22865873/6a2c5bc2-f13a-11e6-883d-b6032db8cbb4.png)

**Comment by openhardwarecoza** [comment]
Working well enough, no recurrence of complaints. Closing

**Comment by maudette01432** [comment]
I haven't complained because I thought it was still being fixed?!

For the record the work around is nice...but I still can't see the fill colors or the outline colors for selecting operations.

**Comment by jorgerobles** [comment]
A light review of this issue, the original file throws colinear error on latests poly2tri. 
So I guess that T where not closed paths. Opening on AI autofix colinear.
![image](https://cloud.githubusercontent.com/assets/1706080/26296783/7e5e1ae8-3ed0-11e7-98bf-7254fdcbd10c.png)

**Comment by jorgerobles** [comment]
@tbfleming https://sourceforge.net/p/jsclipper/wiki/Home%206/ B4.2 Cleaning, can we apply this clean method to polygons whenever that exception arises?

**Comment by tbfleming** [comment]
I already use Clipper to clean it. Colinear doesn't mean the path isn't closed. The JS port of poly2tri doesn't cover the hardest cases that the original C++ version does. These harder cases are all valid polygons that Clipper, boost::polygon, and the rest of our code is OK with. Last time I looked, none of the JS triangulation libraries handled all hard cases, but different ones handle different subsets of the hard cases.
