### ISSUE TITLE
Rotate vectors / images

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#147]
The ability to adjust the rotation of a document on the workspace.

**Comment by jorgerobles** [comment]
@tbfleming Is this very difficult to implement?
I've tried https://webglfundamentals.org/webgl/lessons/webgl-2d-rotation.html but seems scaled on rotation. Maybe relates with 2d transforms on 3d viewport.

**Comment by tbfleming** [comment]
@jorgerobles scale and rotate get along with each other as separate fields, but the math gets complex when you add a rotation field since all 3 fields interact with each other. The easy method is to switch to a single matrix:

* Drop document's translate and scale fields and replace them with a matrix. The single matrix will handle translate, scale, rotation, and skew. gl-matrix has functions to help with this.
* Rewrite code in document-cache and workspace which deals with document bounds; the approach I currently have uses an optimization which is incompatible with rotation.
* Change the vertex shaders to use a matrix uniform instead of translate and scale uniforms
* Update the code in the workspace which manipulates translate and scale to manipulate the matrix instead
* Change ```rawPathsToClipperPaths``` to use the matrix instead of separate translate and scale fields. This will make all of the cam's vector operations work correctly.
* Add rotation to lw.raster-to-gcode; it'd be nice if we have a second person who works on this code.
* Add code to update the documents in old files.

**Comment by jorgerobles** [comment]
Thanks!.. Seems daunting 😨

**Comment by openhardwarecoza** [comment]
(: theres always the "LW isnt a CAD package" argument (;  
Simple positioning yes, rotating might count as "rather use cad"

**Comment by DarklyLabs** [comment]
Move, Rotate and Scale are basic manipulations needed for placement. Even the ability to just rotate a design 90degrees CW or CCW would be beneficial.

Users shouldn't have to jump back into a CAD package if they simply wanted to rotate a design to fit   a free area of material they have.

**Comment by tbfleming** [comment]
90 degrees simplifies things. For vectors, edit the rawPaths; you don't need to touch the shaders. For bitmaps, run them through a transform then store them back into dataUrl.

**Comment by tbfleming** [comment]
You'll also have to adjust scale and translate to compensate.

**Comment by jorgerobles** [comment]
Powerful image manipulation https://www.npmjs.com/package/jimp

**Comment by domenic-d** [comment]
@jorgerobles Will this handle vectors as well?

**Comment by jorgerobles** [comment]
Seems not. I just posted as a reference.

**Comment by tbfleming** [comment]
@domenic-d I'll take care of vectors. @jorgerobles is looking for a way to handle images without relying on separate translate, scale, rotate fields, which will go away. I'm going to replace them with a matrix.

**Comment by tbfleming** [comment]
Here's why we have to shift to matrices for rotation. I said above "the math gets complex when you add a rotation field since all 3 fields interact with each other." I sugar coated that. In some cases the math becomes impossible to solve. Here's one of those cases.

![image](https://cloud.githubusercontent.com/assets/418464/26686105/fc891a8a-46b9-11e7-9912-9dafb51ef34d.png)

If we have separate rotate and scale fields, then we have to decide which one happens first. If we scale the original object then rotate it, then A can transform into B, but B can't transform into A. If we rotate first, then B can transform into A, but A can't transform into B. Either approach adds a restriction to the UI. e.g. if we rotate first, then a user wouldn't be able to rotate an object they already scaled.

Matrices doesn't restrict order. The user can freely rotate and scale in any order. A major downside is lw.raster-to-gcode doesn't understand it. @jorgerobles will have to either preprocess the image before lw.raster-to-gcode or do serious surgery on lw.raster-to-gcode.

**Comment by jorgerobles** [comment]
I will go preprocessing, even we have to store the original and the transformed one, will be better.
I would like @lautr3k could lend us a hand... are you there? 😇

**Comment by jorgerobles** [comment]
@tbfleming as we talked before please do a branch, I hope not, but can be a long task.

**Comment by tbfleming** [comment]
I just pushed a new branch: rotate. It can now rotate vectors. I haven't ported the workspace handling of images to the matrices yet. Image display is currently broken.

todo (me):
* Fix workspace image support (loading, loading in SVG, displaying, selecting)
* Fix dxf import
* Translate old workspace files to new format

**Comment by domenic-d** [comment]
@tbfleming Thanks for the explanation. Please let me know when you need some specific testing performed and i will jump onto it.

**Comment by tbfleming** [comment]
@domenic-d go ahead and test what's there. Don't do the following yet:
* Load an image
* Load an SVG that contains any images
* Load a DXF
* Load an old workspace file

**Comment by domenic-d** [comment]
Its great to see this functionality making its way into LW.
Some feedback:
1: Typing rotation values works well.
2: Clicking the increase/decrease arrows sometimes over-ran the number of clicks made. Couldn't work out how to consistently replicate this.
3: Deselecting the document and then re-selecting it set its rotation back to zero. It would be useful to retain its rotation value so it can be reset to the original orientation.
4: The value window constantly moving as rotation was being applied made it a little tricky, especially when the increase/decrease arrows were being used.

**Comment by tbfleming** [comment]
3 is tricky; there is no rotation value, so it creates a phantom one when the selection changes. When the field changes it computes a rotation matrix from the difference of the two values then multiplies that matrix to the individual matrix of each selected object.

**Comment by tbfleming** [comment]
Ditto with size; there never was a size member; it always computed it on the fly.

**Comment by tbfleming** [comment]
No. That creates the math problem I mentioned above.

**Comment by domenic-d** [comment]
Thanks Todd. Having this feature in LW is a huge benefit. If the user has to eyeball the rotation or even reload the doc then so be it.

**Comment by tbfleming** [comment]
It can now load image files and rotate them.

**Comment by tbfleming** [comment]
@jorgerobles: here's how the doc is now set up: The image occupies a rect with bottom-left corner at 0,0 and upper-right at W,H. The conversion to WCS assumes 1 pixel in the bitmap is 1mm. So, a 1000 x 1000 pixel bitmap is 1m x 1m. The document's transform2d matrix scales, rotates, and translates it to the final WCS bounds.

**Comment by tbfleming** [comment]
Users may combine Rotate & Scale to skew an image:

![image](https://cloud.githubusercontent.com/assets/418464/26749212/6cb8c42a-47d4-11e7-923b-f3cc3e51be74.png)

**Comment by cojarbi** [comment]
Work as expected with the same points described above
clicking the restore icon ( back red arrow ) makes the image disappear

**Comment by cojarbi** [comment]
@jorgerobles restore is working now. Will it be able to restore also the rotation? Correctly it does not

**Comment by tbfleming** [comment]
It now loads transformed images embedded in SVG files.

**Comment by tbfleming** [comment]
Bug note: you may have to ungroup everything in Inkscape if you do transforms because of #332.

**Comment by tbfleming** [comment]
Group bug fixed.

**Comment by tbfleming** [comment]
@domenic-d 

> 5: Size values change as the doc is rotated. I am in two minds about this. On one hand, it would be good to not change the size (since rotation shouldn't be changing it), but the way it is expressed (as x&y) makes sense to have it show a change.

I just tried this on Inkscape. It does the same thing we do with the size. It also doesn't have a rotation value that the user can reset that I could see.

**Comment by tbfleming** [comment]
DXF updated. Not tested.

**Comment by tbfleming** [comment]
It can now load old workspaces.

**Comment by domenic-d** [comment]
@tbfleming  Just back to testing now.
The sizing with rotation is fine the way it is. Users can just make sure they keep the x-y size locked and they won't experience any skewing of their image.

What is the intention of the red undo arrow with raster images? It currently distorts the image when applied.

**Comment by domenic-d** [comment]
DXF loading and rotating  looks to be working as expected.
Image loading and rotating looks to be working as expected.

Raster Opt & Reset distort image when a rotation other than 90 degrees has been applied.

**Comment by jorgerobles** [comment]
Red undo is related with raster optimization, that adjusts dpi to laser
beam, many months ago #132.

Last patch commited only works with scale. But has to be fixed as now scale
and rotation goes together.

**Comment by jorgerobles** [comment]
I'm almost completed the first approach to raster transforms.

Pending bugs
- image offsets
- A axis deformation

![image](https://cloud.githubusercontent.com/assets/1706080/26762421/5fbab57a-4942-11e7-97b5-0fecec83604c.png)

![image](https://cloud.githubusercontent.com/assets/1706080/26762424/87a03312-4942-11e7-93df-d229eeab8795.png)

**Comment by tbfleming** [comment]
@jorgerobles: I added this after context creation to expose what's happening:

```
ctx.fillStyle = 'black';
ctx.fillRect(0,0,w,h);
```

![image](https://cloud.githubusercontent.com/assets/418464/26762760/9249c274-4915-11e7-98e2-aa009b74de53.png)

It's aligning the lower-left corner of raster-to-gcode's output to one of the transformed corners of the image. You need to align center-to-center instead.

**Comment by jorgerobles** [comment]
Ugg can't get it right. Tried translation on transform2[4] and [5] but nup.

**Comment by tbfleming** [comment]
@jorgerobles I fixed that part for you.

**Comment by jorgerobles** [comment]
@tbfleming I've matched Raster A Axis transform to dev-es6 branch behaviour, maybe vector offsetting is not?

![image](https://cloud.githubusercontent.com/assets/1706080/26817944/041a2748-4a99-11e7-9acf-872866ec8442.png)

**Comment by tbfleming** [comment]
@jorgerobles fixed.

**Comment by tbfleming** [comment]
Oops. That introduced a new bug: laser spacing will be off.

To fix that, don't use axisAFactor in params. Instead scale the output gcode.

**Comment by jorgerobles** [comment]
Reducing Y ppi, or postprocessing?

**Comment by tbfleming** [comment]
postprocessing

**Comment by tbfleming** [comment]
Found a different bug while testing. I used the del key shortcut on vector objects. That left the children members of the parents untouched, which causes all kinds of issues.

**Comment by jorgerobles** [comment]
Ok, will dig on that

**Comment by jorgerobles** [comment]
@tbfleming, multiply beam diameter by aAxisFactor in params is not enough?

**Comment by tbfleming** [comment]
@jorgerobles beam diameter affects both X & Y spacing.

**Comment by domenic-d** [comment]
Just running some more testing on the rotate. Seems to be working correctly with both vectors and raster images.
Is it at a point it could be merged in with dev-es6?

**Comment by tbfleming** [comment]
It looks like it. @jorgerobles any more issues you know of?

**Comment by jorgerobles** [comment]
Nup. I think is ready ;)

**Comment by domenic-d** [comment]
If no one has any objections, I believe this can be now closed?
