### ISSUE TITLE
4th Axis TO THE MAX! 

### ISSUE THREAD

**Issue by FabCreator** [LaserWeb/LaserWeb4#149]
So far not much has been done with the 4th axis, with our kits starting to leave us really soon, i am hoping i can turn my attention to continuing to develop the hardware :)

So i thought id throw a few ideas I have for the 4th axis:

I was thinking about engraving cylinders which are not straight, like glasses bottles etc they have shape to them.

Would it be possible to create a Z path for the laser to follow. (example below)
![untitled-2-01](https://cloud.githubusercontent.com/assets/19230933/22856429/82508b14-f091-11e6-92ea-5f8fa217276b.png)

This way you could easily photograph the object side on sketch the curve and then you have the ability to engrave non standard objects without the need for a fancy sensor.

Another 4th axis use is a motorised pass through, engrave the board you have and then the 4th axis drive the board to the next area. this could be used as part as an auto feeder ;)

Cheers,
Bonne

**Comment by DarklyLabs** [comment]
This is a great idea.

**Comment by openhardwarecoza** [comment]
@tbfleming something you'd consider or something we'll close off?  (:

**Comment by tbfleming** [comment]
Not anytime soon
