### ISSUE TITLE
[Workspace] 3d glitches and misbehaviors

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#15]
Hi, I've detected some glitches on 3d rendering, on window resizing (appears a black refresh).
Also, the trackball events are not confined over the canvas, so, clicking some element (document tree, for example) makes camera to change position (Ugh!)

I've tracked issue up to http://stackoverflow.com/questions/13670886/allow-mouse-control-of-three-js-scene-only-when-mouse-is-over-canvas,
Digging into code I've got dead end on components/workspace.js::80

**Comment by tbfleming** [comment]
It currently does what the stackoverflow answer says :(

**Comment by tbfleming** [comment]
I suspect the answer will be to refactor TrackballControls:
* Extract state and move it to the redux store. It will no longer touch the camera directly.
* Rewrite event handlers to use React's event system.

**Comment by tbfleming** [comment]
TrackballControls, and its problems, are now gone because of the switch to regl (#16)

**Comment by jorgerobles** [comment]
osx 10.9 and chrome  54.0.2840.98 (64-bit)

![weird_axis_bug](https://cloud.githubusercontent.com/assets/1706080/21072250/2f38ecde-bebc-11e6-83e8-6f257c9e577a.gif)

**Comment by jorgerobles** [comment]
@tbfleming As far I inspected, camera is undefined on Dom3d mount, so no transform is applied and axis are away from viewport. I suspect a componentWillMount on Workspace should fix that.

**Comment by tbfleming** [comment]
It was a bug in Dom3d.componentWillUpdate(nextProps). It used this.props instead of nextProps.

**Comment by jorgerobles** [comment]
Gone :) Thanks @tbfleming
