### ISSUE TITLE
Can't get gcode after merge of dev-es6

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#153]
@tbfleming @jorgerobles I have merged the changes of the last 10 days of dev-es6 into my dev_comms branch and now I don't get the gcode anymore (with `this.props.gcode`).
Has something changed how to get the gcode?

**Comment by jorgerobles** [comment]
Yes, gcode is now state.gcode.content
Was necessary for progressbar

**Comment by cprezzi** [comment]
No problem. Found it in the meantime ;)
