### ISSUE TITLE
Workflow & usabillity

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#154]
At the moment, LaserWeb4 starts to the com tab, but I think it would make sense to change the order of the tabs to match the workflow. 

The workflow I see is:
1. CAM - load file, define operations, generate gcode
2. COM - connect to the machine
3. JOG - run the job
...

What do you think? @openhardwarecoza @jorgerobles @tbfleming @lautr3k @DarklyLabs @FabCreator ...

**Comment by tbfleming** [comment]
Sounds good
