### ISSUE TITLE
Future Feature Wish: Job Library / History

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#155]
So, in the news today, Eleksmaker, seems to have pulled some inspiration from LW3 

``` 
if ( "Imitation is the sincerest form of flattery" == true ) {
    console.log("LW is so famous even the Chinese  copy us")
}
```

![eleksmaker vs lw](https://cloud.githubusercontent.com/assets/7695323/22963547/4d4b7c12-f35c-11e6-9364-c1ba4fc60b02.PNG)

On a sidenote, EleksCAM seems to be more of a "skin" over Benbox than an outright copy.   At least it doesnt appear to be nodejs. 

![elekscam](https://cloud.githubusercontent.com/assets/7695323/22963553/5156ccda-f35c-11e6-9716-34490cd996cb.PNG)

That said, they do have one or two cool features we might want to steal from (fair game right?)

#  View quick set
![viewer](https://cloud.githubusercontent.com/assets/7695323/22963576/75ee2606-f35c-11e6-89bd-41fd20a65b3c.PNG)

# Gallery of included jobs
![gallery](https://cloud.githubusercontent.com/assets/7695323/22963585/7e4c5854-f35c-11e6-9c26-46befd858c7e.PNG)

**Comment by FabCreator** [comment]
Both of those a very nice features. Also I belive they say opensource. So it's fair game. Let me find a documentary for you Peter. Its about the china and how everything is opensource they just don't share. ;)

**Comment by FabCreator** [comment]
https://www.youtube.com/watch?v=SGJ5cZnoodY

**Comment by jhiner1978** [comment]
Steal away, I say. I would love to have a gallery of previous jobs so I can go back and engrave/CNC old jobs. As for 3d view select, that is a great idea as well. Would be even better to add arrows under each view to rotate said view. Corner views would be cool too like fusion 360.

**Comment by cprezzi** [comment]
I belief the 3d view buttons don't make sense at the moment. All supported operation are max. 2.5d, so the only useful views are from top or diagonal. From the sides it would only be some lines in differen depth.

**Comment by cprezzi** [comment]
But I like the History feature. This could list the history of all generated cam operations, which could be recalled (including all cam settings).

**Comment by openhardwarecoza** [comment]
Ahh you just took Gallery as I was thinking of it (ie some sample DXFs) and
added the idea of Past Jobs! (Localstorage isnt big enough, but hey we
already have workspace export, all we need is a way to dump a preview
render and store it in nodejs backend)

**Comment by openhardwarecoza** [comment]
Agreed on the side view, but i was thinking actually instead of the current
"Reset view button" - if you move it around with the mouse and want to
returns to some view.  Maybe not side, sure, but maybe standards like
isometric, corner perspective, top down, etc?

**Comment by cprezzi** [comment]
I was allready thinking about a job history store on the server and also sending back the running gcode in case the browser was closed an reopened (or a second browser is connected), but a CAM history would be even better, because you could change some settings before re-run the job.

**Comment by openhardwarecoza** [comment]
I love that idea!
