### ISSUE TITLE
Add section to view / inspect gcode text

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#156]
We have a section for this in LW3

**Comment by tbfleming** [comment]
We had it for a while in LW4; it killed performance. Chrome has issues with fields containing huge text blocks (Firefox is much worse). React magnifies that.

**Comment by gndprx** [comment]
If that is the component that cripples my browser in LW3, then I'm all for leaving it out.

If anything, maybe a button to pop-up the generated g-code for review for anyone who really wants to review it in session.

**Comment by openhardwarecoza** [comment]
there is a download button on the cam tab (familiar stiffy save icon)

**Comment by cojarbi** [comment]
The download is there, it just happened that I needed to see the code before executing but not at the expense of usability or speed. If there is no way to add a preview we can close this

**Comment by jorgerobles** [comment]
@cojarbi take a look for a shiny view gcode button :)

**Comment by cojarbi** [comment]
Very elegant as always @jorgerobles thanks
