### ISSUE TITLE
raster generate button broken

### ISSUE THREAD

**Issue by rilliam** [LaserWeb/LaserWeb4#161]
**Problem description:** Raster gcode generation button does nothing when clicked.

**Chrome versions:**  56.0.2924.87
**Platform:** Windows 7 x64 and 32

Tested on 1280x014 and 1900x1200 screen resolutions.
Document type tested: PNG

**To reproduce this problem:**
Add png document to task and select laser raster from type selection drop down.
Populate passes and cut rate fields.
Click the Generate button

**Comment by jorgerobles** [comment]
Late night bug. Fixed

**Comment by openhardwarecoza** [comment]
Pushed to gh-pages?

**Comment by jorgerobles** [comment]
In a minute

**Comment by jorgerobles** [comment]
done
