### ISSUE TITLE
Put Console back to bottom right corner?

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#162]
Could we please place the console back to the bottom right corner (like on LW3)?
The messages in the console are important for machinig, but are often out of view on many screens. It also doesn't make sense to have the console on multiple tabs (com & jog).

![image](https://cloud.githubusercontent.com/assets/5457949/23104269/bed0ef9a-f6ca-11e6-815a-47ca34801d1c.png)

**Comment by openhardwarecoza** [comment]
I agree (:

**Comment by tbfleming** [comment]
Does the console serve a purpose outside of comms and jog?

**Comment by openhardwarecoza** [comment]
In lw1-3 it served as all round notifications (updates available,  news,
 progress updates,  syslog,  error log,  etc)

**Comment by tbfleming** [comment]
And is promptly ignored by most users because of this large amount of messages, even me, except when I'm entering gcode.

**Comment by openhardwarecoza** [comment]
I wouldnt say "most" ...

Most of the old hands (and very quickly the new guys realise it too) know
the syslog contains valuable info when things go wrong.  It also helps us
to say "check the syslog, was there any errors about xyz"

In that argument though, position wouldnt be the problem, the information
being displayed would be the issue (adjustable verbosity might be a better
idea - ERROR/WARN/INFO/DEBUG?)

@lautr3k 's Optimisation rewrite of LW3 (which sadly never got used)
actually had a syslog that majorly improved on what was in lw1-3 :  See
https://github.com/LaserWeb/lw.comm-server/issues/2#issuecomment-274247359

**Comment by cprezzi** [comment]
@tbfleming Yes, I think the console can be of use on all tabs for notification. Often I switch to other tabs while running a job and then I would like to still see the notifications. 

Also, the spece @ bottom right is feeling soo lonely empty ;)

**Comment by cprezzi** [comment]
Yes, I think the console could be of value on all tabs for notifications. I often change to other tabs while running a job but don't want to miss a notificaion. The actual position in the com/jog tab is often out of view and therefore useless.

But the main reason to move it there is, the space at bottom right is soo empty lonely ;)

**Comment by cprezzi** [comment]
We could implement a verbose level to reduce the reports in the console, like I have allready done on server side.

**Comment by jorgerobles** [comment]
I could put back in a minute, just say the word

**Comment by openhardwarecoza** [comment]
"the word"  lol

**Comment by jorgerobles** [comment]
B-bird's the word oh well-a bird bird bird

**Comment by cprezzi** [comment]
This was quick, probably a bit too quick. ;)
The console/syslog should be right of the existing elements, not bellow. This way it takes too much space.

**Comment by jorgerobles** [comment]
There ;D

**Comment by cprezzi** [comment]
Yep, right there :) Thanks!
