### ISSUE TITLE
Active Gcode "Generate" button

### ISSUE THREAD

**Issue by donkjr** [LaserWeb/LaserWeb4#167]
This may not be viewed as a bug. 
While learning LW4 there have been multiple instances where I could not get the image on the palate to behave as I expected. 
One tell tale indication is that the "Simulator" button would not do anything or after a change in setting it acted like nothing had changed. 
It seems that after an operation that changes the documents shade or the contents therein the GCODE menu: "Generate" button needs to be pushed.
This makes sense but it was not always obvious to me that I had done something that required the Gcode to be re-"Generated".
"As a LW4+ user I would like the "generate button" to actively indicate when something is changed in the settings or content that would expect the Gcode to be re-generated".

**Comment by jorgerobles** [comment]
So any change on Settings, Operations, and Documents should mark a "dirty" state isn't it?
@tbfleming  any Redux Black Magic to dispatch GCODE_DIRTY on any others reducers change?

**Comment by tbfleming** [comment]
@jorgerobles : the gcode reducer can listen for all actions which begin with DOCUMENT_ or OPERATION_. It will have to ignore changes to document.selected, document.visible, operation.expanded, and operation._docs_visible.

**Comment by jorgerobles** [comment]
Hmm  @tbfleming  It can watch for other events but the state is scoped to GCODE. So cannot ignore specific changes :| (as far as I know)

**Comment by tbfleming** [comment]
The gcode reducer decides what actions it does and does not listen to.

**Comment by jorgerobles** [comment]
Yes, that is correct, but  `state` variable is not loaded with all the state, only with gcode state.
I hope calling getState from action obtains the preprocesed overall state, if not, I have to move gcode reducer last on the combineReducers list

**Comment by tbfleming** [comment]
The actions have everything you need; you don't need anything in the document state or the operation state.
* if action.type begins with DOCUMENT_ or OPERATION_, but is not DOCUMENT_SET_ATTRS or OPERATION_SET_ATTRS then light the button
* if action.type is DOCUMENT_SET_ATTRS and any field is present that is not 'selected' or 'visible' then light the button
* if action.type is OPERATION_SET_ATTRS and any field is present that is not 'expanded' or '_docs_visible' then light the button

**Comment by jorgerobles** [comment]
Ook, I understand now. I need a nap.

**Comment by cprezzi** [comment]
This issue is probably related to #170.

**Comment by jorgerobles** [comment]
This is done and live!
