### ISSUE TITLE
Show total time passed for a given job

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#173]
Display the total machine time of a completed job. This could also account for stoped jobs maybe.
Pauses could just hold the timer and continue on resume

**Comment by openhardwarecoza** [comment]
https://github.com/LaserWeb/LaserWeb4/issues/110 isnt that the same?

**Comment by cojarbi** [comment]
So I'm embarising myself by duplicating a perfectly openned issue by me. Maybe the title I wrote confused me. Should we keep this new ones separate or delete dmteh new ones and keep the old one

**Comment by openhardwarecoza** [comment]
Keep the oldest one (:

**Comment by cojarbi** [comment]
Sorry guys
