### ISSUE TITLE
Macro not being executed

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#174]
This might be already know.

**Comment by cojarbi** [comment]
I thought it was me, it not working for me either

**Comment by jorgerobles** [comment]
@cojarbi, @DarklyLabs, the action MACRO_FIRE is working (UI), 
It should be related to comms integration.
@cprezzi ping me if you need assistance.

**Comment by cprezzi** [comment]
I didn't look at the macros yet. It probably would be enough include the runCommand function from com.js  and attach the macro click to it, like I had to do on the console. I will check that today.

**Comment by cprezzi** [comment]
It's done. Please test.

**Comment by DarklyLabs** [comment]
@cprezzi Tested and working correctly. Thank you.
