### ISSUE TITLE
Save settings / profiles / app snapshot not working in electron app 4.0.36

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#178]
Im not sure this is a bug, most likely not coded yet since the save action maybe its not the same for the app. Load does work.

I could not test in 4.0.40 as i dont have a build.

**Comment by DarklyLabs** [comment]
Tested in 4.0.40 and the save feature does work.
The one bug I can see is that if 'cancel' is selected when saving then a null.json file is still saved.

**Comment by cojarbi** [comment]
@DarklyLabs is this on an electron app?

**Comment by DarklyLabs** [comment]
@cojarbi No, we are working from dev-es6 for now.

**Comment by cojarbi** [comment]
@DarklyLabs i suspect this is an issue with the electron desktop app only. I have tried dev-es6 4.0.40 and it also works for me

**Comment by DarklyLabs** [comment]
Just including @jorgerobles on this.

**Comment by jorgerobles** [comment]
I'll check ASAP

**Comment by jorgerobles** [comment]
@openhardwarecoza please add this an [ELECTRON] tag.

**Comment by openhardwarecoza** [comment]
done.

**Comment by openhardwarecoza** [comment]
@tbfleming @jorgerobles 
Prompt is not supported under electron, thats why these doesnt work. We will have to replace prompt() where its used with something that is supported in electron

**Comment by openhardwarecoza** [comment]
https://github.com/electron/electron/issues/472

**Comment by jorgerobles** [comment]
Ok, will find a polyfill.

**Comment by jorgerobles** [comment]
https://github.com/konsumer/electron-prompt?files=1

**Comment by jorgerobles** [comment]
Added npm dialog for electron with fallback on native dialogs on browser. Please check

**Comment by jorgerobles** [comment]
Indeed thanks to @cojarbi We have found worse errors. Cannot overload Window. several "services" are bound to window (window.videoCapture, that handles webcam streams) but are not found on electron builds.

**Comment by DarklyLabs** [comment]
@jorgerobles You probably already are aware but the save button is still not functional in electron 4042.

**Comment by jorgerobles** [comment]
@DarklyLabs Yes I am, thanks. I did a couple of comments before yours, I was expecting to solve them easily but not. Anyways, native chrome prompts and confirms are not working. That's the reason it's failing, and so I'm looking solutions.

**Comment by jorgerobles** [comment]
@DarklyLabs should work now with latest compile.

**Comment by DarklyLabs** [comment]
@jorgerobles Compiled for mac successfully.
Save button now working. Even opens up a dialog box to choose where to save to now. Yeah! Well done.
Settings tab is working again.
Machine and GCode tabs are missing some headings above text areas.

Having some trouble compiling for windows. Will keep at it. Perhaps someone out there could verify if windows is compiling correctly for them?

**Comment by openhardwarecoza** [comment]
Just compiled on Windows, without issue

cd ../LaserWeb4
git pull
npm run installdev (to grab new modules and new lw.machines)
cd ../lw.comm-server
git pull
npm install (just in case)
npm run dist

**Comment by jorgerobles** [comment]
:)
