### ISSUE TITLE
Add recent used files section

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#182]
Just an idea, maybe cache the location of the last 5 used files and display them in this spot as a collapsable section. Or a refresh button for the file.

When working on a project sometimes you need to make small changes to the design 

<img width="304" alt="screen shot 2017-03-01 at 5 32 45 pm" src="https://cloud.githubusercontent.com/assets/16444438/23485872/702c8b18-feab-11e6-96d3-761f9d6e8069.png">

**Comment by openhardwarecoza** [comment]
Planned: see https://github.com/LaserWeb/LaserWeb4/issues/155#issuecomment-280406502 (: gallery style
