### ISSUE TITLE
Start height not added into gcode when passes=1

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#184]
When Z-Stage is enabled, the start height is not added into gcode when the number of passes = 1.

When number of passes >1, the correct height is generated.

**Comment by jorgerobles** [comment]
@DarklyLabs please attach workspace json.
I've done a simple lasercut and the Start height is generated

![image](https://cloud.githubusercontent.com/assets/1706080/23542509/da84d324-ffed-11e6-9d6d-153f2e5fe026.png)
[z_height.json.txt](https://github.com/LaserWeb/LaserWeb4/files/816090/z_height.json.txt)

**Comment by jorgerobles** [comment]
@DarklyLabs I've found the bug on raster. Fixed!

**Comment by DarklyLabs** [comment]
@jorgerobles Just checked it. Perfect!
Thank you.
