### ISSUE TITLE
Camera Angle / Zoom presets

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#187]
We have reset view but i find that for smaller objects we could use a button to zoom and place the object (s) max to the screen

**Comment by cprezzi** [comment]
Also my opinion. Best would be to have multiple view presets like "zoom objects (top)", "zoom objects (isometric)" "workspace (top)"...

**Comment by openhardwarecoza** [comment]
Something like this from #155 

![75ee2606-f35c-11e6-89bd-41fd20a65b3c](https://cloud.githubusercontent.com/assets/7695323/24201400/9681fdd4-0f18-11e7-87e8-f8fe657bb458.PNG)

**Comment by cojarbi** [comment]
I still would like to see a button to zoom max on what there is on the canvas

**Comment by tbfleming** [comment]
I replaced the Reset View button with two zoom buttons: Mach (machine) and Doc. Doc zooms to the selected documents, or to the entire set if none are selected.

**Comment by jorgerobles** [comment]
@tbfleming I did a patch (not commited ) about views:

<pre>
 <button onClick={e=> {this.props.dispatch(setCameraAttrs({ eye:[-150,100,0], up:[0,0,1] }))}}>Left</button>
 <button onClick={e=> {this.props.dispatch(setCameraAttrs({ eye:[450,100,0], up:[0,0,1] }))}}>Right</button>
 <button onClick={e=> {this.props.dispatch(setCameraAttrs({ eye:[150,-200,0], up:[0,0,1] }))}}>Bottom</button>
 <button onClick={e=> {this.props.dispatch(setCameraAttrs({ eye:[150,400,0], up:[0,0,1] }))}}>Top</button>
</pre>

Made fast & dirty moving the camera on certain position and capturing values. Thinking on it, maybe we can expose a "named view snapshot" as a workspace setting or so. User moves to their desired camera point and then capture that view, naming it, saving on localstorage or work.
