### ISSUE TITLE
Z Stage required fields > info bubble

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#188]
When enabling z stage there is a start height field added to the operations options. Is this information bubble necessary
<img width="529" alt="screen shot 2017-03-04 at 12 38 18 pm" src="https://cloud.githubusercontent.com/assets/16444438/23580869/c7902832-00d7-11e7-8243-722c42a2edd1.png">
?

**Comment by jorgerobles** [comment]
Was an issue opened by @Darklylabs

**Comment by cojarbi** [comment]
I dont this this as an open issue. I know @DarklyLabs needs the field but not sure if the bubble is needed, cosmetic but it can be perceived as a missing field.

**Comment by jorgerobles** [comment]
Well, was not opened as an issue on github but sent me a mail and done as they requested. I agree that could be better a warning than an error, but that involves some refactoring on bubbles . I can change to any other styling if more people interested. Indeed, the bubbles are not acting as "errors" because they don't prevent operation execution.

**Comment by cojarbi** [comment]
Is this the only one thats not required? Most suer wont see it unless you turn on Z stage

**Comment by jorgerobles** [comment]
Yes, this is the only one so far. And won't be turned on if don't have Z stage.

**Comment by DarklyLabs** [comment]
This is a reminder field for users to set their correct z-height.
It is important to not be missed to avoid ruining a piece of material or causing a collision with material.
I don't see it as a big deal as it doesn't appear unless z-stage is enabled.

**Comment by tbfleming** [comment]
This warning should not be there since it only applies to emblaser. Z=0 is the starting value for machines with a top-of-material sensor.

**Comment by DarklyLabs** [comment]
@tbfleming Is it really that much of a problem to remind users to set this?
Is it causing any problems?

**Comment by tbfleming** [comment]
@DarklyLabs 0 is a valid value for non-emblaser machines; actually it will be the most common value for non-emblaser machines. I don't want to train those users to ignore messages like Microsoft does with all their useless crap in the Windows 10 notification area.

**Comment by jorgerobles** [comment]
@tbfleming, @DarklyLabs, @cojarbi.

- A solution is to present an optional Z default starting height (I think this was already discussed)
 This field will be allow to be with a machine profile, and only fills the default value of starting height on all the jobs. If disabled, no fill is done.
- Other way is to change the field to a text field, allowing, so prefilled with empty value. Then the validation will be clearly valid, as no work with Z could be without filing a number in that field.

**Comment by cprezzi** [comment]
I would prefer to have this value preset in the machine profile, or at least in the settings.
It's very annoying to see that red flyout on every operation.

**Comment by tbfleming** [comment]
@jorgerobles that sounds like a good plan, but do both of your points: change it to a string, add a setting for the default value (will be empty for emblaser), and make it complain if the fields doesn't have a number (positive, negative, and 0 are all valid).

**Comment by jorgerobles** [comment]
Done. now we have a machineZStartHeight settings to customize starting operation Z height. Must be a number, or will complain.
