### ISSUE TITLE
npm start errors

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#194]
An overnight commit is now causing start errors.

webpack: failed to compile

Tested on Win and Mac
git pull, npm install, deleted lw.comms and re-ran npm run installdev

![screen shot 2017-03-07 at 9 17 11 am](https://cloud.githubusercontent.com/assets/14358950/23632818/7c851d2e-0317-11e7-934e-0afe2b218be7.png)

**Comment by DarklyLabs** [comment]
Seems the same problem as
https://github.com/LaserWeb/LaserWeb4/issues/192

Closing

**Comment by emteeoh** [comment]
I just clued in to having been invited to join the "Laserweb Organisation", so I was able to merge my own pull request. Try updating and building now.

**Comment by DarklyLabs** [comment]
@emteeoh Yep, all good now. thx.
