### ISSUE TITLE
Show message to user when file is not supported or broken

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#195]
Currently when loading a file that is not supported or has issues LW keeps quit and can be confusing. 

Can we display a a message telling the user whats wrong?

Bellow 2 responses shown in dev tools for different cases. One is an AI file and the other is a troublesome dxf
<img width="541" alt="screen shot 2017-03-07 at 7 52 43 am" src="https://cloud.githubusercontent.com/assets/16444438/23657255/31e78a6a-030b-11e7-9e7b-e6fedfdb51dd.png">
<img width="554" alt="screen shot 2017-03-07 at 7 40 21 am" src="https://cloud.githubusercontent.com/assets/16444438/23657254/31e790d2-030b-11e7-9bf5-91c79aba9a7e.png">

**Comment by cojarbi** [comment]
@jorgerobles This is working for AI files but not in the case of the dxf that not readable like above. Did you include that in the list of reported files?

**Comment by jorgerobles** [comment]
@iceblu3710 could you check for a fix on dxf parser, if not i will add a generic catch.

**Comment by cojarbi** [comment]
@iceblu3710  in case you need a file that shows the above error
[rezervirano copy.dxf.txt](https://github.com/LaserWeb/LaserWeb4/files/832578/rezervirano.copy.dxf.txt)

**Comment by iceblu3710** [comment]
What dxf version is the rezervirano file? It has no tables section which is where the styles and layers are suppose to reside. I currently use that for the colorByLayer inharentence.

I can output an error and tell the user to save in a compatible file format.

I will likely have to branch the DXF parser library and bring it into the new century to make a more robust parser system.

**Comment by cojarbi** [comment]
@iceblu3710 this files where created from sketchup with the guitar list plug in. Im not sure why its not recognized in AI either. 

What i would want to achieve is that the user gets a warning when theres a problem with the file or is not compatible.

Exporting from sketchup via regular export in either 2000 or 14 get read perfectly

**Comment by iceblu3710** [comment]
PR #201 for my additions.

I added a default byLayer color which I should have had anyways and will log an error when an unknown entity is encountered. File loads correctly now.

**Comment by iceblu3710** [comment]
I would merge the PR but I don't know if your suppose to merge or rebase...

**Comment by jorgerobles** [comment]
It's merged! Thanks!

**Comment by cojarbi** [comment]
@iceblu3710 i found another 2 different error messages, maybe you can take a look. Im not sure whats the difference.

[RTM.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/833865/RTM.svg.txt)
[RTM2.dxf.txt](https://github.com/LaserWeb/LaserWeb4/files/833866/RTM2.dxf.txt)
<img width="552" alt="screen shot 2017-03-10 at 7 05 44 am" src="https://cloud.githubusercontent.com/assets/16444438/23794816/2a6fe848-0560-11e7-8550-5bf3e0dcda6b.png">

**Comment by cojarbi** [comment]
@iceblu3710 that second error you see above must have something to do with the update from yesterday as im getting that qhen opening the file used in #203

**Comment by iceblu3710** [comment]
That first error is in the parser which only handles R12 reliably as there is no fail or check mechinisims.

On my PR I added a log error on unknowen entity. I dont know whay an Action entity is but will dig into it this afternoon.

**Comment by cojarbi** [comment]
thanks @iceblu3710 
@jorgerobles if possible lets add first error to the list of items to display an alert to the user. Only if we are not supporting it, it would be good to add that requirement in the message " only R12" for example

**Comment by iceblu3710** [comment]
I have reworked the fail mechanism for a more verbose fail. Also included a file type reminder.

Just doing some testing now.

**Comment by iceblu3710** [comment]
PR #205 has been updated.

![pr205](https://cloud.githubusercontent.com/assets/187394/23806633/057ccec0-0588-11e7-8358-746f3a2cd3a7.png)

**Comment by iceblu3710** [comment]
@cojarbi Changes should be live

**Comment by cojarbi** [comment]
@iceblu3710 RTM2 files is generating multiple warnings for me and still get loaded empty. can we make it no load at all and then show only one warning?
http://recordit.co/7FP2RVlfiA

Sorry about RTM.dxf i loaded the wrong file
[RTM.dxf.txt](https://github.com/LaserWeb/LaserWeb4/files/835333/RTM.dxf.txt)

Now im worried that if there is not common denominator for how dxf files are generated we could go into a rabit hole.

Is there a way to just exclude all other types not supported with a single error message?

**Comment by iceblu3710** [comment]
Ues it is a large problem I found that the dxf key pair system is overly
complex due to its origins waaaay back in the day. For a "properly"
formatted file to be generated I have found only a few programs. Most
script based generators only output thier relevent skeleton.

Programs like DraftSight and some Linux apps will guess the format and fill
in the blanks but that would be a ton of extra work.

I could wrap my entire dxf lib in a try catch and throw the first error to
exit the block? Not sure if this would mess things up or not as sometimes
you still get enough of the file to be useful.

Another option could be to collect all the messages and build one big alert
at the end of the load process.

**Comment by cojarbi** [comment]
Maybe the best for the user would be:
If theres an error show just one message, if there something to load ( as you said there could be something useful in there ) still shoe the message but let the file load, the the user can decide to fix it or use whats there

**Comment by iceblu3710** [comment]
I started an error log inside my dxf converter and report the findings before handing the state file over. Tested to work on multiple files loaded at once, each gets its own report.

![grouped_errors](https://cloud.githubusercontent.com/assets/187394/23824937/0e88e8f0-0646-11e7-9bc6-072c064afa59.png)

**Comment by jorgerobles** [comment]
Great, can I suggest an 'errors found loadin files, please check console
log' and piping errors to console? will be an option if many files are
opened.

**Comment by iceblu3710** [comment]
@jorgerobles I will dump each to the console as well. Will make group copy paste for error reporting easier as well.

**Comment by cojarbi** [comment]
Is it strictly necessary to show all those messages, could be confusing to the user

**Comment by iceblu3710** [comment]
The user might only care if the file works or not but when they come asking why it would be nice not to have to tell them to check the console every time.

![logged](https://cloud.githubusercontent.com/assets/187394/23825071/806d31f4-0648-11e7-9628-644268243290.png)

**Comment by cojarbi** [comment]
@iceblu3710 displaying the message its necesary thats why i suggested it, not sure if displaying block 2 block 3 block 4 etc is necesary unless its telling you how to fix it or what needs fixing

**Comment by iceblu3710** [comment]
Do you want a generic message on every error like this:
```
Malformed DXF file, please re-save in R12 ASCII format.
Check console log for more details.
```

Then log to console like:
```
Errors found in RTM2.dxf
Unsupported dxf entity: INSERT:block 2
Unsupported dxf entity: INSERT:block 3
Unsupported dxf entity: INSERT:block 4
Unsupported dxf entity: INSERT:block 5
Unsupported dxf entity: INSERT:block 6
Unsupported dxf entity: INSERT:block 7
```

**Comment by cojarbi** [comment]
I think it makes more sense for the user. We already know that to work you need the file as R12 ASCII and will add that to documentation. Maybe you can add a " For help on this look at the docuemntation on preparing compatible DXF files on cncpro.co ( maybe we add the direct address ).

What do you guys think?

**Comment by jorgerobles** [comment]
I prefer [that](https://github.com/LaserWeb/LaserWeb4/issues/195#issuecomment-285881386) too, thanks!

**Comment by iceblu3710** [comment]
Ok, updated and tested to only log real errors and works with multiple file loading. User popup is:

```
Errors found in RTM2.dxf please re-save in R12 ASCII format.
Check console log and documentation for more details.
```

When we have a page in the wiki I can add a link.

**Comment by cojarbi** [comment]
@iceblu3710 you haven't push this correct?

**Comment by iceblu3710** [comment]
Haven't issued a PR yet. Is it the way we want?

**Comment by cojarbi** [comment]
@iceblu3710 i want to get the link but im unable to add the topic to the cncpro.co

**Comment by cojarbi** [comment]
@iceblu3710 here is the link http://cncpro.co/index.php/35-documentation/working-with-files/working-with-dxf

Maybe if possible put "Click here" as the link is very long

**Comment by iceblu3710** [comment]
"Click Here" looked weird, I think hotlinking the documentation keyword is pretty obvious though. Opens in a new tab.

![untitled](https://cloud.githubusercontent.com/assets/187394/23828863/322011da-06a5-11e7-92f0-fcdf53b823cb.png)

**Comment by iceblu3710** [comment]
PR #205
