### ISSUE TITLE
Machine Profile and Electron Cache

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#197]
Should the machine profile for the Emblaser and Fabkit be appearing in the compiled electron releases?

They do not appear when we run the electron 4.0.42 mac and pc versions, but previously imported machine profiles do appear.

Is this a caching issue and if so, how can it be cleared?

**Comment by jorgerobles** [comment]
@DarklyLabs It's done. Base profiles (starts with *) are always refreshed.

**Comment by DarklyLabs** [comment]
@jorgerobles The Emblaser and Fabkit profiles are showing up now. Well done.
We still have remanence of perviously saved profiles listed. Where is this stored and how can they be removed?
 Perhaps a complete 'reset to default' option to return everything in LW4 back to a default state?

**Comment by jorgerobles** [comment]
It's stored on localstorage. To delete an stored profile, use the delete
button on under profile selecting it first.
I could add a reset profiles under Settings->Tools

2017-03-10 3:29 GMT+01:00 DarklyLabs <notifications@github.com>:

**Comment by DarklyLabs** [comment]
@jorgerobles A reset profiles would be very useful. We have a blank profile that somehow made its way into the mix which cannot be deleted.
Being able to return to a pure vanilla version of LW could be useful for users who have been experimenting and now want a completely clean setup, since a re-install will not give them this.
