### ISSUE TITLE
Feed unit selection not being honored in Jog>Control

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#200]
Reported by Walter K on G+

When choosing mm/min in Settings> Application, Should Jog>Control be changed to mm/min also?

Im not sure if we discussed this in the past and decided not to change that, but it makes sense

![capture](https://cloud.githubusercontent.com/assets/16444438/23772771/3838efa4-04ea-11e7-98c4-84b851dbad55.PNG)

**Comment by openhardwarecoza** [comment]
To elaborate, it doesnt follow what you selected in Settings tab?

**Comment by cojarbi** [comment]
Correct, so if i choose mm/min in settings, jog>control keeps displaying mm/s 
( Am i that bad at describing :)  )

**Comment by cprezzi** [comment]
You are right, it should change corresponding to the units set. I probably just forgot it. ;)
I will check that.

**Comment by cprezzi** [comment]
Corrected with commit https://github.com/LaserWeb/LaserWeb4/commit/5bbbf72cc8440abdce1c8df1c68107e7f0425bc5

**Comment by cojarbi** [comment]
@cprezzi not sure if you also want to change this so its consistent
<img width="272" alt="screen shot 2017-03-12 at 3 50 13 pm" src="https://cloud.githubusercontent.com/assets/16444438/23835804/9e3c8e48-073b-11e7-9d3d-2e887560c7fc.png">

**Comment by DarklyLabs** [comment]
Can anyone explain why the G0 Feedrate is needed here and how its used?
Does it override the default value?
Is it used in GCode generation?

**Comment by cprezzi** [comment]
@cojarbi Where is that field from?

**Comment by DarklyLabs** [comment]
@cprezzi I think it's the one under the simulator slider

**Comment by cojarbi** [comment]
Sorry main screen, bellow the canvas

**Comment by cprezzi** [comment]
Ah ok. I did not program that. Think thats for the CAM.

**Comment by DarklyLabs** [comment]
@tbfleming Can you shed any light on the reason and function of this slider?

**Comment by tbfleming** [comment]
Everything in this area affects the workspace, and nothing else:

![image](https://cloud.githubusercontent.com/assets/418464/23837663/13e66e04-0762-11e7-92f7-4635ce72e844.png)

The G0 Feedrate field is for time estimation that the Simulator slider uses.

**Comment by DarklyLabs** [comment]
@tbfleming Where is this estimation found?

This naming is ambiguous and easily confused by users as to what it relates to. I can see it useful if you could playback the simulator, but i don't this this is possible?
Either way, a more appropriate name should be used.

**Comment by tbfleming** [comment]
The slider position is proportional to simulation time. Far left is time 0 and far right is estimated end time.

The naming is exactly what it says: G0 Feedrate tells the simulator what feed rate G0 is. The simulator doesn't know since it doesn't talk to the firmware.

You can playback the simulator; just move the slider. After you click on it you can also hold down the left or right arrow keys.

**Comment by DarklyLabs** [comment]
By calling it G0 Feedrate causes it to be confused with actual G0 feed-rates. As I said, it is ambiguous.

Can I suggest calling it something more appropriate to the simulator?
'Simulator Speed"
"Simulator Estimation Speed"
"Simulation G0"

**Comment by tbfleming** [comment]
It's now "Sim G0 Feed".

**Comment by DarklyLabs** [comment]
Thx Todd.
