### ISSUE TITLE
Add drag and drop files into the app

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#202]
Drag and drop files from the explorer / finder into the app as an additional way of loading.
We have this in LW3. Can it be added here?

**Comment by openhardwarecoza** [comment]
I think that may confuse users (drag from windows into document tree, then drag from document tree to operations.... Users are going to confuse the two and draf from window to operation i bet.

**Comment by cojarbi** [comment]
You might be correct, enough issues we have now but this could be solved by just illuminating the section you are suppose to drag the file to. If it's from outside just illuminate the import section and if it's from LW just illuminate the operations ? 

If to complicated then focus on something more important. I just want to have UI common to now days standards. Most use drag and drop
