### ISSUE TITLE
installdev broken

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#204]
Development environment is broken because of some missing libraries in package.json!

![grafik](https://cloud.githubusercontent.com/assets/5457949/23805609/e3140a74-05be-11e7-9fa3-7f39b5e5956c.png)

**Comment by cprezzi** [comment]
@jorgerobles Could you check please.

**Comment by jorgerobles** [comment]
@cprezzi Weird, cannot reproduce the error. Will try a dry run

**Comment by iceblu3710** [comment]
I have had problems with the `npm run-script installdev` option downloading to the node_modules and then when the script ends they are not resolvable. running `npm install` works every time.

Only happened a few times on Linux for me, I used nvm to install the latest and everything works fine now.

**Comment by jorgerobles** [comment]
@cprezzi still errors?

**Comment by tbfleming** [comment]
> I have had problems with the npm run-script installdev option downloading to the node_modules and then when the script ends they are not resolvable. running npm install works every time.

Very odd since installdev runs npm install.

I just wiped node_modules and did a fresh installdev; everything seems to be OK (Windows 10, Node 4.6.0, npm 2.15.9).

**Comment by iceblu3710** [comment]
I wiped and re-setup my repo this morning and it worked for me on Linux_x64.
Node v6.9.2
npm v3.10.9

I had my problems back in Feb where installdev said it worked but on npm run it would give package errors. Everything worked well since then.

**Comment by cprezzi** [comment]
@jorgerobles The same update (installdev) worked on my notebook, so probably a version conflict on my PC. Will try reinstall.

**Comment by jorgerobles** [comment]
:)
