### ISSUE TITLE
Add G0 and G1 Filters to View

### ISSUE THREAD

**Issue by megashub** [LaserWeb/LaserWeb4#207]
I would like to be able to review G0 and G1 paths separately. Right now, they are presented together, so I can't always see exactly where the G0 paths are because they often times blend into the G1s.

**Comment by jorgerobles** [comment]
It's done at Webgl level, not to be implemented soon, sorry :|

**Comment by openhardwarecoza** [comment]
Are we sure we need this? There are many legit cases where g0 moves may run over g1? I dont see the use of a filter.

**Comment by jorgerobles** [comment]
Hmm. the only thing I'm thinking is that the G0 rendering should be moved on top of G1, maybe will suffice? @tbfleming

**Comment by tbfleming** [comment]
I'd be tempted to do the opposite: G1 on top of G0.

**Comment by megashub** [comment]
Sounds like we're getting into personal preference territory. Perhaps a settings toggle to allow for either one?


--------------------------------------------
On Tue, 3/21/17, Todd Fleming <notifications@github.com> wrote:

 Subject: Re: [LaserWeb/LaserWeb4] Add G0 and G1 Filters to View (#207)
 To: "LaserWeb/LaserWeb4" <LaserWeb4@noreply.github.com>
 Cc: "megashub" <megashub@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, March 21, 2017, 1:28 PM
 
 I'd be tempted to do the
 opposite: G1 on top of G0.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by tbfleming** [comment]
No, that contributes to a flood of settings that most people don't care about. Mozilla fell to that flood and Firefox stripped options out when it rose from the ashes.

**Comment by cprezzi** [comment]
@tbfleming @jorgerobles What if you make all G moves only 70% opaque? This way, colors would mix when one move is over the other.

**Comment by tbfleming** [comment]
That might work. It will need testing since that could hurt visibility on hi-res displays.

**Comment by jorgerobles** [comment]
@megashub in order to go further with this issue, we need a workspace.json to replicate it.
I've used 70% locally but cannot tell If it's enough or not.

**Comment by megashub** [comment]
I have only just begun to play around with LW4, so I haven't made many changes other than the very basics to get it working with my K40. Still, if it's valuable, I'll upload my copy of it. I'm also more than happy to just pull down a test build and give it a whirl. Whatever's most helpful to you and the team.

--------------------------------------------
On Wed, 3/22/17, jorgerobles <notifications@github.com> wrote:

 Subject: Re: [LaserWeb/LaserWeb4] Add G0 and G1 Filters to View (#207)
 To: "LaserWeb/LaserWeb4" <LaserWeb4@noreply.github.com>
 Cc: "megashub" <megashub@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Wednesday, March 22, 2017, 1:34 PM
 
 @megashub in order to
 go further with this issue, we need a workspace.json to
 replicate it.
 
 I've used 70% locally but cannot tell If it's enough
 or not.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jorgerobles** [comment]
@megashub, I'm not sure what you mean, but workspace is just a .json file, you can save it from the cam pane top, workpace, save. 

Please just open the file you used to detect the issue, put some operations and generate gcode. Then download the workspace.json, rename as .txt adnd upload here,

Thanks!

**Comment by openhardwarecoza** [comment]
Closing for now - for most of the users the green/red suffices
