### ISSUE TITLE
Small cut path will not generate accurate gcode

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#210]
@tbfleming  
If the path is to small then the laser cut operation output gcode will not accurate.
It misses or does not follow the path correctly

<img width="1676" alt="screen shot 2017-03-12 at 4 07 58 pm" src="https://cloud.githubusercontent.com/assets/16444438/23836184/63b2e202-0742-11e7-8951-4fb1c9b1bc5a.png">

**Comment by tbfleming** [comment]
The 3 Laser Cut operations now have a Segment field. It defaults to 0mm. Its old non-configurable value was 0.5mm.

Old behavior: Smoothieware was OK with 0.5mm at high feeds. This was too course for some jobs such as this.

New behavior: By default it will reproduce fine detail, but Smoothieware will now choke on some jobs that it could handle before. When this happens, bump up the Segment value. This will cause it to lose detail.

**Comment by cojarbi** [comment]
Work beautifully, now i need to add this to the documentation.
I know i had to use the segment on my mill because my gshield was choked on very small segments also.
