### ISSUE TITLE
Machine Profiles bug

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#212]
After the latest work on profiles, I get this

![lw error](https://cloud.githubusercontent.com/assets/7695323/23858162/3a39fc64-0808-11e7-9b14-d7acdf33ab8e.PNG)

Tried clean re-clone of LW4
Tried installdev couple times
Same happens on Linux and Windows (First picked it up as a error of linux electron build coming up with white screen, but the test below is simply 'node http-server' serving LaserWeb4/dist after a npm run bundle-dev (ruling out electron)

**Comment by jorgerobles** [comment]
O_o

**Comment by jorgerobles** [comment]
@openhardwarecoza Done :)

**Comment by openhardwarecoza** [comment]
(: thank you!
