### ISSUE TITLE
Load gcode button unreliable

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#213]
Sometimes it works and other times it fails to dispatch the GCODE_SET action.

[grayscaletest.gcode.txt](https://github.com/LaserWeb/LaserWeb4/files/838876/grayscaletest.gcode.txt)

**Comment by jorgerobles** [comment]
I've tested 20 times, failed 3, but no error is thrown :slightly_frowning_face:

**Comment by tbfleming** [comment]
It's a heisenbug :(

**Comment by jorgerobles** [comment]
I've applied this workaround but fails equally http://stackoverflow.com/questions/12030686/html-input-file-selection-event-not-firing-upon-selecting-the-same-file

**Comment by jorgerobles** [comment]
Well, after new tests, fix does not work (former commit is wrong, that code is not used). It's a native event bug. Sooo, I will close, sorry.

**Comment by tbfleming** [comment]
Created a new label for cases like this.

**Comment by tbfleming** [comment]
I think we should keep this open so we can point people to it. Also so we'll remember to recheck at the next Chrome release.

**Comment by jorgerobles** [comment]
Right, thanks!

**Comment by tbfleming** [comment]
The two oldest open bugs in jscut have tags "Safari Bug" and "IE Bug" :)

**Comment by donkjr** [comment]
FYI: I noticed a condition under which I can reproduce this error. 
The first time you use "Generate" after loading an image into operations with the "Generate" button in the yellow state and nothing in operations.
The next time you "Generate" it will work correctly and from then on ....

**Comment by jorgerobles** [comment]
Will try, I'm not sure. I had randomly misfires (~20%) just trying to load the same file twenty times a row.

**Comment by jorgerobles** [comment]
@tbfleming Found. Virtual file inputs are the culprits. Searching a workaround
