### ISSUE TITLE
Hiding irrelevant operations / tabs

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#214]
**Example 1:**
Use drags only RASTER / IMAGE into operations:

Current Behaviour:  User can select Laser Cut and CNC operations (If not educated, it seems perfectly logical) - but gets NO gcode (since you cant CUT a Raster...)  

Expected Behaviour: Only show operations relevant to IMAGE types.  

**Example 2:** 
User drags vectors into operation

Current Behavior: User selects Laser Raster because we earlier told him thats the one that "colors in" an image

Expected Behaviour:  Hide Raster operations

**Example 3:**
User drags Vectors and Bitmaps into operation

Current behavior:  LW allows user to do that, but only one of the types will succeed for any operation. The other will fail. 

Expected Behavior: Disallow or warn user?  Maybe ask user "Cannot be done this way, can I split it into two operations?" and then split it for the user?

**Example 4:**  (Related to #199's plans also) 
User runs a Laser only

Current Behavior:  Shows CNC jobs too

Expected Behavior:  Like we had in LW3:  In Settings: Machine - specify if its a laser, 3d printer or CNC:   If Laser is selected, only Laser type CAM operations are shown.  If CNC, then only CNC operations are shown.  If 3D Printing, we should hide the CAM tab, and add a new tab, 3D Printing that only gets shown in 3DP mode.

**Comment by jorgerobles** [comment]
Got it working, but do we traverse all the documents children (snail slow), not?

**Comment by openhardwarecoza** [comment]
Not sure (:

I dont know how deep down users will place such craziness.  Just file on its own is probably definite.   But sometimes images can be embedded in an SVG.   How deep?  Inside a group, inside a layer? I dunno (; I'm a dxf guy

**Comment by jorgerobles** [comment]
Yes, SVG can embed images :)

**Comment by openhardwarecoza** [comment]
So, i take it that means traverse all children? 
Or at least "all children in what was just dropped"

**Comment by tbfleming** [comment]
Example 3:
* User drags an entire SVG file into operations. Selects Laser Raster.
* User drags an entire SVG file into operations again. Selects Laser Cut.
Current behavior: operations filter what they support. Why give an error or warn?

**Comment by openhardwarecoza** [comment]
@tbfleming true, that can happen too...  Thats why i suggested asking user if you can split it on the first drag maybe?  (trailing G_+ and feedback from the 500+-newbie LW4 users (According to google analytics) most dont understand it.  So, either that, or a documentation fix

**Comment by tbfleming** [comment]
I suspect restricting the set of operations based on what's present in the selection may be enough. If there's an image somewhere in the selection, allow raster. If there's a vector somewhere in the selection, allow vector ops.

**Comment by openhardwarecoza** [comment]
Agreed... If both are present, presenting all options is the logical answer

**Comment by jorgerobles** [comment]
Ok, then traverse children for images. I'm still worried for large files performance.

**Comment by openhardwarecoza** [comment]
Ah Performance, that incompatible thing with "user ability"

**Comment by openhardwarecoza** [comment]
It amazes me the little things we now bitch about when you compare what we have with what we had before you awesome people joined the project....

**Comment by openhardwarecoza** [comment]
When I was working on the CAM tree concept in https://github.com/LaserWeb/LaserWeb3/issues/52 - arthur wolf commented about how I should keep the UI simple...   I made a joke about "note to self, laserweb4" and then a mass of buttons confusing Homer...   I wonder if we did achieve that goal (; 

![lots of buttons](https://cloud.githubusercontent.com/assets/7695323/23914636/39c72e18-08ef-11e7-800b-dd6a68477744.PNG)

**Comment by jorgerobles** [comment]
Last thing. What do you prefer, hide operation types or make them unselectable?

**Comment by cojarbi** [comment]
Indeed this will solve many many support questions

**Comment by jorgerobles** [comment]
Tada!

**Comment by cojarbi** [comment]
Wonderfull @jorgerobles

**Comment by openhardwarecoza** [comment]
@jorgerobles ! Man that was too fast!

**Comment by cprezzi** [comment]
Am I the only one who could only do "laser cut" operation now? When I drag a raster image, the operatino is showing "Laser Raser" but all params are from "Laser cut", so I can't define all params and no gcode is generated.

**Comment by jorgerobles** [comment]
Checking...

**Comment by cprezzi** [comment]
All vector operations are working, just raster is not. I think you need to fire the dropdown change event after activate/inactivate dropdown items.

**Comment by jorgerobles** [comment]
Yes.. that is. Will be easy.

**Comment by jorgerobles** [comment]
@cprezzi Done.

**Comment by cprezzi** [comment]
Jep, works just fine :)
