### ISSUE TITLE
Image file structured under a layer from Inkscape

### ISSUE THREAD

**Issue by donkjr** [LaserWeb/LaserWeb4#218]
In Inkscape I created a layer for images and put a bit mapped logo on that layer. Nothing else.
Then I brought it into LW4:
If I select and assign the entire layer to an operation it works fine.
However;
If I select the image only from within that layer and "create single", it will let me define it as that operation but it will not generate the gcode or simulate.

Also: if you define in 'create single"  an image as a "Laser Cut" operation
 it does not prevent the selection but does not generate g-code or allow simulation. 

![lw4_image_in_layer](https://cloud.githubusercontent.com/assets/2752900/23973766/433dc980-099d-11e7-88cf-f24cbabe1f90.gif)

**Comment by openhardwarecoza** [comment]
Gh-pages isn't as up to date as dev-es6 - the screenshot cut off the address bar, cant see where you are running from? Try a Binary from github.com/LaserWeb/LaserWeb4-Binaries

**Comment by jorgerobles** [comment]
@donkjr, the specs of document selection (at #214 ) are these (should add to docs)

1. Must have selected a document to create single/multiple **(just fixed it)**
2. If an operation has only vector documents (traversing each document children), then the raster operations are disabled.
3. If an operation has only raster documents (traversing each document children), then vector operations are disabled.
4. if an operation has mixed documents (several distinct document natures, or a single document whose tree has mixed natures) all the operations are allowed

PS 4,LW has no way to apply different operations to a single tree, so if Laser Cut is selected on a mixed operation that has images, images will not be processed. Either way, if Laser raster is selected on a mixed operation that has vectors, vectors will be ignored.

**Comment by jorgerobles** [comment]
@donkjr I've excluded layers (SVG::G) from vector count, so now if dropping a layer that only contains raster, only raster should be allowed.

**Comment by tbfleming** [comment]
@jorgerobles instead of looking at the type field, which will gain new values over time, it's easier to look if rawPaths (vector content) or dataURL (image content) aren't empty.

**Comment by jorgerobles** [comment]
Neat! Will change :)

**Comment by jorgerobles** [comment]
@donkjr please check to close, thanks :)

**Comment by jorgerobles** [comment]
closing...

**Comment by donkjr** [comment]
Sorry I was late the the response.
It looks like the issue is indeed improved as I tried the top of the image tree and the image itself and it worked correctly.

THANK YOU!
