### ISSUE TITLE
LW4 Electron exposes old LW3 test interface

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#225]
When startting the electron exe, you could open the testenvironment (LW3) in a separate browser on localhost:8000. This can confuse users.

This environment was used for testing during development of lw.comm-server. It's planned to convert it to a slim LW4 remote (for mobiles & tablets).

**Comment by openhardwarecoza** [comment]
That comes from your /app in lw.comms-server - can we remove it from there?
Once gone I can change the path of the lw4 copy from /app/lw4 to /app

(/app is a hardcoded requirement of electron-builder, coincidence to your
selected path for the testing)

**Comment by cprezzi** [comment]
We should move the testapp (which will be converted into mobile remote app) in a subfolder like /app/mobile and have LW4 it the /app folder.

**Comment by openhardwarecoza** [comment]
That'd work too (:

I am already at work, would you have a moment to fix that in
lw.comms-server repo? (i'll merge back down to electron_bundler branch)

**Comment by cprezzi** [comment]
@openhardwarecoza I've swaped the webpages in the **electron branch** (moved testpage to /app/mobile and /app/lw4 to /app & changed package.json and server.js accordingly). I was able to test the electron build for Win x64. Not tested for the rest. :)

**Comment by cprezzi** [comment]
Version is now 4.0.45

**Comment by openhardwarecoza** [comment]
Cool! Will run a set tonight (:

**Comment by openhardwarecoza** [comment]
New binaries are out
