### ISSUE TITLE
Disable operation

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#229]
Being able to disable operations without having to delete them is needed.

This often happens as users are fine tuning their job. Being able to focus on a specific operation would be a great time saver.

**Comment by openhardwarecoza** [comment]
Agreed, I also sometimes have a need for this feature

**Comment by jorgerobles** [comment]
It's done :) check your build :D

**Comment by openhardwarecoza** [comment]
Yikes! Too fast!

**Comment by openhardwarecoza** [comment]
Oh wait,  no. not fast. Just me didnt read on Git, only checked the mail and replied from there

**Comment by jorgerobles** [comment]
@DarklyLabs please check to close, thanks :)

**Comment by DarklyLabs** [comment]
Looks like working well. Thank you.
