### ISSUE TITLE
Ability to move gcode in workspace

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#230]
Many users run repetitive jobs by loading in a gcode file. It's faster and more failsafe once they have a project that is working perfectly for them.

Having the ability to reposition gcode in the workspace in a natural extension of allowing users to work with gcode files directly.

**Comment by jorgerobles** [comment]
That will require a huge preprocessor depending the generated gcode (Gcode is rather verbose). Reprap software (as far as I know) does not do that either.

**Comment by jorgerobles** [comment]
@cprezzi had some G+ answers about a similar topic.

**Comment by DarklyLabs** [comment]
@jorgerobles Where are these answers?

**Comment by jorgerobles** [comment]
Sorry https://plus.google.com/113059362277072411228/posts/KDTmzSbbrMi. Basically It will throw LW on its knees if file is large.

**Comment by DarklyLabs** [comment]
@jorgerobles  If too difficult to implement then we understand.
In effect, we are not suggesting editing the gcode, but rather transforming it. I suspect you will tell me this constitutes the same thing!

**Comment by jorgerobles** [comment]
Yes, it is 🙁  .The problem is handling the amount of data. Currently load once and then is cached. Transforms do that every frame during movement.

**Comment by openhardwarecoza** [comment]
Teach user to export workspace instead of gcode?

**Comment by DarklyLabs** [comment]
Understood.
Thanks for the consideration.
Closing now.

**Comment by tbfleming** [comment]
Update: there's now a partial solution to this using the new MPos/WPos system with Set Zero.
