### ISSUE TITLE
UI Enhancement: Unreadable Inputs

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#231]
![jog speeds](https://cloud.githubusercontent.com/assets/7695323/24200913/3c046d70-0f17-11e7-8be2-0e83bd7d8431.PNG)

**Comment by tbfleming** [comment]
I love that tag!

**Comment by cprezzi** [comment]
The same problem exists in the cam tab.
Could we just make the default width of the sidebar a bit wider?

**Comment by tbfleming** [comment]
I think the cam tab's issues are related to side-by-side fields and other new things that were added since I designed the original CSS.

**Comment by cprezzi** [comment]
@tbfleming For example: It happens that the red cross for deleting an operation is out of view with default width.

**Comment by jorgerobles** [comment]
Easy solution, store splitter position on localtorage ;)

**Comment by tbfleming** [comment]
I think the red cross started its disappearing act around the same time the "hide" link was added. The link forcibly widened the inner column, causing everything inside to readjust to match, flowing past the the outer column's width.

**Comment by tbfleming** [comment]
> Easy solution, store splitter position on localtorage

That will help. Long term I need to go back and rework the CSS to support the added controls better.

**Comment by jorgerobles** [comment]
@tbfleming Yes, will have to think deep around UI and UX. Bootstrap has some limitations also.
@openhardwarecoza does splitter remembering help with that inputs?

**Comment by openhardwarecoza** [comment]
I'll try and work on the CSS for the Jog tab today first (:

**Comment by openhardwarecoza** [comment]
![lw4 jog tab](https://cloud.githubusercontent.com/assets/7695323/24824012/2b69e986-1c05-11e7-9af3-2759d8753011.PNG)

Fixed the major issues - Not done yet - but will continue in the morning.  2:45 AM this side and brain is freezing

**Comment by cprezzi** [comment]
Love that colors :)

**Comment by openhardwarecoza** [comment]
Also from the testing group - those not familiar with cartesian system, the colors help give some visual clue of associating viewer with buttons, and now also DRO

![dro](https://cloud.githubusercontent.com/assets/7695323/24828686/c4fe025a-1c62-11e7-9a90-e2a77fceefec.PNG)

**Comment by jorgerobles** [comment]
Niice!
