### ISSUE TITLE
Redundant workspace save dialog box

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#233]
Saving the cam workspace first opens up a filename dialog box, then after hitting 'ok' the file dialogue window opens.

The first filename window is redundant as the following dialog window allows the filename to be set.

**Comment by tbfleming** [comment]
At one point we decided against this double dialog: https://github.com/LaserWeb/LaserWeb4/issues/93#issuecomment-268041970 . I don't remember when this was reversed.

**Comment by jorgerobles** [comment]
@DarklyLabs, @tbfleming 
That's ok. I forgot #93. Anyway, I found that other pieces of code used prompt.
Not a problem, can be stripped. Following #93, most browser users does not choose to save as as the preference and goes al thru, getting "gcode 20.gcode" some days.

Last decision, should we strip all saving prompts on Electron builds, Browser or both?

**Comment by DarklyLabs** [comment]
Having the 'file browser' come up for a save or load operation in all versions would be ideal, would it not?

**Comment by jorgerobles** [comment]
Native file browser is not available to javascript on regular browser. Is a private chrome setting: :|

**Comment by tbfleming** [comment]
We could point people to that setting when they complain about numbered files.

**Comment by jorgerobles** [comment]
Prompt is disabled by default. Prompt Prone People should do click-shift on save

**Comment by tbfleming** [comment]
Prompt Prone People Prefer Prescribed Preparations while Pondering Place
