### ISSUE TITLE
Cannot open raster file

### ISSUE THREAD

**Issue by lautr3k** [LaserWeb/LaserWeb4#235]
- With a blank workspace.
- Add an image as document.

Console message:
```
error: TypeError: Cannot read property 'naturalWidth' of undefined
    at processImage (document.js:151)
    at loadImage (document.js:196)
    at Object.reducer [as default] (index.js:72)
    at dispatch (createStore.js:179)
    at persistStateMiddleware.js:26
    at action (index.js:30)
    at index.js:103
    at promisedImage.then.img (cam.js:223)
```

**Comment by jorgerobles** [comment]
@lautr3k  I'm away right now, bug is on https://github.com/LaserWeb/LaserWeb4/blob/f9135d9cece04cedee2bc943e5b1882406c21f99/src/reducers/document.js#L149

Substitute {file,context} to context, plz

**Comment by openhardwarecoza** [comment]
I am also pretty much offline till the 4th of april. @lautr3k you have push
access (: would you mind fixing?
