### ISSUE TITLE
SVG Image displacement.

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#236]
Images are displaced upon loading. Also thrown a https://sourceforge.net/p/jsclipper/tickets/18/ error
Design Software: AI
Workspace Bundle[container-02.zip](https://github.com/LaserWeb/LaserWeb4/files/870224/container-02.zip)
Inkscape file, same behavior [container-02-INK.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/870230/container-02-INK.svg.txt)

---

I've also experienced a weird G0 movement slowdown, but cannot reproduce on further tests. Was during a raster, after moving from one raster to another, Smoothie went F100. Gcode revealed no problem.

**Comment by jorgerobles** [comment]
@tbfleming, @lautr3k

**Comment by tbfleming** [comment]
Three bugs in one test case!
1. jsClipper exception: this one causes it to abandon triangulation (fill support). It falls back to displaying outline only.
2. The viewBox units bug (#223)
3. Offsetting: looks like it may be https://github.com/lautr3k/lw.svg-parser/issues/7

**Comment by tbfleming** [comment]
I just fixed lautr3k/lw.svg-parser#7 . Try this now.

**Comment by jorgerobles** [comment]
Partial success!

**Before**
![image](https://cloud.githubusercontent.com/assets/1706080/24849965/6c809814-1dce-11e7-9bce-2c80a896acb4.png)

**After Inkscape**
![image](https://cloud.githubusercontent.com/assets/1706080/24849935/4b616488-1dce-11e7-8cca-5201773de250.png)

**After AI**
![image](https://cloud.githubusercontent.com/assets/1706080/24850195/68c03fd0-1dcf-11e7-8280-c5781cb9f257.png)

Images are gone on render (Js log throws some Infinity problem on Floating Window. )

Attached svg
[container-02.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/909276/container-02.svg.zip)

**Comment by jorgerobles** [comment]
@tbfleming images went with width and height null. Any fixups?

**Comment by jorgerobles** [comment]
@tbfleming found some infinitys out there (those expensive cars)
![image](https://cloud.githubusercontent.com/assets/1706080/24922796/c6d0d7d0-1eef-11e7-9981-074e7c315d41.png)

**Comment by jorgerobles** [comment]
I think the problem is instancing the image on addChildren. width is not met always. I used a promise on the image document load, but I think cannot use it here :/

**Comment by tbfleming** [comment]
Don't set i.width and i.height; it defeats getting the image's native width and height. They're not null when I run it; is this another OSXism?

**Comment by jorgerobles** [comment]
Can I use rawW and rawH? I found that transforms behaves wrong with globalMatrix. I've switched to localMatrix and works like a charm

**Comment by jorgerobles** [comment]
Cannot find the use of `let i = new Image;` anyway I think is not needed even.

**Comment by jorgerobles** [comment]
I've done some tests and the patch introduced works reasonably well :)

![image](https://cloud.githubusercontent.com/assets/1706080/24931528/e73c6b10-1f0d-11e7-8202-038572cb6ab3.png)

**Comment by tbfleming** [comment]
[stars.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/914715/stars.svg.txt)

Inkscape:
![image](https://cloud.githubusercontent.com/assets/418464/24931846/d9148c7e-1edc-11e7-86ba-d215d8af9946.png)

old version: 93159b2:

![image](https://cloud.githubusercontent.com/assets/418464/24931892/1039e08c-1edd-11e7-8d75-47cf0f499297.png)

new version: 7744f9a:
![image](https://cloud.githubusercontent.com/assets/418464/24931938/49cd4276-1edd-11e7-8d52-786595803372.png)

**Comment by jorgerobles** [comment]
@tbfleming then we have an AI vs Inkscape war :)

Is not that bad. Seems something to do with the image proportions, but anchoring is ok. Will try on other machine to replicate the issue if has to be related with the Infinity issue.

**Comment by tbfleming** [comment]
If it's Inkscape vs AI, then Inkscape should win since it's open source. It might not be that. Try constructing a simple test case in AI that mixes a small number of paths and stretched bitmaps. No groups or layers. The test needs to make it easy to see if alignment and stretch are handled correctly.

**Comment by FabCreator** [comment]
AI is important to support, while its not open source it is one of the main programs used for designing. it would be a shame for laserweb to not support mainstream apps :(

**Comment by tbfleming** [comment]
I doubt it would be one vs the other. Let's start with a simple case to see.

**Comment by jorgerobles** [comment]
@tbfleming I think is not the case (aforementioned war)
Yesterday I made all the tests with this file, coincidentally the specs you say.

[image.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/915812/image.svg.txt)

**Comment by jorgerobles** [comment]
I'm more leaned towards image instancing does not have instant measurements, as have done earlier with other code to get naturalWidth, etc I used image onload promise.

**Comment by tbfleming** [comment]
Dang. Not good.

old:
![image](https://cloud.githubusercontent.com/assets/418464/24948081/26434580-1f37-11e7-9956-aa1cd0774ec1.png)

new:
![image](https://cloud.githubusercontent.com/assets/418464/24948087/2eb1ea6e-1f37-11e7-84ad-2306ca8f5c4c.png)

Which means: old code preserves Inkscape alignment and new code preserves AI alignment.

**Comment by FabCreator** [comment]
could we have an option to enable inskape or ai?

**Comment by jorgerobles** [comment]
> Don't set i.width and i.height; it defeats getting the image's native width and height. They're not null when I run it; is this another OSXism?

@tbfleming checked on linux also... linuxism :smile:

**Comment by cprezzi** [comment]
Is there any way we can detect from the file, if it was made by Inkscape or AI?

**Comment by jorgerobles** [comment]
Gonna fiddle a bit, maybe is not necessary, anyway both software use some
identificative tags, easy to detect

**Comment by jorgerobles** [comment]
@tbfleming found! as I've suspected naturalWidth and naturalHeight are not available on instant of decoding image in a predictable way. Sometimes is, sometimes not. Hence, scale is wrong as should be calculated with `rawW/i.naturalWidth` for example

I was looking the place to use the promise to get those values loaded, but cannot find a suitable one. I suppose the best place should be the parser instead the reducer. Can you help me to find it?

**Comment by jorgerobles** [comment]
A possible solution is to install https://github.com/gaearon/redux-thunk that allows promised actions, so documentsLoad will be a promise and dispatch upon processing.

**Comment by tbfleming** [comment]
@jorgerobles there's callback and promise code in the cam component's file loading. You can add more async stuff there.

**Comment by jorgerobles** [comment]
Yes I know :), then move documentsLoad code from reducer to cam and then use documentLoad as a simple state merge?

**Comment by tbfleming** [comment]
That will work. Another option is for the async code to use the images to set our own attributes on Tag. The reducer would read the new Tag attributes instead of loading the images.

**Comment by jorgerobles** [comment]
@tbfleming Fixed!! :tada::tada::tada::tada::tada:

**Comment by cojarbi** [comment]
So now I plain English what's was fixed? :)

**Comment by FabCreator** [comment]
somthing to do with SVGs not loading in the right place and it being different for inkscape and ai

**Comment by cojarbi** [comment]
I this fix is something we need to communicate to the users , if so what should be described

**Comment by jorgerobles** [comment]
So...
New version fixes embedded images bug on svg, and better support to design
software files ;)

El 13 abr. 2017 23:01, "Ariel Yahni" <notifications@github.com> escribió:

I this fix is something we need to communicate to the users , if so what
should be described

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/236#issuecomment-294020486>,
or mute the thread

**Comment by tbfleming** [comment]
There are multiple fixes in this and related issues:
* Some paths got messed up: https://github.com/lautr3k/lw.svg-parser/issues/7
* SVG files that were anything other than 90 px per inch got messed up, even when the user set the px per inch setting correctly
* Embedded images sometimes got mispositioned or missized

**Comment by tbfleming** [comment]
Corel: chances are Corel is still problematic. From the files I've seen in the wild, it looks like Corel randomly generates a different px-per-inch scale for each individual file. We can't handle that until we add px-per-inch auto detection.
