### ISSUE TITLE
SVG solid fill of almost all paths, save for one

### ISSUE THREAD

**Issue by PeterGrace** [LaserWeb/LaserWeb4#237]
[LogoWorkspaceIssue.json.txt](https://github.com/LaserWeb/LaserWeb4/files/870917/LogoWorkspaceIssue.json.txt)
[GeneralPinewoodDerby.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/870921/GeneralPinewoodDerby.svg.txt)

I'm trying to create a laser fill path for the attached svg file.  When I open this workspace in 0.4.0-alpha (BE 4.0.45) the image imports the way I want it to, all except for the R in "DERBY" -- For some reason, LaserWeb is not filling it.  Is this because the path is not closed?  It looks closed in inkscape and qcad, but LaserWeb seems to be annoyed with it.

Can someone shed some light on why this is happening and how I can fix it?

**Comment by tbfleming** [comment]
This is a limitation of the triangulation code. It only impacts the display, not the CAM functions.
