### ISSUE TITLE
Material Database changes not saved after restart of the app

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#239]
Open material database, make some changes or delete the original, close LW, reopen it will show the default sample.

**Comment by jorgerobles** [comment]
Sorry @cojarbi we have connected/disconnected that storage back and forth upon modifications :smile:
If there's a sample operations/materials you want to contribute as bundled, there's a shiny new repository for that on https://github.com/LaserWeb/lw.materials, or send me to attach.

**Comment by jorgerobles** [comment]
@DarklyLabs, @FabCreator if you have any operations specific to your machine, we can add :)
