### ISSUE TITLE
Add keyboard jog support

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#240]
Could it be possible to add keyboard jog support?

**Comment by cprezzi** [comment]
Should be possible, it's just a bit complicated to find keys that make sense and are free on all plattforms ;)

**Comment by jorgerobles** [comment]
Highjacking thread ---I want live feedback also! That is, clicking on the workspace and live feedback enabled, the head moves to the clicked point :smile:, Is useful to aim the laser to an scrap material
@tbfleming is there a way to achieve that?

**Comment by cojarbi** [comment]
Highjaker !!! I think chillippepr has this implemented , not sure if it works for us

**Comment by jorgerobles** [comment]
I've tried, but got lost on CastingXRays or something mutant

**Comment by tbfleming** [comment]
@jorgerobles yes, but all 3 mouse buttons are currently used. WorkspaceContent.xyInterceptFromPoint converts (e.pageX, e.pageY) to machine X, Y.

**Comment by jorgerobles** [comment]
Then using shift+click?

**Comment by tbfleming** [comment]
shift+click is safe as long as the mouse isn't over a document.

**Comment by tbfleming** [comment]
![image](https://cloud.githubusercontent.com/assets/418464/24620280/0843e260-186b-11e7-9688-ecf85b53d476.png)

**Comment by jorgerobles** [comment]
Ok, will find some other key combo ;)

**Comment by tbfleming** [comment]
shift+ctrl+click and alt-click are safe. If you're really ambitious you could chord the letter keys (e.g. Q+W+shift), although that might not work on OSX and windows users only expect that type of chording on video games :)

**Comment by jorgerobles** [comment]
LOL. there's a package already installed that I think it does. :D

**Comment by cojarbi** [comment]
A+S+D+F is more comfortable if we want to use all fingers

**Comment by jorgerobles** [comment]
Asdf or asdw?

**Comment by cojarbi** [comment]
Asdw would give me the finger lol

**Comment by tbfleming** [comment]
My hand rests easily on Q+W+E+R+C. It kind of reminds me of a Tetris piece.

**Comment by cojarbi** [comment]
Real question: isadding a key  a safety feature or a technical one? UGS for example does not add a key but you need to check the option On first

**Comment by tbfleming** [comment]
I just realized I'm mixing up the two issues. @jorgerobles hijacked my mind when he hijacked the thread :)

**Comment by jorgerobles** [comment]
Sorry, highjacking. But even are different topics It sparked because are
related. I bet @cojarbi was trying to move the jog to a material, isn't it?

El 3 abr. 2017 7:16 p. m., "Todd Fleming" <notifications@github.com>
escribió:

I just realized I'm mixing up the two issues. @jorgerobles
<https://github.com/jorgerobles> hijacked my mind when he hijacked the
thread :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/240#issuecomment-291210315>,
or mute the thread

**Comment by cojarbi** [comment]
Look what you did @jorgerobles :). Now what's what?

**Comment by tbfleming** [comment]
Keyboard jog support:
* gamers who place their mouse on the right side are used to WASD for motion control (mouse aims gun)
* gamers who place their mouse on the left side (me) are used to arrow keys for motion control
* If we support both, then we'll end up supporting all machines, even the ones with crippled keyboards

Click to jog:
* I'm OK with shift+ctrl+click or alt+click (or one of the bizarre keys+click on OSX)

**Comment by jorgerobles** [comment]
Click to jog: I will go for alt-click. Other keys are used already for modifying selection.
Keyboard jog: I would go for Arrows (Even Alt+Arrows to be uniform). Are meant for that :smile:, supporting other keys (wasd etc) could conflict with macros and so on.

**Comment by jorgerobles** [comment]
Should jogging with click or keys, be restricted on Jog Tab?

**Comment by tbfleming** [comment]
So far the current tab doesn't affect what users can do in the workspace. Is there a strong reason to limit it to the Jog tab?

**Comment by jorgerobles** [comment]
Well I prefer not to move my machine if I mistake alt key. I know is a corner case, so just asking.

**Comment by cojarbi** [comment]
Is a click or a key required for motion control with the arrows , I would love to use my other hand for something esle

**Comment by cojarbi** [comment]
I assume jog will not work if machine is executing a job

**Comment by jorgerobles** [comment]
@cojarbi good point. We have no safe checks so far.

I think Alt key is required at least for click, and maybe on keyboard too. You know, cursor keys are used on writing on fields.

**Comment by tbfleming** [comment]
I forgot about the fields.

**Comment by jorgerobles** [comment]
Also, Jog click should check if a homing is done before, or we have many wrongly angry users

**Comment by tbfleming** [comment]
Forget keyboard, mouse, and touchscreen. We need this: http://www.economist.com/news/science-and-technology/21719774-do-human-beings-need-embrace-brain-implants-stay-relevant-elon-musk-enters

**Comment by jorgerobles** [comment]
LOOOL :rofl:

**Comment by cojarbi** [comment]
About time. I hope I'm alive to beta test

**Comment by jorgerobles** [comment]
I've got it running locally. 

Keyboard jogging is running if Jog Panel is focused, that is, anything on the panel has been clicked. If you click outside, like workspace, the keyboard jog ceases to work. This is not an intended behavior, but a `react-keydown` one. Could work further on that if proves faulty.

Click jogging works well. I've limited to the Grid coordinates. Clicking outside the grid,  clamps to the max/min coordinate. I have no clear idea of what to do about homing first. Do we pop a confirm the first session click if has not been homed? Do we enable explicitly on jog panel as a toggle? Or maybe raise a flag if homed and use it to allow live jogging?

I would go for a toggle on Jog properly explained. Each time is turned on, machine will home and set the flag and then click jogging will work. if turned off, will disable.

**Comment by cprezzi** [comment]
I would like to switch the workspace between edit-mode and jog-mode. 
It's very tedious already to work on the jog tab and shift, zoom, rotate the workspace, because I allways shift an object insted of the workspace.
If we do that, we get a lot of keys free for usage ;)

**Comment by cprezzi** [comment]
@cojarbi Jog movements during a job will be added to the end of the queue, so no problem for the job, but probably bat after that.

**Comment by jorgerobles** [comment]
I'm already on it. But we have to move a lot com/jog architecture to redux state. Is the only way to have a canonical state in the whole application.

I mean, the `pause` and `playing` vars should be moved to an 'job' state so all the components have access to it.

**Comment by cprezzi** [comment]
@jorgerobles Remind that we use/show work coordinates, not machine coordinates, so you could not limit jogging by the coordinates.

**Comment by jorgerobles** [comment]
Is mandatory to make a homing to use live jogging

**Comment by cprezzi** [comment]
Many machines (ex. diode lasers) don't have homing-switches, but still need jogging

**Comment by jorgerobles** [comment]
Then they have to look a solution to replicate the screen to their machines. I've got one, and just put the head on a corner and G92 X0Y0, or then we have to query their machines for stored position. Workspace right now is not showing work coordinates :|

**Comment by jorgerobles** [comment]
Live jogging is a bit leaned to homing capable machines, like k40, you know what I mean.

**Comment by cprezzi** [comment]
Workspace IS showing work coordinates after the user zeroed the axis.

**Comment by cprezzi** [comment]
That's a historical thing. LW allways used only work coordinates.
But I think we need to add both coordinate systems (switchable), especially since we move to milling.

**Comment by jorgerobles** [comment]
O_o .. Confusing.
The grid does not reflect negative coordinates, is showing machine coordinates rendering. 
That is a pending job (I started with machine offsets to move the axis to the real work position)

**Comment by cprezzi** [comment]
I think that's a lot of work that needs to be donne correctly, not ad hoc. We should support G54 to G59.2.

**Comment by jorgerobles** [comment]
@cprezzi anyway, I think does not matter if are work or machine coordinates. I not supposed to click arbitrarily out the grid (speaking of live jogging) as have no reference of what are doing. 
What kind of solution do you propose?  I can strip homing first limitation but then is up to the user to care about his machine.

**Comment by jorgerobles** [comment]
And rename machineWidth and machineHeight to workWidth, workHeight :smile:

**Comment by cprezzi** [comment]
Back to key jogging. We need six keys for X,Y,Z, not 4 ;)

**Comment by jorgerobles** [comment]
It's done :D I have not commited yet, but supports ctrl+alt+up/dn to Z

**Comment by cprezzi** [comment]
Where did you implement it? In jog.js?

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/LaserWeb4/commit/2b610c52a66733d20892ed3b0128b4e9da6cb224 :)

**Comment by cprezzi** [comment]
That's just the live jogging in workspace, right?

**Comment by jorgerobles** [comment]
Live jogging and key jogging.

**Comment by cprezzi** [comment]
Ah found, jog.js was folded ;)

**Comment by cprezzi** [comment]
@jorgerobles Why did you reformat so much code? That does it make very hard to see the real changes.

**Comment by jorgerobles** [comment]
Sorry, was vscode autoformat. will try to isolate.

**Comment by cprezzi** [comment]
Uhh, I use brackets ;) But their autoformat is even worse ;)

**Comment by jorgerobles** [comment]
vscode format is ok, just had to make it on other commit, so can read clear.

I've added the [keyUp...] decorators, added LiveJogging component.
Synced isplaying and paused to jog state on mount and unmount, so can react changes on child components. Hard access to that variables does not reflect on bounded components

**Comment by cprezzi** [comment]
I have tested a bit. The alt+click on wokspace work as expected, but the keybours shortcuts don't work, because alt+left and alt+right are used by the browser for previous/next url.

**Comment by jorgerobles** [comment]
my fault. should did e.preventDefault. Will fix later.

**Comment by cprezzi** [comment]
What do you guys think about my idea of a workspace mode for edit or jog? 
Would make working in jog much easyer.

**Comment by cprezzi** [comment]
In jog mode, documents/objects should not be clickable or moveable and positioning box should not open.

**Comment by jorgerobles** [comment]
Yes, I agree. For example, if in jog tab, is jog mode.

**Comment by jorgerobles** [comment]
@cprezzi what does lw.comm-client.js? have not seen any reference. Is it lw3 legacy code?

I did some abstraction (and there's a lot of room to improve) to `video-capture.js` and I think is the way to go with comms client, that is, group all the `comms` methods on a regular class (not react component) and bound to store (or laserweb component.). http://redux.js.org/docs/api/Store.html says you could also call dispatch without bind to a component, also.

Why the hassle?  Because react interface is not updating as we need, unless we play its game. Actual implementation of jog commands does not relate with redux nor bound to a component that can dispatch to central state, and then all the application could be aware of their changes.

I'm creating a com.js reducer, and caught some floating vars to it. Please take a look to add missing ones.

**Comment by jorgerobles** [comment]
@cprezzi Jog Mode implemented, maybe should be always active except on Cam tab.

**Comment by cprezzi** [comment]
@jorgerobles lw.comm-client.js is not used. It was just a first try to port the LW3 code.

**Comment by jorgerobles** [comment]
@cprezzi  I've started a comms client refactor (WIP) at https://github.com/LaserWeb/LaserWeb4/commit/e7f6aac165d7a35213cb8c2fdcb789c79f57836d
Allows to spread state to any react component. Please take a look :smile:

**Comment by cprezzi** [comment]
@jorgerobles Just be aware that the actual comm code is in components/com.js. The old lib/lw.comm-client.js was never finished and is probably not compatible anymore with the actual lw.comm-server API.

**Comment by jorgerobles** [comment]
Yes I know, indeed refactored code is taken and leaned from com.js :)
