### ISSUE TITLE
File dialogue bug

### ISSUE THREAD

**Issue by DarklyLabs** [LaserWeb/LaserWeb4#245]
Press 'add document' to open a file dialogue window.
Without selecting anything, press 'cancel'
Trying to add a document from now on is no longer possible. No dialog box is opened.

Verified on 4.0.45 Mac and Win builds

**Comment by cojarbi** [comment]
Can replicate in 4.0.48. Only way out is going to another screen from the left menu and come back.

**Comment by jorgerobles** [comment]
This is very tricky. Involves react overdipatching and that fileinput does not fire any event on cancel, thus cannot restore the initial state.

**Comment by DarklyLabs** [comment]
@jorgerobles Perhaps one of the other developers can shed some light on how to fix this bug?

**Comment by jorgerobles** [comment]
@DarklyLabs, fixed using another hack, this seems to work on Mac. Please test on Win, thanks :)

**Comment by DarklyLabs** [comment]
@jorgerobles Can confirm it is working correctly now in win x64 exe.
Well done.

**Comment by cprezzi** [comment]
@jorgerobles The same bug still exists on the workspace load and the gcode open buttons.

**Comment by cprezzi** [comment]
@jorgerobles Sorry, false alarm. I did test with the exe, but that's a day older than your commit ;)
It works great in the dev environment.
