### ISSUE TITLE
Dragging 3D viewer not proportional to viewPort, seems proportional to Window

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#249]
Dragging in the viewer feels unnatural.  

Play with LW3 and see how well OrbitControls+ThreeJS felt in that respect 

I am taking a guess but it feels like mouse events are scaled from Window, instead of the actual Viewer's dimensions?  Thus mouse outruns actual move?

**Comment by tbfleming** [comment]
Improved version:

![lw4 pan improved](https://cloud.githubusercontent.com/assets/418464/24824755/b9004482-1bdf-11e7-9f35-c84f7d59cf2d.gif)

Compare with LW3:

![lw3 pan](https://cloud.githubusercontent.com/assets/418464/24824757/c0c654e0-1bdf-11e7-9845-c580966bd6b5.gif)

**Comment by tbfleming** [comment]
I cheated with the LW3 comparison. See if you can spot what it is.

**Comment by openhardwarecoza** [comment]
Tested, works much smoother thanks!

And negative, you got me stumped - can't see what the cheat is?

**Comment by tbfleming** [comment]
Perspective is off in the LW4 capture; LW3 can't turn it off. With perspective, motion speed varies with distance to camera.

**Comment by openhardwarecoza** [comment]
ahh yes!
