### ISSUE TITLE
DXF file contains appropriate layers in qcad; layers showing incorrectly in LW4

### ISSUE THREAD

**Issue by PeterGrace** [LaserWeb/LaserWeb4#258]
I downloaded this dxf from thingiverse.  I loaded it in QCad and moved the cuts and parts to separate layers to ease the frustration of trying to select a lot of polylines in the LW4 selection box.  Unfortunately upon loading the dxf, the layers in LW4 do not match what QCad shows.

Any insights into why this is happening would be much appreciated!

[Pi-supply_case_rev_3-layers-R14.dxf.txt](https://github.com/LaserWeb/LaserWeb4/files/914035/Pi-supply_case_rev_3-layers-R14.dxf.txt)
[IncorrectLayout.json.txt](https://github.com/LaserWeb/LaserWeb4/files/914038/IncorrectLayout.json.txt)

**Comment by jorgerobles** [comment]
@iceblu3710

**Comment by openhardwarecoza** [comment]
Seconding @iceblu3710

Confirmed the users file in QCad is correct, and further proved that the old parser in LW3 interprets it correctly:

![lw3](https://cloud.githubusercontent.com/assets/7695323/25091252/68d06b76-2388-11e7-861a-52149256ccad.PNG)

**Comment by iceblu3710** [comment]
PR #266 fixes the issue.

When the layer/entity order is jumbled the layer info was not being carried with the entity when added to the document. byLayer color was also broken in this case. All solved now.


![issue258](https://cloud.githubusercontent.com/assets/187394/25114437/fa09d1bc-23bb-11e7-87fc-f8bb61314fda.png)

**Comment by openhardwarecoza** [comment]
Thanks @IceBlu3710! Merged PR, it will make its way into tonight's nightly build (:
