### ISSUE TITLE
Z-Safe Height for milling ops

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#262]
So, over the weekend I finally build/wired up and commisioned my new mill (provided by OpenBuilds) so at last I am back to hands on testing

Maybe I just dont see it?  But I did take a second look today...   It seems milling ops retract out only to Z=0 between entities, it doesnt go above the surface with some clearance, commonly called Z-Safe height?

![no z safe](https://cloud.githubusercontent.com/assets/7695323/25090705/1473190a-2385-11e7-9d17-c085e5effda4.PNG)

Note: No moves above Z=0 in LW4

In LW3: Note the 10mm Z Clearance between moves - just helps if an edge has a chip up, or when you zeroed it wasnt quite Z=0 

![lw3 z moves](https://cloud.githubusercontent.com/assets/7695323/25090733/58084be0-2385-11e7-8893-a5ea6f857a8a.PNG)

**Comment by openhardwarecoza** [comment]
Oh and it should be configurable per operation - not all op's have the same remaining Z clearance (; 
But a sane default is 3mm 

![lw3 z moves](https://cloud.githubusercontent.com/assets/7695323/25090814/c3767eba-2385-11e7-97c5-4bdc958fbaad.PNG)

**Comment by tbfleming** [comment]
Another setting disappeared? I think I called it clearance.

**Comment by cojarbi** [comment]
Yes I'm using clearence

**Comment by openhardwarecoza** [comment]
Ahh! See even I missed that - may i suggest a clearer label (; 

And as far as I'm concerned that should probably be flagged as required?

![clearance](https://cloud.githubusercontent.com/assets/7695323/25091462/7dd9d77c-2389-11e7-8eb8-43ccd758f250.PNG)

**Comment by openhardwarecoza** [comment]
(: Sidenote I want to work on the UI of all these a little: For example in the screenshot, it irritates me that Final Cut Depth and Pass Depth despite being so closely related to each other, are not directly below each other (;

**Comment by jorgerobles** [comment]
Huh! I'm showering out glory! Will check :|

**Comment by openhardwarecoza** [comment]
No probs Jorge, found it! Needs a better label if it confuses me! #newb @openhardwarecoza go read the #rtfm! Lol!~

**Comment by cojarbi** [comment]
So im the only daredevil using the milling?

**Comment by openhardwarecoza** [comment]
Probably not - I hope!

**Comment by openhardwarecoza** [comment]
https://github.com/LaserWeb/LaserWeb4/commit/31ee365bd421685d4307ec103b4204ff1a0a51c1#diff-34b9ac852e7b8fd2059fcba0ce0c9662R360
