### ISSUE TITLE
COM Refactor branch integration

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#264]
@cprezzi, been doing a migration to react of `components/com.js` and `lib/lw.comm-client.js` . It's almost complete but needs some testing. Mainly the button classes are not implemented yet. Could you take a look for functionality?

What do you use to test? a full blown machine or a bare arduino board?

**Comment by jorgerobles** [comment]
Ditched. will arise soon or later.

**Comment by cprezzi** [comment]
Sorry that I never head time to test!! :(

**Comment by jorgerobles** [comment]
I supposed ;) 
Will take on summer :+1:
