### ISSUE TITLE
Mill ops: S value for spindle speed

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#274]
From Alex Krause on https://plus.google.com/+PetervanderWalt/posts/PJxUmz8KMue

>The lack of spindle speed commands in the CNC portion... Still haven't been able to command a spindle speed using m3 and s*** on the console

**Comment by jorgerobles** [comment]
Please refine. Is console faulty? Can it be done with macros?

**Comment by openhardwarecoza** [comment]
Neg. Should be an option on milling CAM operations: Spindle Speed 0-100%.
Which adds a (S0-100% * s-multiplier) at start of operation.  S pwms the
spindle controller and sets the speed of the endmill spinning. Slower for
alu, faster for wood, for example. Mind you then it also needs to be hooked
to material db

**Comment by jorgerobles** [comment]
Ok. Adding option is easy (materialdb not a problem is all synced), Gcode gen maybe harder @tbfleming do you foresee any issue?

**Comment by tbfleming** [comment]
Traditionally S value on mills is RPM for compatibility with feed and speed calculators. If I remember right Both grbl and smoothie can adjust their range to calibrate this.

**Comment by openhardwarecoza** [comment]
Aha! Correct yes.

**Comment by jorgerobles** [comment]
@tbfleming what does imply this apart adding UI option?

**Comment by jorgerobles** [comment]
@openhardwarecoza what is s-multiplier? please write gode example of desired scenario. I'm a bit fuzz.

**Comment by openhardwarecoza** [comment]
S as in pwm value. S multiplier for smoothieware is 1. For grbl its
whatever $30 is. Its in Settings

**Comment by jorgerobles** [comment]
ok, then is the PWM MAX S VALUE on settings?

**Comment by openhardwarecoza** [comment]
Yip that (:. Sorry on phone. Will type out example tomorrow

**Comment by jorgerobles** [comment]
It's the same as Laser Power, but for milling?

**Comment by openhardwarecoza** [comment]
Yip

**Comment by tbfleming** [comment]
My recommendation: don't scale S on mills. If the firmware's calibrated correctly, then if the user enters e.g. 4000, and you produce S4000 in gcode, then the spindle will run at 4000 RPM.

**Comment by jorgerobles** [comment]
Then is not a percentage. Should be added as an "axis" on machine feed rates?

**Comment by tbfleming** [comment]
Yes. e.g. G1 X5 Y4 F100 S4000.

**Comment by tbfleming** [comment]
The percentage thing is because lasers repurposed S.

**Comment by jorgerobles** [comment]
Done!
