### ISSUE TITLE
Clamp input fields to validated values

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#277]
For example laser power field, we warn if <0, but we do allow user to type it in.  As per Tobias Holzman on https://plus.google.com/+PetervanderWalt/posts/PJxUmz8KMue - consider clamping inputs?

**Comment by jorgerobles** [comment]
This drives to frustation, then anger, then the dark side.

**Comment by jorgerobles** [comment]
I've done some tests but none are enforcing this without a major refactorization. Closing for now.
