### ISSUE TITLE
Mousewheel zoom: Center viewport on mouse

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#281]
From https://plus.google.com/+PetervanderWalt/posts/PJxUmz8KMue - mousewheel zoom always needs a drag reposition too.

**Comment by openhardwarecoza** [comment]
For what its worth, threejs also didnt do this (; so i know this probably isnt easy (pov calculation with raycasting... yikes)

**Comment by tbfleming** [comment]
Done!
