### ISSUE TITLE
REQUEST: Clear-all on operations

### ISSUE THREAD

**Issue by KirAsh4** [LaserWeb/LaserWeb4#289]
While one can remove an image or operation by clicking on the red [X] on each line, when you have multiple operations, it gets tedious to be clicking on each line to remove them. Can there be a single 'remove all' button to clear everything (similar to the trashcan icon to clear the visible gcode from the canvas)? Doesn't matter much on the loaded images, but more so for the operations. Some of my designs will have quite a lot of operations because I switch between engraving, marking, and cutting all on the same design, and I do it in a specific order as I traverse the material (to avoid things like loose pieces getting in the way of the moving head, or if the board is warped, I tend to do all engraving and inner cuts in a specific order before doing the final large cuts.)

**Comment by tbfleming** [comment]
Do you mean remove all operations, or move all document objects within a single operation?

**Comment by KirAsh4** [comment]
I suppose both, though in this case I'm referring specifically to removing all operations.
![lw_operations](https://cloud.githubusercontent.com/assets/4676811/25450527/717c245e-2a7c-11e7-9bc2-b1c8b2132834.png)

**Comment by openhardwarecoza** [comment]
Clicking on the document level, deletes all children. Same for layer level

**Comment by KirAsh4** [comment]
That's not what I'm asking for.

**Comment by openhardwarecoza** [comment]
Exactly what your first post + screenshot did ask

**Comment by openhardwarecoza** [comment]
Except for the operations (note i mentioned Document level)

**Comment by KirAsh4** [comment]
My first post, and the screen shot, talks about the operations, clearly defined and noted in the image as well. Nowhere do I say that I want to get rid of the (multiple) layers within an operation.

**Comment by KirAsh4** [comment]
Even Todd asked, 'delete all OPERATIONS' or all documents. Again, nowhere does it talk about the individual layers.

**Comment by openhardwarecoza** [comment]
<thumbsup>

**Comment by jorgerobles** [comment]
Done. Will show next build.
