### ISSUE TITLE
UI: Macro Panel 

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#29]
Action: Port / Rewrite functionality from LW3

Present Source: https://github.com/LaserWeb/LaserWeb3/blob/master/public/js/macros.js

Desired result: Popup Makro panel with programmable Gcode macros

**Comment by openhardwarecoza** [comment]
I love the work you've done on this! Good idea to have them in the jog panel. I put them into bootstrap panels too so we can collapse as appropriate on small screens

**Comment by openhardwarecoza** [comment]
https://github.com/LaserWeb/LaserWeb4/commit/20a7cb50f2e7813f96d54fb22ffb9e2edb2da1cb

**Comment by jorgerobles** [comment]
Thanks! There's a component that abstracts BS, react-bootstrap, you could use 

import {Panel} from 'react-bootstrap'

<Panel>
</Panel>

**Comment by openhardwarecoza** [comment]
darn, sorry! Will redo!

**Comment by jorgerobles** [comment]
It's ok, was a friendly advice, not imperative ;)
