### ISSUE TITLE
Missing JSON files prevent compilation

### ISSUE THREAD

**Issue by hepabolu** [LaserWeb/LaserWeb4#295]
```
git clone https://github.com/LaserWeb/LaserWeb4.git   # dev_es6, 4.0.728
cd LaserWeb4
npm install
npm start
```

Compilation fails, because 2 files are missing:

ERROR in ./src/reducers/machine-profiles.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../data/lw.machines/machine-profiles.json in [path]/LaserWeb4/src/reducers
 @ ./src/reducers/machine-profiles.js 20:76-128

ERROR in ./src/reducers/material-database.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../data/lw.materials/material-database.json in [path]/LaserWeb4/src/reducers
 @ ./src/reducers/material-database.js 34:66-120

After adding both files with an empty JSON object compilation succeeds

**Comment by jorgerobles** [comment]
<pre>
git clone https://github.com/LaserWeb/LaserWeb4.git   # dev_es6, 4.0.728
cd LaserWeb4
npm install
</pre>
**`npm run installdev`**
<pre>
npm start
</pre>

**Comment by hepabolu** [comment]
Maybe good idea to note this in the README ? I was just following instructions in the README.

**Comment by jorgerobles** [comment]
Will do, sorry

**Comment by openhardwarecoza** [comment]
@hepabolu are you a user or a dev?

Devs are usually familiar with checking package.json for scripts. The fact
you mentioned following the manual, makes me want to check if you arent a
user trying to install LW, in which case, head over to
github.com/LaserWeb/LaserWeb4-Binaries instead (:

**Comment by jorgerobles** [comment]
@hepabolu please, what readme are you following? Thanks!

**Comment by openhardwarecoza** [comment]
(; good point @jorgerobles we dont have any instructions in the LW4 readme,
so its not from that he was following

**Comment by hepabolu** [comment]
@jorgerobles The readme found here, in plain sight: https://github.com/LaserWeb/LaserWeb4
@openhardwarecoza I'm a programmer, but not good enough in NodeJS to help out with this project, so in this case I'm more of a user. I installed this project, because there are currently no OSX LaserWeb4 binaries and I wanted to test if the macro buttons work in 4.0728. So I simply followed the instructions on the front page of this project. ;-)

**Comment by openhardwarecoza** [comment]
There is a dmg on the latest release

**Comment by hepabolu** [comment]
???? On https://github.com/LaserWeb/LaserWeb4-Binaries there is a message that there is no dmg. Where can I find the dmg ?

**Comment by openhardwarecoza** [comment]
One question mark would suffice. Under the releases tab
