### ISSUE TITLE
Cut Rates wonky

### ISSUE THREAD

**Issue by KirAsh4** [LaserWeb/LaserWeb4#296]
Referring to .68_729 - Cut Rate appears to now be limited to 10000 mm/min which translates to 166 mm/s. Was there a reason for this?

Also, setting the app settings to mm/s, it still allows me to put in a Cut Rate of 10000. I think that's a bit much there. Something's going to break at that speed.

**Comment by jorgerobles** [comment]
Thanks @KirAsh4. Moving this conversation to #294, still open. What mm/s do you work on?
