### ISSUE TITLE
Clear workspace / reset workspace button 

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#299]
Done with job on. Click clear. Load new files for job 2. :)

**Comment by jorgerobles** [comment]
Hmm you can delete operations with our brand new button "clear all". 
Maybe we can ask if deleting the documents also, if not, just click root X ;D

**Comment by openhardwarecoza** [comment]
After deleting ops and deleting docs. You also need to clear gcode (; thats
three clicks. How about one small button next to load/save workspace that
just clicks all 3 for me (:

**Comment by jorgerobles** [comment]
.... Done :P

**Comment by openhardwarecoza** [comment]
Thanks (:
