### ISSUE TITLE
New "work area" and machines >500

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#306]
Loving the new look! 

(; but I have one machine with a 600mm X (; so the hard coded +-500 is a little issue

![600mm](https://cloud.githubusercontent.com/assets/7695323/26051048/444da874-3961-11e7-9f7b-ec04a3c173b2.PNG)

**Comment by jorgerobles** [comment]
@openhardwarecoza Missed something? It's buried on a comment.

![image](https://cloud.githubusercontent.com/assets/1706080/26052780/daeb534e-3966-11e7-9d59-5833f55ac094.png)

**Comment by openhardwarecoza** [comment]
Ahh ok, found it. Not immediately obvious enough maybe?

**Comment by cprezzi** [comment]
I have a OpenBuilds machine with 1m * 1m ;)
