### ISSUE TITLE
Config units are in megamolar

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#307]
![image](https://cloud.githubusercontent.com/assets/418464/26069800/3a8529fc-3970-11e7-8e58-8dd5c81c9740.png)

https://en.wikipedia.org/wiki/Molar_concentration

1 MM is such a high density it's off the chart!

**Comment by jorgerobles** [comment]
Yeah, we are such cooool  :)

**Comment by jorgerobles** [comment]
Will fix ASAP

**Comment by cprezzi** [comment]
No need to fix. All caps is not a bug. Will look ugly if small mm...
