### ISSUE TITLE
Global operation starting height

### ISSUE THREAD

**Issue by domenic-d** [LaserWeb/LaserWeb4#308]
Setting the starting height for individual operations is useful, but we find ourselves and customers using one material height at a time, most of the time.

With many operations being used at a time it becomes cumbersome to systematically go through each one when a different material thickness is being used.

A global starting height would in actual fact prove more commonly used.

Without wanting to add extra options, I just wanted your thoughts on this and whether you agree with this and/or have any suggestions on how to work this in?

**Comment by tbfleming** [comment]
I suspect this may apply to multiple fields. Maybe a button by each field which copies the value to all other operations?

**Comment by domenic-d** [comment]
I see, this feature could prove useful with the absence of a 'duplicate' operation.

**Comment by cprezzi** [comment]
What if we just remember the last used value and use it for every new operation?

**Comment by jorgerobles** [comment]
I'm already working on the duplicate button. :)

**Comment by cprezzi** [comment]
I would prefer the "last value" way, as this would also speed up the process of designing multiple different operations, not only duplicates.

**Comment by jorgerobles** [comment]
Ok, will think about the better way to implement.

**Comment by openhardwarecoza** [comment]
I also prefer the "last value" and sometimes even useful if that can persist in localstorage between sessions and between workspace resets.  I find myself buying a sheet of some material, using it for everything, lol. Maybe thats my budget's problem not lw's lol

**Comment by jorgerobles** [comment]
Ok, it's easy to save last operation selected on localstorage, but are you sure that's the way?  a redux key currentoperation is stored and may be used as reference-- that is the same as duplicate. 

It's unclear for me the way it has to proceed.

BTW- the start height is a setting already, that fills every operation that has is empty...

**Comment by cprezzi** [comment]
I wouldn't store the whole operation, just all the separate field values (independant of operation type).

**Comment by jorgerobles** [comment]
Ok then. We are then talking specific, hardcoded, fields, `start_height` and `cutrate`?

**Comment by cprezzi** [comment]
That was my idea. All fields (that do not have a differently defined init value) would just use the last used value of that field. Applying something from the material database would override the fields value, but not the saver "last value".

**Comment by domenic-d** [comment]
Repeating the previous value for a new operation only partially addresses things.
From my initial post, the time consuming part is when you need to go back and use the same set of operations for a different thickness of material. This is the time consuming part.

In actual fact, I would almost say it's not appropriate to have previous operation values automatically filled when creating a new one as it could lead to users not checking the values that are blank and obviously important.

**Comment by jorgerobles** [comment]
@domenic-d then, an "link all button" on start height? The button could will be located on the start height field each operation next its name or beign a context button over the field name. if toggled any change on start height on that field will automatically spread that value to all operations.

**Comment by jorgerobles** [comment]
Ok, I've implemented a contextual menu available on operation fields `startHeight`, `cutRate`, with the command _Spread to all Ops._ This copy the value of the actual entered field to all the other operations.
It's generic so it's base to extend any field with some context menu.

**Comment by jorgerobles** [comment]
@domenic-d can you take a look to the latest code? Is that context menu closer to your idea?

**Comment by domenic-d** [comment]
@jorgerobles Clever solution without cluttering up the UI with more buttons.
I think it should be probably called 'Copy to all Ops' instead of 'Spread....'

From my testing it seems to be working correctly.

Thank you.

**Comment by jorgerobles** [comment]
Copy then :)
