### ISSUE TITLE
Machine Profiles

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#31]
Long requested functionality:  Saved machine profiles / Material database

Also, this can be used to attract sponsors by including premade profiles, profiles can include customised functionality

**Comment by jorgerobles** [comment]
+1000

**Comment by tbfleming** [comment]
> +1000

What units is that in?

**Comment by jorgerobles** [comment]
ThumbsUps of course ;)

**Comment by jorgerobles** [comment]
So go refine a bit more. Proposal:

**Machine Profiles:**
Would the profile be an stored group of settings? If this is it, I imagine go to settings tab, and have a dropdown/modal interface where select one of the stored machine settings with some info about the machine. Then the settings forms will be filled up with that profile (maybe an "r u sure?" nag). I think this way you could still touch the settings freely in case you have a customized-of-the-shelf machine.
On the save settings then have the possibility to tag your settings. Balanced between noobs and expert user.

**Material Database:**
This would affect two sections

  1. **On Settings:** The Edit Material Database needs some space on screen. I don't know if We go for a modal, or go for a whole new section without workspace area. Anyways could show an editable datagrid (excel like... http://adazzle.github.io/react-data-grid/index.html) that displays the Name of the material, an Operation profile tag (Cut, Engrave, etc) and then the Operation Speed, Operation Intensity, Operation Passes, and maybe some more I don't know :smile:

  2. **On CAM:** There would be a wizard icon next to the operation selector, and launch some modal that allows you to select the material/operation tag. Then the operation settings will be overriden, like the way described on Machine Profiles, allowing to tweak for the experts and so on.

<:unicorn:> A coooool feature would be allowing to "cloud update" both the Machine profiles and the Material Database </:unicorn:>

**Comment by jorgerobles** [comment]
FYI.. not comitted
![machine_profiles](https://cloud.githubusercontent.com/assets/1706080/20246963/1b3adf1c-a9c2-11e6-8c28-a09c90f54041.gif)

**Comment by openhardwarecoza** [comment]
Exactly what i had in mind yes.  Dropdown populates defaults.  Just add to
that a way to save your profile

**Comment by jorgerobles** [comment]
And a way to delete too :)
The custom profiles would be stored on LocalStorage and merged with the application hardcoded ones. On future will be sent to the server part for full storage. Deal?

**Comment by openhardwarecoza** [comment]
Deal.  As long as it can be backed up from the current backup settings
button (: then localstorage is fine

**Comment by jorgerobles** [comment]
I could add a download profiles button. No fuss.

**Comment by jorgerobles** [comment]
Go, go, go!

![machine_profiles](https://cloud.githubusercontent.com/assets/1706080/20276189/8f21ba3e-aa9b-11e6-9841-489c7a52bf7e.gif)

**Comment by openhardwarecoza** [comment]
Please post this under the Development. News on g+!

**Comment by funinthefalls** [comment]
Extra helping of awesome sauce on this one!

**Comment by jorgerobles** [comment]
Now we need some machine profiles :P. I will close the issue until they come.

**Comment by openhardwarecoza** [comment]
@quillford @jorgerobles

**Comment by openhardwarecoza** [comment]
@jorgerobles what was the exact plan, where are we hosting the machine profiles? Git repo? 
@quillford wants to code this into LW3 and I advised him to talk to you first.  Since LW4 is still a short way from done I dont really want to put off doing it in LW3, but I also dont want whatever we do to be completely incompatible with LW4 work...

**Comment by jorgerobles** [comment]
Good question! (I've no mind of it until now :smile: ) It's a great idea to host on a repo, with default setting url of the "official" repo customizable to other users repos (if they want).
But the idea gets complex if we want them able to commit to the repo. We have to study github rate limits, etc.
The folder option will work better for keep their own profiles and tweaks, but for that we need system access (electron...)

**Comment by kaosat-dev** [comment]
Electron way is the easiest I think these are essentially 'plugins' like in the atom editor. So no need to worry about github rates etc

**Comment by openhardwarecoza** [comment]
'But the idea gets complex if we want them able to commit to the repo' ...

The idea here isnt the indivisual users pushing their private configs up to the  repo.
Its more about the preconfigured "default" templates, a standard K40+Smoothie, a Emblaser, a Fabcreator profile, etc...)

And after playing with Electron yesterday, I am in love.  Electron it is (no argument there) so we can store local configs in json locally.  But for that initial configuration, it would be nice to obtain a "almost good enough" config from the dropdown

**Comment by jorgerobles** [comment]
Ok then, there will be a button/automatic way to get the profiles from repo. In the meantime there's a  data/machine_profiles.json where any contributor can work with. It's a simple dictionary,  prefixing the machine profile id with * prevents to be deleted by error in LW4 interface

**Comment by openhardwarecoza** [comment]
Cool stuff

@quillford -  check that out and see if thats suitable for your work too?

(or skip doing that in lw3,  rather tackle more lw4 work so we can complete
port sooner)

**Comment by quillford** [comment]
To clarify, the way I understand this should be implemented is: for lw4 we have default/preconfigured profiles the user can load but they also have their own customized ones which are saved locally. for lw3 they can basically use the existing restore functionality and get a sightly easier way to load a preconfigured profile. Is this right?
