### ISSUE TITLE
Ramping plunge on mill ops

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#311]
@tbfleming please please i am begging (;
I broke another endmill today plunging into aluminum (; and it remindes me I havent asked yet. 

Can we get ramping plunges on mill ops (;

**Comment by tbfleming** [comment]
yes

**Comment by jorgerobles** [comment]
@openhardwarecoza the ramps algorithm existed already ;)

**Comment by jorgerobles** [comment]
@openhardwarecoza is it enough? closing?

**Comment by openhardwarecoza** [comment]
(: Taking the family away for a little long weekend - will test Monday - but yeah, close for now (:
You guys are too awesome!
