### ISSUE TITLE
Tabs: Milling: Seems to take center of tool and not account for tool radius

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#313]
For example: Add 10mm tabs, resultant cut is only 4mm if tool is 6mm dia

![tabs](https://cloud.githubusercontent.com/assets/7695323/26259706/7c87c550-3cca-11e7-88b9-32b23acf0b5f.PNG)

Bad Example case:  If I add a 5mm tab, and my tool is 6mm - it cuts through the tab (ouch my arm - throw the part at me)  - didnt notice it before as I used 5mm tabs with 1/8th endmill.  

Shouldnt the tool retract at (half tool dia) before the tab start?

**Comment by tbfleming** [comment]
Fixed.
