### ISSUE TITLE
name change?

### ISSUE THREAD

**Issue by FabCreator** [LaserWeb/LaserWeb4#316]
Just wondering if there is a plan to change Laserweb 4 to CNC pro any time soon?
I think we are currently in a bit of a limbo between names. Its starting to become potentially confusing for current and future users. 
As the wiki is now call CNC Pro perhaps we should just dive in and change all the names to conform? 
Thoughts?
![image](https://cloud.githubusercontent.com/assets/19230933/26285007/4772a050-3e47-11e7-9af6-8cab042f2278.png)

**Comment by jorgerobles** [comment]
Wont happen for now. :|
