### ISSUE TITLE
LW UI Performance hit

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#318]
I'm having hard time with parallel webworkers concurrency and react response. 
The most patent case is that LW is unresponsive on Gcode generation due to parallel processing choke.
Can anyone lend me a hand?

**Comment by tbfleming** [comment]
Try limiting the number of workers to the number of CPU threads - 1. Ex: my desktop is a 4-core 8-thread machine, so it'd be 7 on it. There is no browser API that reports this so it'd have to be a setting.

**Comment by jorgerobles** [comment]
Is a setting indeed :) I've done a naive approach using setinterval to
percent dispatching. Seems good but maybe there's a better way.

**Comment by jorgerobles** [comment]
I'm quite in shock. A ~44sec computing to merely 1s540
