### ISSUE TITLE
Updating libs

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#319]
@tbfleming what about updating some key libs? (Not updated yet on LW)
- poly2Tri is now 1.5.0
- clipperjs is now 1.0.2
...

**Comment by tbfleming** [comment]
If upgrading gains capability or performance or solves a bug we hit. e.g. does the upgraded poly2tri handle the test case in #146?

**Comment by jorgerobles** [comment]
I dunno :|.  Gonna update and check, I suppose.

**Comment by jorgerobles** [comment]
Nothing to update (on those libs) were already on latest
