### ISSUE TITLE
Feature request - joystick for jogging.

### ISSUE THREAD

**Issue by funinthefalls** [LaserWeb/LaserWeb4#323]
I was hoping that we could get joystick jogging added to the current feature set.

Thanks in advance
Anthony

**Comment by jorgerobles** [comment]
@funinthefalls I would rather use a Joystick to Keyboard mapping software. Using Joystick seems a bit complicated to include right now.
Have you tried Live Jogging feature?

**Comment by funinthefalls** [comment]
I can give mapping software a try. I had spoken to Todd about adding joystick ability, and he said to go ahead and ask for it. But I understand you guys have your plate full right now, so I will try your suggestion, and maybe revisit this when you guys are not so busy. Thanks for the quick response, I'll close this for now.

**Comment by jorgerobles** [comment]
Thanks!

**Comment by jorgerobles** [comment]
Highly experimental Gamepad support @funinthefalls, @openhardwarecoza 
https://github.com/LaserWeb/LaserWeb4/tree/gamepad

**Comment by funinthefalls** [comment]
Thanks. How do I run this to rest it on my system?

**Comment by jorgerobles** [comment]
What OS do you use? Win? I could try to compile this branch for you, or maybe could you install development stack (faster for dev/testing)

**Comment by jorgerobles** [comment]
If you use linux, here is the app http://laserweb-release.s3-website-us-east-1.amazonaws.com/LaserWeb/LaserWeb4/211/211.1/dist/lw.comm-server-4.0.78-x86_64.AppImage

**Comment by funinthefalls** [comment]
I am on Win10. If you can give me a list of what I need, I will certainly install the dev stack.

**Comment by jorgerobles** [comment]
@funinthefalls https://github.com/LaserWeb/LaserWeb4-Binaries/releases/tag/v4.0.732c-78

How to:

- Go to settings -> application. Enable **Use gamepad**
- Connect your machine
- Go to Control, Connect your gamepad. should appear on console as Gamepad connected. 
- Lets play! (left jogger)
- Does not work outside jog mode. 

Caveats:
 
- Currently cannot go diagonal (have to review jog command)

Bonus!
- This release includes delete documents selected pressing "del" if mouse is over the workspace.

**Comment by funinthefalls** [comment]
Wow that was quick. Thank you for getting this to me to test.

**Comment by funinthefalls** [comment]
Will be going out this weekend to get a new gamepad for testing. Any reccomendations on make or mode?

**Comment by tbfleming** [comment]
![image](https://cloud.githubusercontent.com/assets/418464/26509479/eefe618c-4226-11e7-9c8f-bc55103d37c7.png)

**Comment by jorgerobles** [comment]
I got a rainbow chinese sh** gamepad and goes fine

**Comment by funinthefalls** [comment]
Nice setup Todd. I have actually considered buying a CH full flight sim joystick,pedal,yoke,throttle package for building a Drone control station, as well as for flying my model planes and helis. I almost bought it then was afflicted with the laser and CNC disease, and all the fun money has been going to this new addiction.


Thanks for the info @jorgerobles

**Comment by funinthefalls** [comment]
Got a gamepad finally, goiong to test over the next couple of days and get back to you.

**Comment by funinthefalls** [comment]
It seems to work OK, but has some jittery movements sometimes. Not sure if it is the cheap gamepad cable, or something in the coding. I am leaning towards it being a crappy cable, as the quality does not appear to be there.

**Comment by jorgerobles** [comment]
Ok, will include to next release, so anyone can test :)

**Comment by funinthefalls** [comment]
Sounds like a plan. Once again, thank you for adding this feature.
