### ISSUE TITLE
Work offset messages ...

### ISSUE THREAD

**Issue by KirAsh4** [LaserWeb/LaserWeb4#324]
Running a K40 Laser cutter with a Cohesion3D board. After installing the latest Win64 binary release, I'm now getting a bunch of these messages popping up.
![workoffset](https://cloud.githubusercontent.com/assets/4676811/26432348/5bb495e6-40b8-11e7-8350-2425ef4a4170.png)

**Comment by KirAsh4** [comment]
Hey Jorge, this is still present in the most recent Windows release. Forgot to update the master branch?

**Comment by jorgerobles** [comment]
I got rid of _continous_ work offset messages on that commit  c3e42cc . Now should only appear the first time the machine shows it or changed. Do still appear to you? 

![image](https://cloud.githubusercontent.com/assets/1706080/26667033/70443be2-46a3-11e7-9afe-a8566b8215a7.png)

**Comment by KirAsh4** [comment]
Yep, a continuous stream. I'm running 4.0.733-79-x64 on Win10.

**Comment by jorgerobles** [comment]
Is it GRBL or Smoothie? @cprezzi  is sthis behaviour firmware dependant?

**Comment by KirAsh4** [comment]
I'm running a Cohesion3D board which runs Smoothie firmware.

**Comment by cprezzi** [comment]
@jorgerobles Grbl is reporting WCO when changed, but less often with status reports (not every). Smoothie (over USB) is reporting MCO and WCO in every position report. I cache the offsets in lw.comm-server and only send them to the client when something changed. At least that's what it should do.

**Comment by cprezzi** [comment]
@KirAsh4 Are you sure you user smoothies *firmware-cnc.bin*?

**Comment by jorgerobles** [comment]
@cprezzi that is what I did in the commit. Is weird it still happens. Is working ok on my board :/

**Comment by cprezzi** [comment]
@KirAsh4 It would help if we could see the lw.comm-server logs. Could you please create a ".env" file in the LW installation folder with the following text in it: `LOG_LEVEL=3`
This activates writing a logfile.txt in the installation folder.

**Comment by cprezzi** [comment]
@jorgerobles I think I found the reason (toggling around +/- zero) and fixed it with lw.comm-server commit https://github.com/LaserWeb/lw.comm-server/commit/c5b3cb496767bad96534986f65792728cfcc1a3f

**Comment by cprezzi** [comment]
I have tested and my commit doesn't fix the problem. I am working on it.

**Comment by cprezzi** [comment]
Ok. Initializing the local position and offset vars to float 0.00 instead of int 0 seems to help :)
https://github.com/LaserWeb/lw.comm-server/commit/5f73724dd9b46ef7e0043971c72920cdd7cc1bde

**Comment by KirAsh4** [comment]
@cprezzi, yep, I'm using firmware-cnc. It sounds like you may have found the issue, do  you still want me to generate a log file?

**Comment by cprezzi** [comment]
@KirAsh4 As I was able to replicate the problem, the log is not needed anymore.

**Comment by KirAsh4** [comment]
Latest release is still exhibiting this. I've attached a log file. Steps I followed to generate this log file (after adding the .env file):
a) launch LW4 (4.0.734-96-x64)
b) Switch to Comms tab and clicked Connect
c) Switch to Control tab and clicked Home All
d) Closed LW4

It's a constant stream of Offset messages as shown in my very first post.

[logfile.txt](https://github.com/LaserWeb/LaserWeb4/files/1065447/logfile.txt)

**Comment by cprezzi** [comment]
@KirAsh4 What you see in the log is normal. These are the position messages that we get every 250ms from the controller, but that's not sent to the frontend. Only changes should be sent to the frontend.

**Comment by KirAsh4** [comment]
Right, I only linked it because you had asked for it previously, _before you made a fix_. What I'm saying is, the problem is still there. In the front end, I'm constantly seeing these Offset messages whenever the laser is working. They seem to correlate to whenever the screen is refreshed and the blue dot indicator is being updated, but I could be wrong here.

**Comment by KirAsh4** [comment]
Hey @cprezzi, can I provide you with any more information on this, or did you secretly already fix this? :)
