### ISSUE TITLE
raster2gcode does not use toolOn or toolOff

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#326]
On Machines that need ToolOn and ToolOf (GRBL) r2g does not include codes to start/end tool each first/last G1

**Comment by jorgerobles** [comment]
@cprezzi, @openhardwarecoza should M3 be always safe with M3 S0?

**Comment by cprezzi** [comment]
@jorgerobles Yes, M3 S0 is aleways safe. M3 without S0 is not safe, as it restores the previous S value, but still can be usefull for machines without laser PWM.
