### ISSUE TITLE
Delay refreshing operation value list

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#327]
While changing operation type, is not until a value is entered that the corresponding list of values is refreshed. 

http://g.recordit.co/aNsqPjNJoT.gif

Latest commit build / OSX

**Comment by jorgerobles** [comment]
@cojarbi Cannot reproduce error. 😮

**Comment by cojarbi** [comment]
I just compiled in windows 10 and getting the same behaviour. 

Try the following:
( make sure CNC mode is on )
Load SVG
Drag file into operation 
Change between the various operation types (inside, outside, etc ) , you will not see   options change unless you type or change a value

**Comment by jorgerobles** [comment]
@openhardwarecoza, @cprezzi, @tbfleming could you please test if the error arises on clean copies? I cannot reproduce. :|

**Comment by openhardwarecoza** [comment]
Confirmed on Win 10 - I get this:
Open file and add document to a new operation: Defaults to 'laser cut' and parameters are as it should be for laser cut. Change operation dropdown to say, Mill Outside.   Paramater stay as they are for laser cut (for example Tool diameter etc stays missing). Start typing in any field (say, Name), suddenly renders the missing fields

**Comment by openhardwarecoza** [comment]
Ruling out SVG - my test was with a DXF

**Comment by openhardwarecoza** [comment]
No errors in devtools, even with debug on

**Comment by jorgerobles** [comment]
I've tested on linux too.. no issues here 😞

**Comment by openhardwarecoza** [comment]
I havent tested latest from dev-es6: That was with last release  (732/78)

**Comment by cojarbi** [comment]
Mind that clicking on the grid or document section also causes the list to refresh.

**Comment by openhardwarecoza** [comment]
Confirmed, grid click works on win10 too

**Comment by openhardwarecoza** [comment]
http://recordit.co/8PER1PYvNV

**Comment by jorgerobles** [comment]
I'm going to compile 733 for windows. Maybe something has been fixed.

**Comment by cojarbi** [comment]
Tested on Linux Ubuntu 17.04 VM, same thing.

Could this have something to do with Display cache? On or Off does not fixe the issue but..

**Comment by jorgerobles** [comment]
The only thing we could do is test from sources without compiling to binaries and go back a commit each time :sweat:

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/LaserWeb4-Binaries/releases/download/v4.0.733-79/LaserWeb.Setup.4.0.733-79-x64.exe

**Comment by jorgerobles** [comment]
http://recordit.co/h907TrBzs6

**Comment by cprezzi** [comment]
It workes correctly on my installed 732-78-x64 on Win10. I'm installing 733 now.

**Comment by cprezzi** [comment]
Version 733-79 works also as expected on Win10.

**Comment by jorgerobles** [comment]
@cprezzi What gpu do you have? (if any)

**Comment by cprezzi** [comment]
AMD Radeon HD 5700 Series

**Comment by jorgerobles** [comment]
ok. I got nvidia.. is not that.

**Comment by openhardwarecoza** [comment]
Nvidia GeForce 210 (yip from couple decades ago) and have the issue. Will
try new build when i get home

**Comment by cprezzi** [comment]
Running from dev environment also works as expected.

**Comment by cprezzi** [comment]
I have tested 733-78-x64 also on the Pipo X10 and it works correctly.

**Comment by openhardwarecoza** [comment]
Tested: Still same, but, one little difference: When switching operations, now i can see the red warning flags appear right about where they would be, but the actual fields still just render after typing or clicking grid

**Comment by cojarbi** [comment]
I do have same behavior with the above hosted live version and the above build.

**Comment by jorgerobles** [comment]
Could be a Chrome issue? Versión 58.0.3029.110 (64-bit) on Mac

**Comment by cojarbi** [comment]
Version 58.0.3029.110 (64-bit) Windows 10

**Comment by tbfleming** [comment]
I Just got my desktop building LW again after a fresh OS install. My EVGA GTX 980 Ti crashed so many times it hosed my OS image beyond what Windows recovery could fix. Fortunately it didn't damage hardware. Yet another manufacturer is on my sh** list.

Works as expected:
* Windows 10 Version 1703
* Node 6.10.3
* Chrome 58.0.3029.110 (64-bit)
* Asus GTX 770

**Comment by cprezzi** [comment]
Same here: works on Chrome 58.0.3029.110 (64-bit)

**Comment by jorgerobles** [comment]
@tbfleming Ouch! :band:

**Comment by cprezzi** [comment]
What about Javascript version. I remember I got a message of a Javascript update when browsing some days ago.

**Comment by tbfleming** [comment]
That's tied to the browser version.

**Comment by jorgerobles** [comment]
Posted branch without menuitem https://github.com/LaserWeb/LaserWeb4/tree/no_context_menu
please checkout and test your faulty ones :smile:

**Comment by cprezzi** [comment]
I think I was using Firfox. Probably they do update the js engine saparately.

**Comment by cojarbi** [comment]
Not working on:

- Windows 10 Pro 10.0.14393 Build 14393
- Version 58.0.3029.110 (64-bit)
- Node 6.10.0
- Intel Iris 540 16MB

**Comment by cojarbi** [comment]
If ive done the process correctly, im still having the same issue with that branch :(

**Comment by jorgerobles** [comment]
Then go reverting 1 week then 2 :(

**Comment by tbfleming** [comment]
@jorgerobles instead of posting branches, maybe suggest specific hash revisions for @cojarbi to try.

**Comment by cojarbi** [comment]
I will be reverting commits by a week range to pin down where this started

**Comment by jorgerobles** [comment]
Yes, that branch was only a longshot. Will delete

**Comment by cojarbi** [comment]
I just noticed that the problem is seen while changing between same machine type operations from a normal cut to a outside/inside.

If I go from any laser operation to any mill operation it works as expected. 

If I go from Laser cut to laser cut inside, it does not refresh. The same with milking ops.

I continue to looking for the origin

**Comment by tbfleming** [comment]
> If I go from Laser cut to laser cut inside, it does not refresh. The same with milking ops.

Reproduced this for laser. I don't have any CNC cows to test the milking ops.

**Comment by jorgerobles** [comment]
LOL. so, you have reproduced the error?

**Comment by tbfleming** [comment]
yes. debugging it now.

**Comment by jorgerobles** [comment]
@tbfleming Found!.. and fixed! (not commited)

**Comment by jorgerobles** [comment]
operation:534, componentDidUpdate is not the place to put the code.. should be inside componentWillReceiveProps
