### ISSUE TITLE
Laserweb 0.4.0 (alpha) in title bar

### ISSUE THREAD

**Issue by domenic-d** [LaserWeb/LaserWeb4#328]
Laserweb v0.4.0 (alpha) appears momentarily in the titlebar whenever LW is started. This is quickly replaced with the current version.

Is there any way to prevent this from happening?

Using v732 on Mac and Win versions.

**Comment by cprezzi** [comment]
That also bothers me.
@jorgerobles Could you just strip the version number out of the static html content, so that no version is displayed until the update with the correct version?

**Comment by jorgerobles** [comment]
Already done :) https://github.com/LaserWeb/LaserWeb4/commit/e8d807e68d996c5267e659b5ee9e25bd1c564b14
