### ISSUE TITLE
Sub-Titles on settings

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#330]
Could we add sub-titles to the section inside each category so its better defined plus easier to explain in the Docs or while giving support

Example:
<img width="337" alt="screen shot 2017-06-01 at 7 30 11 am" src="https://cloud.githubusercontent.com/assets/16444438/26680084/87b6546e-469d-11e7-820d-25dac0ec54c0.png">

**Comment by cprezzi** [comment]
I would move the origin shift fields between "machine height" and "beam diameter". 
@jorgerobles what do you think?
