### ISSUE TITLE
lw.svg-parser mishandles group transforms

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#332]
[group transform.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/1049850/group.transform.svg.txt)

Inkscape:
![image](https://cloud.githubusercontent.com/assets/418464/26756360/d6f5532c-486e-11e7-8d84-178badfffe6d.png)

https://lautr3k.github.io/lw.svg-parser/dist/example/  :

![image](https://cloud.githubusercontent.com/assets/418464/26756368/fb1b9496-486e-11e7-8fca-9a068c304be9.png)

LW4:

![image](https://cloud.githubusercontent.com/assets/418464/26756374/1b3deb34-486f-11e7-81f6-96b13b5898a7.png)

**Comment by tbfleming** [comment]
I bypassed lw.svg-parser's transform handling. src/reducers/document.js now does it instead.

rotate branch only. dev-es6 is still broken.

**Comment by jorgerobles** [comment]
As merged, fixed.
