### ISSUE TITLE
Add rotation arrows

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#335]
I know you guys just finished this but maybe the following or similar could be added either 45 or 90 degrees interval?
<img width="639" alt="screen shot 2017-06-08 at 7 45 01 am" src="https://user-images.githubusercontent.com/16444438/26929301-ba34dc90-4c1e-11e7-914b-72393617a596.png">

**Comment by tbfleming** [comment]
I'm thinking it might be cleaner than what I currently have to do this: Changing the value won't immediately rotate. Instead it will change the increment that the arrows rotate the doc. It could default to 45.

**Comment by jorgerobles** [comment]
![image](https://user-images.githubusercontent.com/1706080/26948453-afaf0aca-4c96-11e7-96d9-c2311033b314.png)
