### ISSUE TITLE
Negativ Workingarea in Settings Machine

### ISSUE THREAD

**Issue by jtronics** [LaserWeb/LaserWeb4#337]
Hello,
I'm using Laserweb4, Smothieware and a K40 Laser.
It is not possible to configure the workingarea, so that the coord is in the top left corner.
So Machine Height is negative -200mm

Thanks Martin

**Comment by cojarbi** [comment]
Please this kind of support questions are to be posted in our G+ community

https://plus.google.com/communities/115879488566665599508
