### ISSUE TITLE
Delete Key deletes document during position editiong, instead of digit

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#340]
@jorgerobles I found a bug: When editing the position/size of an object, pressing the delete key deletes the whole document intead of the digit behind the cursor. The document tree is not updatet (document still visible but not usable).

**Comment by jorgerobles** [comment]
F**k

**Comment by jorgerobles** [comment]
Quick fix.. ctrl+delete?

**Comment by cprezzi** [comment]
Easy, but needs to be told to people that already use del to delete a document. ;)

**Comment by jorgerobles** [comment]
Yep it's on release page.  Will document ASAP

**Comment by cojarbi** [comment]
Delete key on the mac not working at all to delete a path from the grid. Neither any other key combinations with delete key works

**Comment by jorgerobles** [comment]
@cojarbi mouse pointer should be over workspace. (not over floating controls)- I've tested and works ok.

**Comment by cojarbi** [comment]
@jorgerobles got it to work but its not straightforward on the mac since the alt key is available by pressing the fn key , so its fn+alt+delete

**Comment by jorgerobles** [comment]
Key 'option' is not working?

**Comment by cojarbi** [comment]
nope

**Comment by jorgerobles** [comment]
O_O
https://developer.mozilla.org/es/docs/Web/API/KeyboardEvent/keyCode
option should be behave as alt :|

**Comment by jorgerobles** [comment]
@cojarbi  use Command+Backspace :D

**Comment by cojarbi** [comment]
@jorgerobles on Mac laptops there is no other key besides delete, which is the same as backspace
