### ISSUE TITLE
No supported firmware detected.

### ISSUE THREAD

**Issue by DanielArgil** [LaserWeb/LaserWeb4#344]
Hi @cprezzi first of all I apologize for my English, I am trying to use LaserWeb4 but I always receive this message: No supported firmware detected. Closing port COM4, I can connect to Universal GCodeSender even though I get the following message: Active State: Alarm, and after entering $X everything works fine. 

The message from Arduino is as follows:
Grbl 1.1e ['$' for help]
[MSG: Check Limits]
[MSG: '$ H' | '$ X' to unlock]

**Comment by cprezzi** [comment]
Please ask your questions in our G+ community https://plus.google.com/u/0/communities/115879488566665599508
We use git issues only for known bugs.
