### ISSUE TITLE
AI SVG text not showing up correctly

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#351]
Could someone verify why the letters ( converted to outlines ) dont show up correctly?
Made on AI CC 2017
[LaserWeb Logo copy.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/1086607/LaserWeb.Logo.copy.svg.txt)
<img width="383" alt="screen shot 2017-06-19 at 6 54 45 pm" src="https://user-images.githubusercontent.com/16444438/27310567-cb9be73e-5520-11e7-8247-29994d442bd9.png">

**Comment by cojarbi** [comment]
Update: its seems its not recognizing the fill. If i add a stroke to the letter then it shows up

**Comment by tbfleming** [comment]
The SVG doesn't have any fill or stroke set.

**Comment by cojarbi** [comment]
In AI it does have a fill

⁣Ariel Yahni​

**Comment by jorgerobles** [comment]
On export, use representation attributes instead css. Black fills are not
correctly exported by ai

**Comment by cojarbi** [comment]
@jorgerobles not working for me. I think i have tried all the possible combinations. 

This other file was just made in inkscape, text converted to path and added fill / stroke. LW does not load it at all and says " its not your fault " which  i like
[drawing.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/1088031/drawing.svg.txt)

**Comment by tbfleming** [comment]
I just pushed a fix to the Inkscape problem.

**Comment by tbfleming** [comment]
It had code to handle the case where the fill and stroke were missing. It created a transparency effect to indicate the problem, without annoying people who intentionally made things invisible. The recent frame buffer caching system caused it to be too transparent. fixed.

**Comment by cojarbi** [comment]
Woking perfectly. Thanks @tbfleming
