### ISSUE TITLE
could not open a svg file

### ISSUE THREAD

**Issue by lollotek** [LaserWeb/LaserWeb4#355]
Hi,
I think I found a bug, when I try to open this file i get an error.
I'm secure it was working using laserweb3

Branch es6-dev:
```
index.js:sourcemap:60266 Uncaught (in promise) TypeError: this.node.getCTM is not a function
    at Element.elproto.transform (index.js:sourcemap:60266)
    at addChildren (index.js:sourcemap:42410)
    at loadSvg (index.js:sourcemap:42494)
    at documentsLoad (index.js:sourcemap:42609)
    at Object.reducer [as default] (index.js:sourcemap:41860)
    at hot (index.js:sourcemap:16550)
    at index.js:sourcemap:41456
    at dispatch (index.js:sourcemap:38819)
    at index.js:sourcemap:41387
    at index.js:sourcemap:41542
```

[testsvg.zip](https://github.com/LaserWeb/LaserWeb4/files/1103505/testsvg.zip)

**Comment by cojarbi** [comment]
It's does not open for me either unless I open it in inkscape and do  Object to Path

**Comment by lollotek** [comment]
Ok, FYI using LaserWeb3/master it loads without inkscape editing.
Thanks for the support.
![testsvg](https://user-images.githubusercontent.com/3391893/27561480-7fd38ee4-5ac8-11e7-8833-63728baac9f9.jpg)

**Comment by jorgerobles** [comment]
Seems some crap from Snap library. https://github.com/svgdotjs/svg.js/issues/385 :(

**Comment by tbfleming** [comment]
This file is defective. Not even Chrome, which is pretty permissive, can display it. It starts with:

```
<svg width="400mm" height="300mm" viewBox="0 0 400 300">
```

It should be:

```
<svg xmlns="http://www.w3.org/2000/svg" width="400mm" height="300mm" viewBox="0 0 400 300">
```

Snap builds on Chrome's SVG handling; it breaks when Chrome breaks.

**Comment by tbfleming** [comment]
@jorgerobles to test for corruption like this, drag the file into an empty Chrome tab.

**Comment by jorgerobles** [comment]
Yes, I overlooked that. :/

**Comment by lollotek** [comment]
I added xmlns attrib to my generator, and import works.
thanks
