### ISSUE TITLE
underlines blue dash items in CAM: What for? 

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#357]
Why are some items in CAM underlined in Blue?

For example? 

![underlines](https://user-images.githubusercontent.com/7695323/27588740-744ebdec-5b49-11e7-8b52-bb2f97f5260d.PNG)

**Comment by jorgerobles** [comment]
Right click and get a surprise ;)

**Comment by openhardwarecoza** [comment]
Ok. I'll follow that up with another issue, more general (;

**Comment by jorgerobles** [comment]
:) it comes from #345 and #308, but yes. should have a context menu icon on hover
