### ISSUE TITLE
debug section of About: Line breaks (;

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#361]
![line breaks](https://user-images.githubusercontent.com/7695323/27591342-aae1dada-5b51-11e7-8712-5a8dc98896cd.PNG)

Some ```<br>``` or table action would clean that up

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/LaserWeb4/commit/87eb7a6b9d6113ab8bc1d1b680f22b171dde11fd

**Comment by openhardwarecoza** [comment]
Thanks (;
