### ISSUE TITLE
UI - Gamepad enhancement

### ISSUE THREAD

**Issue by ghost** [LaserWeb/LaserWeb4#364]
Continuation from #359 :  GamePad

I can jog XY just fine, but two suggestions:

1: Step size modifier: Seems to always jog 1mm:  Perhaps holding down one of the buttons on the right side of gamepad, could act as a modifier for 0.1?  Especially on milling, Z jogs are almost always 0.1.  Maybe another button for x10?  Or a button that cycles through 0.1, 1, 10, 1, 0.1 and displays it onscreen? 

2: Cant seem to jog Z yet? 

and 

3:  Possible UI to remap own controller. i have a Buffalo NES pad, so my right hand side buttons are in a straight grid. PS style controller they are in a + grid. So probably no one size fits all.

**Comment by openhardwarecoza** [comment]
Gamepad mapping demo: http://charliejwalter.net/gamepad/demos/main/  (SVG of gamepad with inputs overlayed? )

**Comment by openhardwarecoza** [comment]
Second note, just tried my USB snes joystick, but forgot to unplug the NES. Realised we may need a select box like we have for Webcam, to pick Gamepad

**Comment by jorgerobles** [comment]
Freezing feature for now. No reports of usage.
