### ISSUE TITLE
Laserweb CPU usage

### ISSUE THREAD

**Issue by eomizrak** [LaserWeb/LaserWeb4#366]
Laserweb using %30-40 of CPU power while It is idle on Mac.

**Comment by cojarbi** [comment]
Im getting between 15 to 30

**Comment by eomizrak** [comment]
I am using macbook pro 13' 2016. Is it normal to consume power like %15 or %40 when the program doing nothing. Even if you didn't open any document on the program.

**Comment by openhardwarecoza** [comment]
Yes, even he nothing is going on,  webgl runs animation loop to keep viewer displayed

**Comment by jorgerobles** [comment]
You could enable settinga application display cache. It's a greedy cache
only draws when called

**Comment by openhardwarecoza** [comment]
@jorgerobles - that works good for me.  Just sometimes a little bothersome to have to click on viewer for force a reanimation. Perhaps we can add flags to things like onMouseUp of Simulator slider, so when its done, it calls an anitmate()  to refresh the viewer?  

In Chilipeppr there is a lot of code to deal with pausing the animation unless needing an update

**Comment by jorgerobles** [comment]
Added SIMtime to display cache invalidation
