### ISSUE TITLE
SVG embedded image displaced vertically

### ISSUE THREAD

**Issue by allstar87** [LaserWeb/LaserWeb4#367]
Attempting to create an object which is a raster image centered on a vector cut.  Created in Inkscape v 0.91. Created the following SVG:
[basicsaturn5.zip](https://github.com/LaserWeb/LaserWeb4/files/1116111/basicsaturn5.zip)

The blue rectangle and the image of Saturn both have their lower left corners on the origin.

When imported into LaserWeb V4.0.731, the embedded image is shifted vertically 3mm, as seen here:
[laserweb_inkscape_screenshot.zip](https://github.com/LaserWeb/LaserWeb4/files/1116135/laserweb_inkscape_screenshot.zip)

[Laserweb-Workspace.json.txt](https://github.com/LaserWeb/LaserWeb4/files/1116114/Laserweb-Workspace.json.txt)

Only Laserweb shifts the image like this, opening the SVG in other software displays the image correctly.

**Comment by tbfleming** [comment]
The Laserweb-Workspace.json.txt file above is empty.

Here's what happens when I load basicsaturn5.svg into LW:

![image](https://user-images.githubusercontent.com/418464/27749063-ed99147e-5d9f-11e7-8ab7-99ac1104a0ba.png)

**Comment by allstar87** [comment]
That's what I'm trying to achieve, and failing.  I'll attempt to reupload the workspace json.

**Comment by tbfleming** [comment]
Very odd. Go ahead.

**Comment by tbfleming** [comment]
Sounds like you might be getting file system corruption.

**Comment by allstar87** [comment]
[Laserweb-Workspace.json.zip](https://github.com/LaserWeb/LaserWeb4/files/1116200/Laserweb-Workspace.json.zip)

**Comment by tbfleming** [comment]
I can tell from the .json that you're on an older LW version. I've done major changes to SVG import since then.

**Comment by allstar87** [comment]
From the About section:  Frontend 4.0.731, backend 4.0.68.  I'll go fetch the most recent appimage I can find.

**Comment by allstar87** [comment]
That got it.

**Comment by jorgerobles** [comment]
Still an issue? if not please close
