### ISSUE TITLE
OSX - permission denied on 'logfile.txt'

### ISSUE THREAD

**Issue by gerwinbrunner** [LaserWeb/LaserWeb4#369]
I'm running LaserWeb 4.0.735 on OSX.
When I enable the log level and set it to 3 then I get the following error message:
<img width="497" alt="screen shot 2017-07-03 at 19 53 52" src="https://user-images.githubusercontent.com/75502/27803524-34089466-602a-11e7-92a7-9f5ae0c0cda6.png">

It seems that this is an issue with rights on OSX.

Here is how I do this:
```
export LOG_LEVEL=3
open LaserWeb.app
```

**Comment by gerwinbrunner** [comment]
I think the problem is this call here:
https://github.com/LaserWeb/lw.comm-server/blob/41f0844fe40e69f20c6373ab904c0e006e2362dc/server.js#L2797

The path should somehow be passed in (or set for this library) by using a platform specific path like `app.getPath('userData')`
The electron api I'm talking about is here:
https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by jorgerobles** [comment]
Yes, I've have the same issue.
Could you lend us a hand to fix it? Thanks!

**Comment by jorgerobles** [comment]
Moved to lw.comm-server

**Comment by jorgerobles** [comment]
BTW. the patch works ok

`logFile = fs.createWriteStream(path.join(electronApp.getPath('userData'),"logfile.log"));`
