### ISSUE TITLE
Release v4.0.735-109 does not have an OSX .dmg file

### ISSUE THREAD

**Issue by gerwinbrunner** [LaserWeb/LaserWeb4#370]
Hi, 

just wanted to let you know that for release `v4.0.735-109` the OSX .dmg file is missing.
See: https://github.com/LaserWeb/LaserWeb4-Binaries/releases/tag/v4.0.735-109

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/LaserWeb4-Binaries/releases/tag/v4.0.735-109
