### ISSUE TITLE
Material database operation not checked against document type

### ISSUE THREAD

**Issue by domenic-d** [LaserWeb/LaserWeb4#371]
Any material database preset can be applied to any document type, whether it is legal or not.
For instance a raster engraving preset can be applied to a vector document.

Tested on OSX 4.0.734

**Comment by jorgerobles** [comment]
Done now disables incompatible presets on picking.

**Comment by domenic-d** [comment]
Thx Jorge.

**Comment by jorgerobles** [comment]
Fixed up last fix ;P

https://plus.google.com/117472235206728939420/posts/SWSJLv7fxSd
