### ISSUE TITLE
High CPU & RAM consumption

### ISSUE THREAD

**Issue by msurguy** [LaserWeb/LaserWeb4#377]
Hello! 

I am using the latest version of LaserWeb and am getting very high CPU / RAM consumption on both, Electron and hosted versions of the program. I have a 2.5Ghz quad core i5 and 16GB of RAM, with no other programs running besides LaserWeb and seems like there is a memory leak or some event listeners that are maxing out the CPU cycles.

Fun fact, this is really helpful if you want to discharge your laptop's battery in less than 10 minutes!

**Comment by jorgerobles** [comment]
@tbfleming 
---
For reference:
- https://addyosmani.com/blog/taming-the-unicorn-easing-javascript-memory-profiling-in-devtools/

**Comment by tbfleming** [comment]
@jorgerobles yep, I often use those tools. Problem is I usually develop on a high-TDP desktop which doesn't have those symptoms.

**Comment by jorgerobles** [comment]
Me too 😄

**Comment by tbfleming** [comment]
e.g. I have the .exe version up now. It consumes ~0.5% while idle.

**Comment by tbfleming** [comment]
Turning on the Display Cache drops it to ~0.1%.

**Comment by jorgerobles** [comment]
@msurguy Could we have your computer profile and workspace.json? Any data you can provide us to debug? Do you have the camera installed?

**Comment by tbfleming** [comment]
@msurguy things which may affect this:
* CPU model
* GPU model, if you have a discreet one
* OS, version, and 32-bit or 64-bit

Most reports I've seen so far with this problem are with old hardware or old OS. A 2.5 GHz CPU produced within the past couple years behaves very differently than a 2.5 GHz CPU produced 7 or 8 years ago.

**Comment by msurguy** [comment]
@jorgerobles attached is a screenshot of my Mac profile: 

<img width="479" alt="screen shot 2017-07-14 at 10 18 19 am" src="https://user-images.githubusercontent.com/585833/28222789-ca46370c-687d-11e7-893b-7fa7ec7244b8.png">

Could be that this issue is only on Chrome Mac. 

The issue appears even when I don't do anything other than open the app and let it sit idle.

**Comment by jorgerobles** [comment]
My desktop is similar :/

![image](https://user-images.githubusercontent.com/1706080/28226724-74275a90-68d7-11e7-9745-94aea4144935.png)

**Comment by jorgerobles** [comment]
try chrome://gpu/ to detect problems

![image](https://user-images.githubusercontent.com/1706080/28239886-97b04cf2-6976-11e7-9ff8-3b8fee011c67.png)

![image](https://user-images.githubusercontent.com/1706080/28239891-aa44f49e-6976-11e7-8adb-798c0543f54d.png)

**Comment by msurguy** [comment]
Thanks @jorgerobles! Tried to check for GPU problems and none were found. 

What I did discover is that this problem seems to appear only sometimes, and only when I have an external monitor plugged into my MacBook. When the monitor is unplugged, the CPU load is very minimal!

**Comment by jorgerobles** [comment]
Glad to hear. Unfortunately due the randomness of the issue cannot offer any further solution. Closi g by now.

**Comment by tbfleming** [comment]
I suspect this might be happening: adding an external monitor increases the amount of video ram dedicated to running the display. This leaves less video ram for the GPU to use for handling LW's requests. The CPU is forced to take up the slack.
