### ISSUE TITLE
LaserWeb crashes when minimum grid minor spacing is set to 0

### ISSUE THREAD

**Issue by wdehaas** [LaserWeb/LaserWeb4#379]
I'm using LaserWeb4 Mac OSX version.

I tried to set the minimum grid minor spacing and major size to 0 and then the program crashed. I did this under: 

Settings: Application \ Grid

Now when I try to start the program again I get a blank screen. 

Edit: I installed an old version of LaserWeb which is called lw.comm-server. Then I could find the Application Support files. I deleted them and got this version to work. Also latest version is working again, though the Application files are not called lw.comm-server I think.

Thanks in advance for the reply.

greetings,

Waldemar

**Comment by jorgerobles** [comment]
~/Library/Application\ Support/lw.comm-server/Local\ Storage

**Comment by jorgerobles** [comment]
Before deleting, please attach .localstorage files to this issue to debug

**Comment by wdehaas** [comment]
Hi,

Thanks for your reply. As far I can see I cannot find the /lw.comm-server directory under Application Support. Are you sure this is the right location for it?

Thanks for your reply.

**Comment by jorgerobles** [comment]
On mine is :|

**Comment by kreaziku** [comment]
this problem is happen to me too :( blank
