### ISSUE TITLE
Operation processing & Filtering

### ISSUE THREAD

**Issue by domenic-d** [LaserWeb/LaserWeb4#385]
@tbfleming 
If a very complex vector file is opened in Laserweb, would there be any advantage to using filters to process sections of the file in multiple operations, rather than in one operation?

In other words, is there any computational advantage in creating multiple operations but limiting the region for each?

![screen shot 2017-07-19 at 11 25 08 am](https://user-images.githubusercontent.com/27034222/28346566-1bf4099e-6c75-11e7-88a6-dfc6cb333465.png)

**Comment by cprezzi** [comment]
I'm not absolutely sure, but it could be faster to have multiple operations because multi threading works better then (depenting on your CPU and thread setting).

**Comment by jorgerobles** [comment]
Yes. I think I mentioned in other issue, current threading system works on
multiple operations.

**Comment by tbfleming** [comment]
Probably need to try it and see what happens.
