### ISSUE TITLE
"Unknown Error Code 87"  While connected to C3D via LW4 will disconnect requiring reconnection.

### ISSUE THREAD

**Issue by Bama-Breeze** [LaserWeb/LaserWeb4#390]
While connected to C3D board via USB with LW4 connectivity will disconnect and an error code:  "Unknown Error Code 87" appears.   Repetitive issue.  I can reconnect and in approximately 15-20 minutes of idle time it will loose connection again.  No difficulty in reconnecting, but in a few minutes I loose connection again.  No projects were being executed at anytime during connectivity issue.  Prior to disconnect I had jog capability with Y, X, Z, and A (rotary) axis and webcam.   There are NO power savers or other known issues or applications that would terminate connection.  I further validated the only USB devices connected upon successful connection of LW4 were the C3D board, a mouse, a keyboard, and the webcam.  Windows device manager shows no device issues.  All USB ports functioning.  Upon loosing connectivity in LW4 I still have full access via Windows Explorer to open the C3D board's micro SD card.  

Running Windows 10 and lastest version of LW4.  Have switched between USB 3.0 and 2.0 with no difference.  Successful connection via COMMS tab and shortly disconnect.    Have changed USB cable with no difference.

Thanking you in advance!

Photograph to follow.
![error 87 lw4](https://user-images.githubusercontent.com/28910156/28989625-33883606-793c-11e7-87a9-be7632dc5168.jpg)

**Comment by domenic-d** [comment]
@Bama-Breeze Can you please try to emulate this problem without Laserweb running or connected?
We have experienced similar issues with smoothieboards even when laserweb has not been running.

Can you please let us know the brand of laptop you are using? We have found this offers most often on Dell Inspiron machines.

**Comment by Bama-Breeze** [comment]
Domenic:

My computer is a Inspiron Desktop 3668 purchased a month ago.  All if my desktop and laptop computers are Della.  All running Windows 10.  

Upon an effort to reproduce the issue I do not note replicated transient connectivity issues.  With Laserweb4 powered off and nothing more that the USB cable connected to the C3D and observed through Windows Explorer I did not observe instability and could see the SD card.  I tested the board with the transfer of a large 11mb pdf file from desktop to the board's SD card.  The 11mb transferred and was viewable without difficulty.

It may be a WASP, but I noted upon research on most recent Windows 10 updates that USB ports were exhibiting similar indiscriminate disconnects.  The fix was to go into the Device Manager and independently disable or deselect "Allow This Device To Deselect To Save Power" for each USB ports.  Simply turning off all power management simply through the Power Saving scheme was not adequate. 

It's beyond my skill level, but as I understand the issue they are describing the USB ports are going into a suspended state in power savings if it appeared a USB port's power source was not necessary in an idle state.  This again maybe little more than a WASP; however, one could surmise it as applicable since each time LW4 connectivity was in an idle state after a period of testing functionality of jog control of Y, X, Z, and A rotary.  The only device was the webcam, mouse, and keyboard.  As specified I observed no connectivity issues.  I monitored the webcam via an independent application.  Again I could open and execute a file in the on board AS care, i.e., I could open and view the 11mb pdf file I had pasted.

I will disable all power saving options on each USB ports later today in Windows 10 Device Manager.

If I have failed to follow your instructions please advise.  My doctorate is not in computer or data science.  While I possess a working knowledge I am most definitely not of the intellectual expertise as you and your colleagues.  So be gentle. 😊

I await your further thoughts, instruction, or chastising if applicable.

**Comment by Bama-Breeze** [comment]
Domenic:

My computer is a Inspiron Desktop 3668 purchased a month ago.  All if my desktop and laptop computers are Della.  All running Windows 10.  

Upon an effort to reproduce the issue I do not note replicated transient connectivity issues.  With Laserweb4 powered off and nothing more that the USB cable connected to the C3D and observed through Windows Explorer I did not observe instability and could see the SD card.  I tested the board with the transfer of a large 11mb pdf file from desktop to the board's SD card.  The 11mb transferred and was viewable without difficulty.

It may be a WASP, but I noted upon research on most recent Windows 10 updates that USB ports were exhibiting similar indiscriminate disconnects.  The fix was to go into the Device Manager and independently disable or deselect "Allow This Device To Deselect To Save Power" for each USB ports.  Simply turning off all power management simply through the Power Saving scheme was not adequate. 

It's beyond my skill level, but as I understand the issue they are describing the USB ports are going into a suspended state in power savings if it appeared a USB port's power source was not necessary in an idle state.  This again maybe little more than a WASP; however, one could surmise it as applicable since each time LW4 connectivity was in an idle state after a period of testing functionality of jog control of Y, X, Z, and A rotary.  The only device was the webcam, mouse, and keyboard.  As specified I observed no connectivity issues.  I monitored the webcam via an independent application.  Again I could open and execute a file in the on board AS care, i.e., I could open and view the 11mb pdf file I had pasted.

I will disable all power saving options on each USB ports later today in Windows 10 Device Manager.

If I have failed to follow your instructions please advise.  My doctorate is not in computer or data science.  While I possess a working knowledge I am most definitely not of the intellectual expertise as you and your colleagues.  So be gentle. 😊

I await your further thoughts, instruction, or chastising if applicable.

-------- Original message --------From: Domenic Di Giorgio <notifications@github.com> Date: 8/5/17  2:41 AM  (GMT-06:00) To: LaserWeb/LaserWeb4 <LaserWeb4@noreply.github.com> Cc: Bama-Breeze <montys-woodworking@att.net>, Mention <mention@noreply.github.com> Subject: Re: [LaserWeb/LaserWeb4] "Unknown Error Code 87" While connected to
  C3D via LW4 will disconnect requiring reconnection. (#390) 
@Bama-Breeze Can you please try to emulate this problem without Laserweb running or connected?

We have experienced similar issues with smoothieboards even when laserweb has not been running.
Can you please let us know the brand of laptop you are using? We have found this offers most often on Dell Inspiron machines.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LaserWeb/LaserWeb4","title":"LaserWeb/LaserWeb4","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LaserWeb/LaserWeb4"}},"updates":{"snippets":[{"icon":"PERSON","message":"@domenic-d in #390: @Bama-Breeze Can you please try to emulate this problem without Laserweb running or connected?\r\nWe have experienced similar issues with smoothieboards even when laserweb has not been running.\r\n\r\nCan you please let us know the brand of laptop you are using? We have found this offers most often on Dell Inspiron machines.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/LaserWeb/LaserWeb4/issues/390#issuecomment-320424640"}}}

**Comment by domenic-d** [comment]
@Bama-Breeze we have also experimented with the power saving features etc, with no improvement.

This issue has been previously discussed with the lw.comms developer and laserweb lead, without any clear determination as to whether LW could be causing this. We since moved on and started looking elsewhere for a reason. The one link we have found is that it is related to Dell Inspiron computers.

I would recommend you raise this issue on the C3D forum, as I suspect it is not related to Laserweb.

Please share any findings you have and perhaps we can use them to find an answer to this.

**Comment by Bama-Breeze** [comment]
Has this been an issue with every LaserWeb build?  Concerning since Dell computers are one of the leading consumer computer manufacturers by principal and other consumer brands.  

I will share with C3D.  I thank you, but somewhat disappointed in a reply indicative of an ongoing issue unknown to users.

**Comment by tbfleming** [comment]
@Bama-Breeze it's only been within the last month or so that @domenic-d spotted the pattern. It doesn't appear to be all Dells, just some. It may not be just LW, it may be all apps which talk to Smoothieware when running on those Dells. We just don't know yet because we don't have enough data to go on and the lw.comms developer and the Smoothe developers don't have machines with that problem to debug with.

**Comment by tbfleming** [comment]
A point of comparison:
* nVidia is a leading GPU maker
* Philips is a leading monitor maker
* It took 2 years before nVidia fixed driver bugs that caused my Philips 4K monitor to:
  * glitch every couple hours
  * randomly stop working at 60 Hz and fall back to 30 Hz, which strains my eyes
* Intel had similar bugs with this monitor

**Comment by cprezzi** [comment]
Link to the post in the Cohesion3d G+ community (with my answers): https://plus.google.com/u/0/117720577851752736927/posts/jR3nBCbQCsb

This is what we know so far:
- Bad quality or long USB cables could cause it.
- Insufficent voltage on USB port could cause it (if board MCU is not powered from a separate source).
- USB 3.0 can cause it. Use USB 2.0 ports only.
- Sometimes just changing the USB port did help.
- Smoothieware can cause it, because of dual connection over the same USB port (CDC & MSD). Disable MSD (SD card interface) to resolv that or try replace Smoothieware with grbl-LPC.
- Mains power spikes can cause it (like light, air-condition or other equipement switching on/off)

**Comment by openhardwarecoza** [comment]
The number part of the node-serialport is only reported by us. The error code is from the O/S:

87: https://social.msdn.microsoft.com/Forums/en-US/ad18e2a1-c25b-43e7-8b8d-019073db2c6f/why-setcommstate-error-87-?forum=vssmartdevicesnative

**Comment by Bama-Breeze** [comment]
Gentleman if I may please accept my brief commentary.  As stated previously I have little more than "walking sense" in the technology you discuss herein.  My education resides elsewhere.  But, I so wish I could comprehend your discussion thread.  An academician in heakthcare for 40+ years I find your process extrodinarily  fascinating.  A process we would have called a "root cause analysis".  I'll step back into the shadows while continuing to enjoy your process.  Though I know not the subject matter I do appreciate the intellect.  Thank you for permitting my audience. -  My best regards to all!

**Comment by Bama-Breeze** [comment]
Forgive my typos.

**Comment by LdyMox** [comment]
I had this exact same problem with Windows 10 and a Dell  XPS 8910 with the Cohesion3D Mini.  When I switched over to grbl-lpc (https://cohesion3d.freshdesk.com/support/solutions/articles/5000740838-grbl-lpc-for-cohesion3d-mini) I haven't had the issue since, granted it's only been about 4 days but I did lots of projects over the weekend.   After you install grbl in LaserWeb for the machine settings you need add M4 to the start gcode, M5 to the end Gcode and Home to $H and PWM scale from 1 to 1000.

**Comment by Bama-Breeze** [comment]
Thank you LdyMox.  How goes the experience with your switched over to grbl-lpc on your C3D?

**Comment by LdyMox** [comment]
It has been 1000 times better since moving over to grbl-lpc from Smoothie on my C3D
