### ISSUE TITLE
Unable to clear 'Hold' after 'Abort'

### ISSUE THREAD

**Issue by domenic-d** [LaserWeb/LaserWeb4#396]
Frontend: 4.0.989
Backend 4.0.115
Smoothie Firmware: Latest CNC edge-049af91

If a job is paused (Hold displayed) and abort is pressed, it is not possible to clear the 'hold' without restarting the controller.

**Comment by cprezzi** [comment]
Ok, I'll check that...

**Comment by cprezzi** [comment]
The problem is caused by smoothieware, which goes to alarm state on each **ctrl-x** even when not needed (no job running and position save). Grbl does handle that better and goes only to alarm when a move was interrupted.

**Comment by domenic-d** [comment]
@cprezzi Are you able to clear that alarm?

**Comment by cprezzi** [comment]
Yes, if I press reset alarm (after pause and abort), the alarm goes away. 
Doesn't that work on your machine?

**Comment by domenic-d** [comment]
@cprezzi No.

**Comment by cprezzi** [comment]
Ok. I was able to replicate the problem with Smoothieware **firmware-cnc-latest.bin**. It works perfect with **firmware-cnc.bin**. Something must have changed on smoothieware side.

**Comment by domenic-d** [comment]
I have also tested it on a default smoothie board and it is happening as well. I wanted to ensure it was not specifically our board causing it.

**Comment by cprezzi** [comment]
Which Smoothieware version did you use? As I said, I only get the problem with firmware-cnc-latest.bin, but not with firmware-cnc.bin. I was testing with the Cohesion3D Remix.

**Comment by domenic-d** [comment]
@cprezzi I used the latest smoothiware CNC version.
After the issues we were having with the older non-CNC firmware's compatibility with LW, we now compile our config into the firmware and hence are always using the latest version.

Can you provide any specific details you need to resolve this so we can perhaps get Jim or Arthur involved to see what has been changed?

**Comment by cprezzi** [comment]
I think you compile the same version as the so called **firmware-cnc-latest.bin** on the smoothie page. Can you please try the **firmware-cnc.bin** from https://github.com/Smoothieware/Smoothieware/tree/edge/FirmwareBin, just to confirm my test?

**Comment by cprezzi** [comment]
If I know what exactly changed on Smoothieware side (related to hold, resume, ctrl-x and homing) I can adjust my state handling. 
The problem you get is that LW thinks it's still in pause after the abort.

**Comment by cprezzi** [comment]
The only concern I have is, that two different behaviours would be needed for users with latest or older firmware.

**Comment by domenic-d** [comment]
I have tested it with firmware-cnc.bin and can confirm this works correctly as you have observed.
Pause followed by two aborts places the machine in an 'idle' state correctly. Jobs can then be restarted as expected.

I understand your concern about having the two behaviours. At the end of the day, laserweb should be able to support the 'latest' firmware, just like we experienced recently with it not supporting the older firmware version we were using. This is the same situation with smoothiware users needing to update a while back so that they could use laserweb at all.

**Comment by cprezzi** [comment]
For me, latest is something like beta? I always use the normal (not latest) version, because I've read somewhare that lastest could be less stable.

Did you find out what changed in Smoothieware between the two versions?

**Comment by domenic-d** [comment]
@cprezzi I didn't pursue what changes because you mentioned you knew exactly what changed.

**Comment by domenic-d** [comment]
@wolfmanjm Can you please advise whether we should be working with the 'latest' version of the CNC firmware or is this 'beta', as Claudio is asking?

There has been a change made to the 'latest' firmware which has broken the way Laserweb handles pause/resume/abort.

There is uncertainty as to whether LW should be revise to accomodate this change or users should be restricted to the older version of the firmware.

**Comment by wolfmanjm** [comment]
I'll look into it.The old frmware ignored hold !/~, the latest firmware will go into a hold state although not pause immediately.

It is possible that if you abort (control X) while it is in hold it will not clear the hold anymore. If so I will fix it so that an abort will clear any hold.

**Comment by domenic-d** [comment]
@wolfmanjm Thanks for the info. That certainly appears to what is going on. Please let us know when we can test your fix.

On a side note, we usually run our segments at 0 or 0.1. With these settings, the delay in pausing is not very long and acceptable in most circumstances.

**Comment by wolfmanjm** [comment]
I presume by ABORT you mean KILL (sending control X)? Abort in smoothie is a different thing and stops a job running from the internal SDCard.

**Comment by wolfmanjm** [comment]
Looking at the code it should work correctly. Feed hold is cleared regardless of being in HALT mode.
Are you expecting a control X to also clear HOLD? if so that currently does not happen you need to send ~ to clear the HOLD even when in HALT mode.
This is with the latest code, not sure if the prebuilt stuff has this HOLD in it at all.

**Comment by wolfmanjm** [comment]
Confirmed it works as I expect it to work..
```
?<Idle|MPos:0.0000,0.0000,0.0000|WPos:0.0000,0.0000,0.0000|F:4000.0000>
!
ok
?<Hold|MPos:0.0000,0.0000,0.0000|WPos:0.0000,0.0000,0.0000|F:4000.0000>
ALARM: Abort during cycle
~
ok
?<Alarm|MPos:0.0000,0.0000,0.0000|WPos:0.0000,0.0000,0.0000|F:4000.0000>
$X
[Caution: Unlocked]
ok
?<Idle|MPos:0.0000,0.0000,0.0000|WPos:0.0000,0.0000,0.0000|F:4000.0000>
```
This shows that I can issue HOLD with a !, then control X to HALT, then issue ~ to clear HOLD, then $X to clear HALT, and we end up back in IDLE, without the ~ we would be back in HOLD.

**Comment by domenic-d** [comment]
@wolfmanjm Thanks for the info. @cprezzi oversees this part of the code and I guess he will ask for any clarification if needed.

Just to clear up on the original question, is 'latest' the version users should be running?

**Comment by wolfmanjm** [comment]
Yes always use the latest edge.

**Comment by FabCreator** [comment]
I thought Laserweb was using CNC version?

**Comment by cprezzi** [comment]
@FabCreator Yes, absolutely. On the whole thread we are talking about the CNC firmware.

**Comment by cprezzi** [comment]
@domenic-d I will check my code for the procedure like Jim described.

**Comment by domenic-d** [comment]
@cprezzi Just checking in to see whether you have had a chance to look into this?

**Comment by cprezzi** [comment]
@domenic-d I was very busy last month and forgot about this problem. Sorry!
I did now adjust the process on "clear alarm" for smoothieware (send additional ~after $X). This seems to resolv the problem. It will be published with backend version 126.

**Comment by domenic-d** [comment]
@cprezzi Thanks Claudio.
I will check this with the latest version of Smoothieware when its published.

**Comment by domenic-d** [comment]
@cprezzi Hi Claudio.
I have just tested the latest smoothie CNC firmware (compiled locally).
It appears that this version allows clearing of alarms correctly.

A new problem is that when connecting via wifi, 'No supported firmware detected' is returned. This error does not occur with the previous version of the firmware. It also does not occur when connecting via USB.

I suspect there may be a problem with the way lw.comms is parsing the smoothie connection string?

I have attached two screen grabs showing USB and WiFi connection responses by the console. Can you provide any information on why this would be happening?

![screen shot 2017-10-04 at 10 49 28 am](https://user-images.githubusercontent.com/27034222/31154332-19d38bf8-a8f2-11e7-978d-7c8f93c0d062.png)
![screen shot 2017-10-04 at 10 50 07 am](https://user-images.githubusercontent.com/27034222/31154331-19cf6b0e-a8f2-11e7-9f35-3764e21c7ac8.png)

**Comment by cprezzi** [comment]
@domenic-d Good question. It could be that it just takes a little longer until smoothieware sends the welcome string and this takes more than the default timeout of LW. 
You could expand that timeout by adding "SMOOTHIE_WAIT_TIME=5s" to the ".env" file. (default is 1s)

**Comment by FabCreator** [comment]
![image](https://user-images.githubusercontent.com/19230933/34438339-5202d540-eca6-11e7-8f08-714862866f8d.png)

Hi All,
During a long engrave we occasional get this issue, the job moves into a Hold state, we are unable to clear the hold and continue the job. Any ideas to why it could be moving into hold? Is there any way we can continue the job without having to abort and then ~ to clear the hold.

Kind regards,
Bonne

**Comment by FabCreator** [comment]
![image](https://user-images.githubusercontent.com/19230933/34438728-26c7bd5c-eca9-11e7-9f45-a8646d2ff5ce.png)

**Comment by jorgerobles** [comment]
@FabCreator  Probably gone to Alarm state for a raster issue. There have been some optimizations did by @llamasoft  last week. Will be added next compile so you can test if still happening.
