### ISSUE TITLE
NOT AN ISSUE - PAGE BEING USED FOR WIKI IMAGE UPLOAD - DO NOT MODIFY OR DELETE

### ISSUE THREAD

**Issue by funinthefalls** [LaserWeb/LaserWeb4#401]
![meraygun](https://user-images.githubusercontent.com/3101946/29798766-255bddd6-8c2d-11e7-8ad3-a2382f51ed9a.png)

This upload method is at: http://solutionoptimist.com/2013/12/28/awesome-github-tricks/

**Comment by openhardwarecoza** [comment]
So CNCPro.co now?  <frown>

**Comment by funinthefalls** [comment]
[
![laserwebdec2016](https://user-images.githubusercontent.com/3101946/29824987-fb84c4d6-8ca0-11e7-8a5e-6fd0178933c1.PNG)
](url)

**Comment by openhardwarecoza** [comment]
Anthony... this sort of thing is WHY i kicked you out of doing docs.  Seriously WTF.   We moved from Github wikis, to a proper PAID FOR hosting with proper CMS so we DONT HAVE TO RESORT TO STUPID HACKS like this!

**Comment by openhardwarecoza** [comment]
Also, anyone care to remember WHY we went from Git wikis to CMS?   for the sake of USERS: Git wikis are too limited to do proper menu structures and search

**Comment by openhardwarecoza** [comment]
This is another example of the shit you did in the old days too: nonsensical shit is worth less than NO docs at all... 

Who uses curly brackets as a whatever it was supposed to be
![brackets wtf](https://user-images.githubusercontent.com/7695323/29825378-8100fcf0-8cd4-11e7-94da-4fab6425164e.PNG)

firmware-cnc.bin 
![nonsensical shit](https://user-images.githubusercontent.com/7695323/29825318-5ae22e40-8cd4-11e7-98c0-d242c31ef834.PNG)

My point is you need someone who KNOWS the app, to dopcument the APP, not some bored guy who thinks he has a clue

**Comment by funinthefalls** [comment]
As always, you are entitled to you opinion. I was just doing what Todd asked me to do. If you have an issue with the documents being done this way I suggest you have a discussion with Todd, Claudio and Jorges. I am nothing more than a volunteer trying to move this project forward. I find your ability to -overreact to things, well frankly I find it as being nothing more than a childish tantrum.

**Comment by openhardwarecoza** [comment]
@tbfleming ? @cprezzi @jorgerobles

**Comment by openhardwarecoza** [comment]
showing users screenshots off the live version (as per your first post)
leads to more confusion too... at least crop out the browser ffs!

**Comment by funinthefalls** [comment]
That screen shot is direct fro CNCPro.co, funny you never has an issue with it when it was posted by someone else, but now that I post it it you comment that it is idiotic. Make up your mind Peter, can't have it both ways.

**Comment by openhardwarecoza** [comment]
Then FIX it dont just blindly move existing contents. That's not what was
needed ever

**Comment by funinthefalls** [comment]
Fixing is what this process is all about. A message was posted on the LaserWeb g+ community stating it would be a few weeks before everything was moved and edited.

**Comment by openhardwarecoza** [comment]
So, do it twice? Upload wrong then te upload correct. Oh all the while
still in the wrong place. Genius! That makes a lot of no sense. Sure you
dont want to go volunteer somewhere else?

**Comment by funinthefalls** [comment]
It may be YOUR idea of being the wrong place, but it is where the CURRENT devs wanted me to put it. You can try and bait me all you want Peter, the only thing you will accomplish is creating tons of screen shots that document your ignorance and lack of respect for others.

**Comment by openhardwarecoza** [comment]
:) yay more screenshots you wanna forward to everyone via email. Again.
Surprised i dont like you? Whose childish now. Anyway. Fuck forth.

**Comment by jorgerobles** [comment]
Please Stop. I think this is not the place to air up personal grudges.

Just ask @tbfleming  politely what all of this intended (I've been away for a while, and don't know about that conversation).

I believe in people's good will.
Disabling wiki until that is a good option.

**Comment by tbfleming** [comment]
I'm pissed off at you, @openhardwarecoza . I need to back away before I do something rash.

**Comment by openhardwarecoza** [comment]
Thats fine. Just remember the history you  don't even know

**Comment by tbfleming** [comment]
I don't give a crap about past history I don't know of, except when you use it as an excuse to go off the rails at someone.

**Comment by funinthefalls** [comment]
This thread is still for images destined for use in the LaserWeb wiki. Please do not delete or modify.

**Comment by cprezzi** [comment]
@openhardwarecoza What did you make with cncpro.co??? I spent many hours for cncpro.co!! 
The wiki was not ment to replace cncpro.co, it was ment to give impatient users a quick entry!

Please restore cncpro.co.

**Comment by funinthefalls** [comment]
I am closing this issue as it strayed from its purpose. I will be making another issue to handle the image uploading on a temporary basis

**Comment by cprezzi** [comment]
Image for wiki:
![comms](https://user-images.githubusercontent.com/5457949/70990703-5f238c00-20c6-11ea-9342-fb0d061b5325.jpg)
