### ISSUE TITLE
##NOT AN ISSUE - FOR UPLOAD OF WIKI IMAGES ONLY - DO NOT USE OR RRESPOND PLEASE**

### ISSUE THREAD

**Issue by funinthefalls** [LaserWeb/LaserWeb4#403]
This issue is only to allow the temporary uploading of images to the LaserWeb4 wiki. Please do not respond or otherwise edit this issue.

Regards,
Anthony Bolgar

**Comment by funinthefalls** [comment]
![select-profile](https://user-images.githubusercontent.com/3101946/29846236-ef5e1a16-8ce3-11e7-9691-138d9bc8ebcf.png)
![new-profile](https://user-images.githubusercontent.com/3101946/29846237-f0c8deae-8ce3-11e7-9dfd-0b974ce1a4c4.png)
![meraygun](https://user-images.githubusercontent.com/3101946/29846240-f2aadc68-8ce3-11e7-9c48-5dffb8a53826.png)
![laserwebdec2016](https://user-images.githubusercontent.com/3101946/29846242-f54aef76-8ce3-11e7-82ae-6d1ce18f7be2.PNG)
![gerbil](https://user-images.githubusercontent.com/3101946/29846244-f72edf82-8ce3-11e7-9c6f-7372454b109f.png)

**Comment by cprezzi** [comment]
@funinthefalls Please don't use your "UFO" Logo on our page. That's nothing official and in my eye, it's ugly. Also, don't post anything about gerbil, it's nothing we officially support.

**Comment by cprezzi** [comment]
![settings-machine](https://user-images.githubusercontent.com/5457949/29917958-e618d2d2-8e43-11e7-9664-22933c0013b6.jpg)

![settings-file](https://user-images.githubusercontent.com/5457949/29917964-ed6a6e92-8e43-11e7-87c1-ac5aa50e6d30.jpg)

![settings-gcode](https://user-images.githubusercontent.com/5457949/29917970-f29b930a-8e43-11e7-9eed-e31db7a1d2df.jpg)

![settings-application](https://user-images.githubusercontent.com/5457949/29917977-f70f49fe-8e43-11e7-88f9-e4083fc2c88b.jpg)

**Comment by jorgerobles** [comment]
@funinthefalls  is this issue still used? How is the documentation on wiki going?

**Comment by cprezzi** [comment]
@jorgerobles This issue is permanently needed. as the pictures in the wiki are related to the pictures in this issue.

**Comment by jorgerobles** [comment]
Ok, just curiosity: are the url references not working if issue is closed? We can always reopen or extend with content even closed

**Comment by cprezzi** [comment]
I think it should still be working when the issue is closed. I'll test it.
