### ISSUE TITLE
Node Memory Settings

### ISSUE THREAD

**Issue by glennswest** [LaserWeb/LaserWeb4#407]
Using the latest build 4.0.989-115-x64 on windows 10 (And i've seen it on mac as well)
If I load a image and its close to my darkly em2 max size it universally seems to result in the part
of the gui blowing up, same image resized works fine. I believe the nodejs memory settings are
not big enough, can we get them set 4x bigger. 

I'd love to build from source, but its not clear what the windows build dependencies are,
can someone point me to a list/script etc for setting up development environment.

I dont mind commiting back/PR

**Comment by cprezzi** [comment]
All the GUI stuff is running in the browser (chrome inside the electron exe), not in the nodejs server. The server only needs memory for the gcode while you run the job from the controll tab.

@jorgerobles @tbfleming Any limitations for file sizes in the frontend?

**Comment by jorgerobles** [comment]
None than I'm aware of, but I suppose there are.

**Comment by jorgerobles** [comment]
Glenn please attach file for review..

**Comment by Daniel-dk** [comment]
I think I'm running into the same issue, 

When I load a fairly large image, GCODE generation for engraving gets to around 6 % then the GUI goes blank ( white screen, and my machine's fans slow down again, I it might have crashed or stopped entirely )
![339971main_pg63_as11-40-5878_full](https://user-images.githubusercontent.com/582384/30069081-0095ee7c-9260-11e7-84da-6c13d46d8b07.jpg)

**Comment by cojarbi** [comment]
I just downloaded your image and was able to generate the raster code in the than a minute with no issues. I presume machine specs has something to with this. I'm running a surface pro 
![20170905_104240](https://user-images.githubusercontent.com/16444438/30070089-029d7bf0-9228-11e7-842f-a244779db3d2.jpg)

**Comment by Daniel-dk** [comment]
mm, interesting, 
The host machine is quite beefy ( i7 with 16 GB RAM, OS: Win10 x64, 500 GB free on main HDD )

Is there a debug or error log that I could analyse to see what might have gone wrong ?

 ( the plan is to use ths laser engraving option with a low power UV laser to make cyanotype images )

**Comment by Daniel-dk** [comment]
Laser diameter was set to 0.01 mm, 
When set to 0.1 mm it generates Gcode for the image sucessfully

Might be an issue with the number of instructione generated with such a small increment.

**Comment by tbfleming** [comment]
.01 mm would cause it to try to generate ~(200/.01)*(200/.01) = 400,000,000 lines of gcode. That's too big.

**Comment by cprezzi** [comment]
The real beam diameter is mostly >0.1mm (if good focus). Configuring anything less that that would just overlap the dots.
