### ISSUE TITLE
Not reading .dxf in inches

### ISSUE THREAD

**Issue by joelmosk** [LaserWeb/LaserWeb4#412]
I am using laserweb with grbl 1.1. I laserweb and grbl is set for metric units because the laser ihas metric a feed. I load up a .dxf with the metric tag in it as is well. The laserweb preview is correct. 
I load up a .dxf with an inch tag and laserweb assumes the dimension are in mollimeters and the preview and actual lasering is wrong. Shouldnt laserweb see the inch tag and multipy all th dimentions accordingly?
Am i setting something up wrong? How do i fix this?
Is this just not supported?
Is it a missing feature or not supposed to be supported?

Please help.
Thanks,
Joel

**Comment by cprezzi** [comment]
LaserWeb does not support imperial (yet), but it should be easy to export the DXF in mm from the software you are designing in.
