### ISSUE TITLE
[Feature Request] Better Webcam support including timelapse function

### ISSUE THREAD

**Issue by mrcg** [LaserWeb/LaserWeb4#414]
I would like to ask for better webcam support so that the webcam live stream can be easly expanded in control/move mode and while engraving activity.
Beside this i would like to have automatic timelapse generation while engraving activity (user to set amount of pictures every X seconds).
More or less exactly the same implementation like done in Octoprint.

https://github.com/foosel/OctoPrint

**Comment by jorgerobles** [comment]
> I would like to ask for better webcam support so that the webcam live stream can be easly expanded in control/move mode and while engraving activity.

You know that you can spawn a floating window on LW, that can me moved around and be resized?

![image](https://user-images.githubusercontent.com/1706080/30759340-204ed098-9fd6-11e7-97d3-f0fa64775abe.png)

> Beside this i would like to have automatic timelapse generation while engraving activity (user to set amount of pictures every X seconds).

That is unlikely to be done on LW part, because cannot be done with frontend technologies in a performant way. An alternative could be using an external ipcam software to make capturing.

:|

**Comment by mrcg** [comment]
I really like the implementation as done in Octoprint (printserver similar to LaserWeb but used for 3d printer).
Its very useful to have the webcam pre-integrated on the page with all the control (up/down/left/right, laser power, weak laser on/off, start/stop/pause gcodeetc.).

Usually the webcam is used to setup (adjust and set the home point on the object) and safely monitor the engraving activity (emergency stop, pause, etc.).
Therefore all the contol button are needed beside the webcam live stream.

Implementation of control tab in octoprint:
[http://octoprint.org/assets/img/features/control-tab.png](url)

Screenshot from timelapse implementation in octoprint:
[http://octoprint.org/assets/img/features/timelapse-tab.png](url)

**Comment by jorgerobles** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/1706080/30762331-ed13cab0-9fe1-11e7-9443-b997ee6e1d4b.png)

BTW. I know about Octoprint, but it uses other technology (Python) that currently offers low level system access, what is not posible currently on LW.

**Comment by jorgerobles** [comment]
On the other side, LW offers OMR technology to make precise aligning of stock (https://github.com/LaserWeb/LaserWeb4/issues/354)

**Comment by jorgerobles** [comment]
As #425, support for webcam URL is granted. Use a native streamer app on your machine to connect to, LW cannot afford an embedded streaming server performance, for now.
