### ISSUE TITLE
errors open eagle dxf files

### ISSUE THREAD

**Issue by madhouse-nl** [LaserWeb/LaserWeb4#416]
can you investigate the eagle7.7.0 output files  .dxf 

included in zip file.

I get this error massage when opening eagle dfx files:

Errors found in DMX_RGB_LED%N.sol.dxf please re-save in R12 ASCII format. Check console log and documentation for more details.
OK

![error dxf](https://user-images.githubusercontent.com/32269334/30813213-1877a05a-a20d-11e7-8e76-490a8db06716.PNG)
[Nieuwe map (2).zip](https://github.com/LaserWeb/LaserWeb4/files/1329780/Nieuwe.map.2.zip)

**Comment by jorgerobles** [comment]
Have you tried to resave as r12 dxf previously?

**Comment by madhouse-nl** [comment]
In eagle there is no option for it.
from eagle file menu you can export in jpg, bmp or dxf but no options
john

**Comment by jorgerobles** [comment]
Autocad is free download on Autodesk site. Lw only supports r12 dxf.

**Comment by madhouse-nl** [comment]
Thanks, will try it.
