### ISSUE TITLE
LW4 Files Quarantined By McAfee - Have Lost LW4

### ISSUE THREAD

**Issue by Bama-Breeze** [LaserWeb/LaserWeb4#419]
Attempted to download the most recent operating software for LW4 this evening.  It would run on a Windows 10 (64bit operating system) to control a C3D.  Previous version of LW4 downloaded without issue.

This time my McAfee quarantined the files and would not permit executing the installation.  I uninstalled the newest edition of LW4 and experienced the same circumstances with the previous edition of LW4 that had been installed successfully in July.  Consequently I have lost all copies of LW4.

Thank you for any guidence.

Attached are photos of the alert and error messages.
![img_20170930_232948](https://user-images.githubusercontent.com/28910156/31051784-4db47eea-a637-11e7-9b44-2aaedef11dbc.jpg)

**Comment by jorgerobles** [comment]
This issue have arised from time to time. The fact is an AV issue, I use avast, and no complains.

**Comment by Bama-Breeze** [comment]
Thank you Jorge.  Seems all I tried to accomplish yesterday was snakebit.  My best sir. 
-------- Original message --------From: jorgerobles <notifications@github.com> Date: 10/1/17  3:10 AM  (GMT-06:00) To: LaserWeb/LaserWeb4 <LaserWeb4@noreply.github.com> Cc: Bama-Breeze <montys-woodworking@att.net>, Author <author@noreply.github.com> Subject: Re: [LaserWeb/LaserWeb4] LW4 Files Quarantined By McAfee - Have Lost
  LW4 (#419) 
This issue have arised from time to time. The fact is an AV issue, I use avast, and no complains.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LaserWeb/LaserWeb4","title":"LaserWeb/LaserWeb4","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LaserWeb/LaserWeb4"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jorgerobles in #419: This issue have arised from time to time. The fact is an AV issue, I use avast, and no complains."}],"action":{"name":"View Issue","url":"https://github.com/LaserWeb/LaserWeb4/issues/419#issuecomment-333360817"}}}
