### ISSUE TITLE
CNC Mode ??

### ISSUE THREAD

**Issue by sfranzyshen** [LaserWeb/LaserWeb4#420]
... the reference to the CNC Mode has been removed from the wiki (https://github.com/LaserWeb/LaserWeb4/wiki/Settings-:-Application) and toolCncMode is set to false  in src/reducers/settings.js ... how do I enable Z? ... is CNC support still in the plan?

**Comment by cprezzi** [comment]
Yes, we still support CNC Milling (more than ever), but CNC-Mode ist not anymore needed. All Milling operations are available in the CAM by default and you can enable the Z-Axis with "Machine Z Stage" in Settings / Machine.
