### ISSUE TITLE
option to reverse axis 

### ISSUE THREAD

**Issue by themodmin** [LaserWeb/LaserWeb4#421]
hello i'm using LaserWeb Frontend: 4.0.990 Backend: 4.0.115 w/ GRBL 1.2
I can't find an option to reverse/invert my x axis as it goes the opposite direction.

**Comment by jorgerobles** [comment]
I always did this on hardware, either issuing $3 or physically inverting motor sockets.

**Comment by themodmin** [comment]
thank you i used $3=1
