### ISSUE TITLE
[Feature Request] Unidirectional Raster

### ISSUE THREAD

**Issue by lonnie776** [LaserWeb/LaserWeb4#424]
My laser engraver is a bit finicky and only likes to raster from left to right. Can you please add an option to do the raster in only 1 direction.

I found the line of code that manages this. It is line 687 of dev-es6/src/lib/lw.raster2gcode/raster-to-gcode.js

I am currently running it on a Pi.

**Comment by jorgerobles** [comment]
Will be available on next build. :)
