### ISSUE TITLE
Provide Support for Raspberry Pi webcam

### ISSUE THREAD

**Issue by scottmil** [LaserWeb/LaserWeb4#425]
I am running LaserWeb4 on a Raspberry Pi 3 with the stock 8MP webcam.   I am running Raspbian Stretch version 4.9.41-v7+.

However, I cannot configure the Raspberry Pi camera in the LaserWeb4 settings.  The video resolution dropdown has no results.  (Screenshot attached)

Can you provide support for the Raspberry Pi webcam in a future release?

Thanks

[Laserweb-Workspace.json.txt](https://github.com/LaserWeb/LaserWeb4/files/1381042/Laserweb-Workspace.json.txt)
![raspberry pi 3 cam](https://user-images.githubusercontent.com/10510570/31524237-0dc448b2-af6d-11e7-97f1-15b49e7ac752.png)

**Comment by cprezzi** [comment]
We do not recommend running the frontend on a Raspberry Pi (too slow + needs Chome browser to work properly). You can run the server on the raspi, but you should use Win PC or Mac for the frontend.

If doing so, you need to stream the camera video via network to the frontend.

**Comment by scottmil** [comment]
Thanks, Claudio.

I am running the LaserWeb4 server on a Raspi 3 and using my Mac Chrome browser as the front end, and it seems to run well.

I also have MJPEG-streamer successfully running on the same Raspi, whose video I stream independently to my frontend.  However, I was hoping I could better integrate the webcam video with the LaserWeb4 interface.

FYI: I run Octoprint on a Raspi with webcam for my 3D printer, and I was hoping to have the same web control functionality using LaserWeb4 with my laser engraver.

Again, thanks for all of your dedicated work on LaserWeb4.

-Scott

**Comment by cprezzi** [comment]
@jorgerobles I thought we do support configuring a webcam via MJPEG streaming over IP? Don't we?

**Comment by jorgerobles** [comment]
Nope. That's a pending feature :) I will take a shot next week.

**Comment by jorgerobles** [comment]
@cprezzi, are you working on it on MPG branch? or is a different Mpeg?

**Comment by cprezzi** [comment]
MPG stands for Motion Pulse Generator, which is a machine remote (pendant). In the MPG branch I am implementing an interface to the XHC-HB04 MPG (see http://www.ebay.com/itm/2017-Wireless-Mach3-MPG-Pendant-Handwheel-for-CNC-Mac-Mach-3-4-axis-Wholesale-/140918851970).

**Comment by jorgerobles** [comment]
Ok :)
