### ISSUE TITLE
Program blink in mac os

### ISSUE THREAD

**Issue by sdarocha** [LaserWeb/LaserWeb4#432]
Hello all. 
I am testing (learning) LaserWeb-v4.0.990b-115 for some weeks, my laser just arrived today.
Today I open LaserWeb and can't see nothing, all is blinking. Also tried the latest version.

I'm using mac osx 10.10.5

I spend all day googling but can't found the solution. I think it's because of a codec.
Thank you in advance.

![screen shot 2017-11-03 at 19 15 26](https://user-images.githubusercontent.com/32965858/32399358-1f30673e-c0ed-11e7-8298-0dab21f20a7c.png)
![screen shot 2017-11-03 at 20 16 21](https://user-images.githubusercontent.com/32965858/32399359-1f4fc494-c0ed-11e7-9fa9-646968a250a2.png)

**Comment by cprezzi** [comment]
Please don't ask the same question on git and G+. We don't like to have the discussion spread over multiple channels. Please use git issues only for software bugs. As this is probably an installation problem, we will try to help you on G+.
