### ISSUE TITLE
Differentiate between cut and travel speed

### ISSUE THREAD

**Issue by nerdbeere** [LaserWeb/LaserWeb4#433]
Hey there,

I'm pretty new to laser cutting but have a background in 3d printing where we are used to set different speeds for travel an actual printing.
I wonder why there's no such thing in laserweb4. It would significantly speed up my engraving jobs. Is there any reason why this is not implemented? Am I missing something?

**Edit:** After looking through the code a little I found `rapidRate` which [seems to be always disabled](https://github.com/LaserWeb/LaserWeb4/blob/a642d6bfe8070a70a26552409a0b041c34ff3843/src/lib/cam-gcode-raster.js#L183).
I also saw that, in order to get `G0` instead of `G1`, `burnWhite` needs to be disabled. Can someone explain to me what this does?

**Comment by jorgerobles** [comment]
Thanks, but it was a design decision, as far as I remember isn't it @tbfleming ?

**Comment by tbfleming** [comment]
@jorgerobles yep.

**Comment by nerdbeere** [comment]
@tbfleming Could you elaborate on why this design decision was made? I would love to understand this a bit better.

**Comment by tbfleming** [comment]
I just left a comment on the push which partially explains my position. LW assumes that the firmware controls G0 feed. Most firmware has a setting for it.

**Comment by edgary777** [comment]
This is an old issue but I recently came upon this same problem, my solution is not perfect solution but works if your firmware doesn't control G0 feed.
You can edit the LW gcode setting for **TOOL OFF** and add "G1 F???" where "?" is the feed speed, it will change the feed speed only when the laser is off.

**Comment by nerdbeere** [comment]
@edgary777 what I didn't know when I opened this PR was that you can disable `burnWhite` (not sure what this does anyway) when using Laser Raster which basically does exactly what I wanted to achieve.

Also, if your input file allows that (vectors), use Laser Cut Fill Path. This is much faster than Laser Raster
