### ISSUE TITLE
All' right, I'm stupid, how to start the program...

### ISSUE THREAD

**Issue by Gnaogab** [LaserWeb/LaserWeb4#441]
Ok, I'm so stupid, bat  I can do it....
I use win7 and xubuntu...
I've download and installed Git , laserweb4, Arduino,  Java, Chrome...... and so on..
I've everythink ..... 
Now what can I do to start laserweb.. .
Run  a Git gui  or cmd , and then ?
I'm very afraid... please  help a stupid 'nibbio'
Gab

**Comment by jorgerobles** [comment]
LOL. Download the app from
https://github.com/LaserWeb/LaserWeb4-Binaries/releases

**Comment by cprezzi** [comment]
You think much too complicated. Just download and run the Windows Installer (x86 or x64). You will get a start Icon on the desktop (like a normal application).
