### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Mohamed-Ateef** [LaserWeb/LaserWeb4#444]
Hello Good Morning !
im Using LaserWeb4 Now and is good application So Far
But i have Some Question ?!
im using Grbl 1.1 So i set Machine Profile is Grbl That is Right ?!
and i Changed PWM to 12000 For My laser !
if there any setting i must set it be4 i work Becuse when im engrave photo i got Result Not Good idk Why Can u help me with this question`s
thnx

**Comment by jorgerobles** [comment]
Please use https://plus.google.com/communities/115879488566665599508
