### ISSUE TITLE
LW4 broken

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#45]
```
./src/reducers/machine-profiles.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../data/lw.machines/machine-profiles.json
```

**Comment by jorgerobles** [comment]
Hi @tbfleming , I've split up the machine-profiles data to a new repository (material-database is on the way too), https://github.com/LaserWeb/lw.machines as @openhardwarecoza suggested (#31)
It should be available as a submodule (https://github.com/LaserWeb/LaserWeb4/blob/dev-es6/.gitmodules)
Sorry I should advertised 😦 
If you cannot get it working (should be easy) I will revert.

**Comment by tbfleming** [comment]
Ah-ha. It works fine. If we stick with this, then please update the laserweb-development-environment section of the readme.

A disadvantage to this approach is that it requires two commits for every change, plus extra git commands for every pull. Since we already have to run ```npm install``` frequently, maybe it should go in package.json instead. See https://github.com/LaserWeb/LaserWeb4/blob/005f9f06e86e239d6f62d16675b1d49c9b30875a/package.json#L84

**Comment by jorgerobles** [comment]
Ok, no problem, but I would like to keep in the data folder. Is there a way to do that with npm?

**Comment by jorgerobles** [comment]
Ok, no problem, but I would like to keep in the data folder. Is there a way to do that with npm?

**Comment by tbfleming** [comment]
I don't think there is. npm forces it under node_modules. An advantage is that it makes it clear to everyone that it lives in a different repository.

**Comment by openhardwarecoza** [comment]
In the Electron-LW3 branch we now use some awesome NPM Script fu for that.
It can launch other commands (git init submodules for example).  Say add a
script called setup-dev and have it run npm install; git init submodules;
etc

**Comment by jorgerobles** [comment]
Done! I've created a package.json for each repository in case we get a mess with @openhardwarecoza script-fu, and added a "npm run-script installdev" option to obtain my yellow belt.

**Comment by tbfleming** [comment]
It needs ```git submodule init``` before ```git submodule update```

**Comment by jorgerobles** [comment]
Done!

**Comment by tbfleming** [comment]
It works nicely. Now just need to update the readme.

**Comment by jorgerobles** [comment]
Sorry :roll_eyes: , and Done
