### ISSUE TITLE
Coordinates not being displayed

### ISSUE THREAD

**Issue by gregoryperrin** [LaserWeb/LaserWeb4#453]
Hi,

I am able to jog the machine, but on the top left, X and Y always say 0, even while i jog it.

I tested this on two different computers with Linux Mint on it.

![screenshot_2018-01-28_13-40-00](https://user-images.githubusercontent.com/15223909/35485697-374984c2-0431-11e8-96e7-915f3834f81f.png)

**Comment by jorgerobles** [comment]
GRBL $10=1

**Comment by gregoryperrin** [comment]
My grbl settings in my board (Eleksmaker Mana SE) with GRBL 1.1f is already setup with $10=1. Are you suggesting this is the problem and I should make it 0 or 2?

**Comment by gregoryperrin** [comment]
@jorgerobles

**Comment by jorgerobles** [comment]
Yes, it's on the documentation https://cncpro.yurl.ch/documentation/initial-configuration/31-grbl-1-1e you have to set to $10=0

**Comment by gregoryperrin** [comment]
thanks!
