### ISSUE TITLE
Gcode generates extra paths that don't appear in the original SVG

### ISSUE THREAD

**Issue by quintesse** [LaserWeb/LaserWeb4#459]
This is how the SVG gets rendered:

![image](https://user-images.githubusercontent.com/778793/37560063-8399945e-2a31-11e8-8367-98ae8850e58e.png)

And this is the generated GCODE:

![image](https://user-images.githubusercontent.com/778793/37560065-91963d96-2a31-11e8-9b4d-330e57108970.png)

You can clearly see the extra lines that would cut off the puzzle pieces tabs.

[Laserweb-Workspace.json.txt](https://github.com/LaserWeb/LaserWeb4/files/1822103/Laserweb-Workspace.json.txt)

**Comment by jorgerobles** [comment]
Check your svg... I bet there are, or please attach the svg to test it out.

**Comment by quintesse** [comment]
@jorgerobles the SVG is in the attached `Laserweb-Workspace.json.txt`, you can see for yourself

**Comment by jorgerobles** [comment]
Hmm no.

Inside workspace is the vector data after parsing, not the SVG/DXF file.
Need to compare the source file with the data present on the workspace to
detect parsing error or another issue.

:)

2018-04-17 19:58 GMT+02:00 Tako Schotanus <notifications@github.com>:

**Comment by quintesse** [comment]
OK, here it is: [jigsaw.zip](https://github.com/LaserWeb/LaserWeb4/files/1921022/jigsaw.zip) :)

**Comment by jorgerobles** [comment]
It's an AI/LW issue, just open it and release compound path.
[jigsaw_2.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/1921032/jigsaw_2.svg.zip)


![image](https://user-images.githubusercontent.com/1706080/38888016-b620bf36-427a-11e8-9613-259398670019.png)

**Comment by quintesse** [comment]
Ok, great, but... could you perhaps explain:

> just open it and release compound path.

I didn't get that :)

**Comment by jorgerobles** [comment]
http://g.recordit.co/vF4aQyg5f3.gif

2018-04-17 20:25 GMT+02:00 Tako Schotanus <notifications@github.com>:

**Comment by quintesse** [comment]
Aha, unfortunately in Inkscape the same function there doesn't really seem to work very well / the same way:

![inkscape_break_apart](https://user-images.githubusercontent.com/778793/38889468-1aaffa30-427f-11e8-8dea-f93503b37783.gif)

**Comment by jorgerobles** [comment]
Try reassigning colors, maybe?

2018-04-17 20:37 GMT+02:00 Tako Schotanus <notifications@github.com>:

**Comment by jorgerobles** [comment]
Closing corner case, should be solved on Illustrator software

**Comment by quintesse** [comment]
I don't agree. The problem is in the Laserweb software. Perhaps there is a work around for Illustrator, but for people that don't have Illustrator there doesn't seem to be a solution.

**Comment by jorgerobles** [comment]
This file has join paths too and does not raise the error you have with the other file, hence, not all the files have that error (indeed, believe me or not, was the first file I've seen with that behavior, and I use LW daily)
[join paths.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/1966927/join.paths.svg.zip)

That, said, I've observed that behavior is only raising on a join path that has collinear intersections with open paths @tbfleming 

Decomposed and recomposed on AI: true
[jigsaw_2.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/1966950/jigsaw_2.svg.zip)
Open Paths only: false
[jigsaw_3.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/1966949/jigsaw_3.svg.zip)
Closed Paths and Open Paths not collinear: false
[jigsaw_4.svg.zip](https://github.com/LaserWeb/LaserWeb4/files/1966948/jigsaw_4.svg.zip)

**Comment by jorgerobles** [comment]
@tbfleming On a compound path, any M/m command should be parsed as a new path or may rawpaths admit delimiters or subarrays to not to treat them as the same entity on join reduceCamPaths?

**Comment by tbfleming** [comment]
Oy. It's a good file that has characteristics that fool the code into thinking it's a bad file which needs to be cleaned up. This file mixes open and closed subpaths in a single path object. Usually that means the user didn't close paths correctly, so the code closes them, throwing things off.

**Comment by tbfleming** [comment]
Heh. That mixture is also confusing Inkscape badly.

**Comment by tbfleming** [comment]
Here's how to work around Inkscape's confusion in order to clean it up:
* Select the path
* Right-click the X (none) on the color bar and choose Set Fill
* Right-click any color on the color bar and choose Set Stoke
* Now use Path -> Break Apart

**Comment by tbfleming** [comment]
> Try reassigning colors, maybe?

Yep :)

**Comment by quintesse** [comment]
Ok, that worked indeed, thanks @tbfleming !

![image](https://user-images.githubusercontent.com/778793/40350748-f5dcaedc-5daa-11e8-894e-a0c765d49b40.png)

Any explanation perhaps for us mortals as to _why_ this works? :)

Also, perhaps it would be possible to add this to the docs somewhere? This information might be useful for others too.
