### ISSUE TITLE
Laser Cut: Laser does not turn off during empty feeds / between path

### ISSUE THREAD

**Issue by careyer** [LaserWeb/LaserWeb4#462]
Hi there,

I am having issues with the "Laser Cut" Gcode. The laser does not turn off between different path that are bing cut. The empty feeds are displayed in "green" in the simulator... however the laser stays on during those movements connecting the different path/shapes with a line.

<img src="http://www.ip-networx.de/content/GitHub/LaserCuterror.JPG">

**Comment by jorgerobles** [comment]
You should check your M3,M4,M5 on settings.

Github is for bugs. That's clearly not a bug on Laserweb but a misconfiguration on your side. 

Please use gplus community to ask for support, thanks
