### ISSUE TITLE
Solve "hanging chads" by implementing overtravel

### ISSUE THREAD

**Issue by CrowJay** [LaserWeb/LaserWeb4#465]
I'm facing the same issue as described here on the [Eleksmaker forum](http://forum.eleksmaker.com/topic/656/t2laser-prevent-hanging-chad/9). Is it possible to implement a simular solution to Laserweb?

**Comment by jorgerobles** [comment]
There's overscan parameter implemented on LW.

**Comment by jorgerobles** [comment]
Please reopen if unsolved.
