### ISSUE TITLE
HI , I'm the developer of EleksMaker

### ISSUE THREAD

**Issue by EleksMaker** [LaserWeb/LaserWeb4#475]
HI , I'm the developer of EleksMaker. The software you're doing is awesome.

Will you have any plans for carving any images in the future?(in outline mode)

**Comment by jorgerobles** [comment]
Can you explain that further? Please attach a photo. 
When you say carving you mean: with a mill, or doing z passes with laser?
Outline mode could be achieved in several ways.. finding edges on a image editor, preparing vector outline with an illustration editor, etc

Thanks!
