### ISSUE TITLE
Lastest update did not keep settings.

### ISSUE THREAD

**Issue by Member32** [LaserWeb/LaserWeb4#485]
[New ver Laserweb-Workspace.txt](https://github.com/LaserWeb/LaserWeb4/files/2024338/New.ver.Laserweb-Workspace.txt)
[Old Laserweb-Workspace.txt](https://github.com/LaserWeb/LaserWeb4/files/2024339/Old.Laserweb-Workspace.txt)

I updated to latest release of Laserweb4 and I cannot burn anything.
I uninstall latest version and reinstall previous version and ALL is OK.
This has not been an issue with previous upgrades.
I did notice Initially after install that some Gcode settings were missing... then I noticed my saved machine profiles were gone too.
When I reinstall last version all goes back to normal, My saved profiles are back too.
  
Latest ver filename "LaserWeb.Setup.4.0.988-130.exe" (May21)
previous ver filename "LaserWeb.Setup.4.0.130.exe Downloaded (May1)
I am running Win7 on HP Elitebook 8470p

**Comment by jorgerobles** [comment]
The issue arised on the binaries tool change. Regrettably could not foresee that behavior. Anyway was reported already, and fixed yesterday.

Lw-comm-server has a way back ui dependency, causing a regression on the build. 

Please download again .988 and check latest features.
