### ISSUE TITLE
Laserweb 4.0.993 locking up

### ISSUE THREAD

**Issue by marshalltjones** [LaserWeb/LaserWeb4#489]
I am using Laserweb 4.0.993 on Win 7 running on an Intel i3 with 16 GB of ram.  I loaded a 300 dpi png (292.6 mm tall 195 mm wide) in Laserweb and set it to 200 mm tall.  0.2 mm laser width.  When I generate g-code, the Laserweb window goes completely white, and you have to restart the program.  When I drop the file to 100 mm tall, it generates g-code without an issue.  

I am including the file and a screenshot of the settings before g-code generation.  

Am I missing something?
![before gcode](https://user-images.githubusercontent.com/20959782/41075274-ef6225a6-69d9-11e8-976c-c3e42443588d.png)

**Comment by marshalltjones** [comment]
![dsc_0014](https://user-images.githubusercontent.com/20959782/41075365-5aad8152-69da-11e8-915b-3b94453e2dbd.png)

**Comment by jorgerobles** [comment]
![image](https://user-images.githubusercontent.com/1706080/41112446-4422c26c-6a7f-11e8-91dc-4d22afb03399.png)


Sorry, I guess is a processor performance issue. Your pic goes fine (mac, i7, 16Gb Ram)

**Comment by marshalltjones** [comment]
I'll have to try it on my i5
