### ISSUE TITLE
Settings Panel number input bugs

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#49]
![number problems](https://cloud.githubusercontent.com/assets/418464/20863422/d6f3a13c-b997-11e6-80a7-9a2c8c0f8f57.gif)

This shows me doing the following:
* Entering ```200``` into Machine Width. Result is 2.
* Entering ```.1``` into Laser Beam Diameter. Result is 1.

I suspect the first problem may because of DOM changes near the input control. The second problem is a React bug; I fixed this problem in the CAM pane today. See NumberInput in components/operation.js for the fix.

**Comment by tbfleming** [comment]
@jorgerobles if you want, I can fix the 2nd problem (the React one)

**Comment by jorgerobles** [comment]
Thank you todd, please apply your patch. It's probable that also that fixes the first issue.

I have been spending some hours a few days ago around inputs, and I think it would be better to use onBlur, or just "uncontrol" all the inputs as you have done on operation.
Also this enforces my opinion that we should work on core input components to not need to spread code (DRY) on the same bugs.

**Comment by jorgerobles** [comment]
As a side issue, We need some data versioning mechanism (data as settings, machines, materials, operations) as  I've encountered localstored data is not valid as we make improvements on the code.
It could be as "easy" as a version flag on each data stores, or as complex as use  JSON Schema, to check the validity of stored data and prune/migrate if needed.

**Comment by tbfleming** [comment]
The second problem is now fixed. It didn't solve the first problem.

Please create an issue about data versioning.
