### ISSUE TITLE
Z axis doesnt move according to set mm

### ISSUE THREAD

**Issue by Timacaro** [LaserWeb/LaserWeb4#496]
Good afternoon,

I can't figure out why the Eleksmaker A3 Z axis won't move the amount of mm I tell it to. It moves but just not as much as it should. Who can tell me where to find the settings for that?

Thank you in advance.

Romano

**Comment by jorgerobles** [comment]
https://plus.google.com/105883028987453428385/posts/aReptQEWGhd?fscid=z134cpnqsorajduqb04cdzi4gkqmchxawu00k.1529894546339529
