### ISSUE TITLE
BUG: action2gcode: Invalid Regex flags

### ISSUE THREAD

**Issue by riaancillie** [LaserWeb/LaserWeb4#497]
With a raster image select and a Laster Raster operation being created, gcode generation will fail if the machine configuration (Settings > GCODE) has "Tool On" and "Tool Off" gcode defined. 

```
abstract-generator.js:11
Uncaught SyntaxError: Invalid flags supplied to RegExp constructor 'gis'
    at RegExp (<anonymous>)
    at DefaultGenerator.postProcessRaster (abstract-generator.js:11)
    at postProcessing (cam-gcode-raster.js:123)
    at Worker.r2g.onmessage (cam-gcode-raster.js:238)
```

In commit It appears that "gis" flags are invalid, specifically the single-line flag which is not supported in javascript.

[LaserWeb4/src/lib/action2gcode/generators/abstract-generator.js #492](https://github.com/LaserWeb/LaserWeb4/blob/d3583016cd9fa7f5d478471769cfdf71065a8db8/src/lib/action2gcode/generators/abstract-generator.js)

`if (this.settings.gcodeToolOn && this.settings.gcodeToolOff){
      return gcode.replace(new RegExp("G0(.*?)G1","gis"),'G0$1\n'+this.settings.gcodeToolOn+'\nG1').replace(new RegExp("G1(.*?)G0","gis"),'G1$1\n'+this.settings.gcodeToolOff+'\nG0')
    }`

[Laserweb-Workspace.json.txt](https://github.com/LaserWeb/LaserWeb4/files/2144776/Laserweb-Workspace.json.txt)
![laserweb-error](https://user-images.githubusercontent.com/30519342/42027929-305d4912-7acb-11e8-8f47-529a4d860eb7.png)

**Comment by jorgerobles** [comment]
Download previous version. Will drop the release.

**Comment by jorgerobles** [comment]
Anyway is weird I had successfully run that piece of code on latest chrome.
Have to check chromium version

**Comment by jorgerobles** [comment]
https://github.com/LaserWeb/LaserWeb4/commit/289dec3a90467d38c461841d88c2a9e54a64b7d3
