### ISSUE TITLE
Serial interface refresh will not display newly connected device

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#5]
If i start the server and load the interface before connecting the device pressing the refresh  icon will not load the device until you refresh the browser or the SD card is mounted

**Comment by lautr3k** [comment]
Before you press the refresh button, you must allow time for the card to get ready and accessible through the serial interface . I do not think it's different in LaserWeb3 ?

**Comment by cojarbi** [comment]
This is OSX.  In LW3 the second I connect I can hit refresh and get the interface. Mind that like I said above if I hit refresh in the browser I get the interface inmediatly also in LW4

**Comment by lautr3k** [comment]
No longer relevant since ES6 reboot.
