### ISSUE TITLE
No options for dogbones or tbones .

### ISSUE THREAD

**Issue by se3d** [LaserWeb/LaserWeb4#503]
Hi. I'm using laserweb4 with my diode laser and it's working like a charm. But I tried the mill function on my new cnc mill machine and on cut outside with the final size... the part is down and the tool touch it destroying part of mill. in another cnc softwares a option as T-bone or dogbones are checked for a little part without mill and maintenance the part in the place.

**Comment by cprezzi** [comment]
These are called mill tabs and they have to be done manually (in cad/cam).
