### ISSUE TITLE
My laser always go full speed and full laser power.

### ISSUE THREAD

**Issue by Ryuzaki92** [LaserWeb/LaserWeb4#508]
Hello, I know this is probably isn't the place but I have no more place to ask for help. I've bought cheap 10W 100x100cm as it turned out it's Laseraxe. I've flashed it with custom 1.1f grbl for laseraxe to make it work with laserweb but I've got problems. Everytime I load any file, amd then set laser power and feed rate before generating gcode it always go full speed and full power. I don't know what's that all about but on Google+ and benbox forums I couldn't get any help. Thanks for any help and sorry to put it here.

**Comment by cprezzi** [comment]
Please use our Google+ community (https://plus.google.com/u/0/communities/115879488566665599508) for support questions. Github is only used for veryfied bugs.
