### ISSUE TITLE
Firmware not loading more than once.

### ISSUE THREAD

**Issue by fergusfp** [LaserWeb/LaserWeb4#509]
I am having an Issue with laserweb4.0 and my MKS SBASE V1.3 on mac OSX.

I follow the instructions on the website and put the current copy of the firmware for grbl-LPC v1.1 on to a micro-sd card and rename it. I eject it from the computer and place it in the MKS BASE and plug it into my computer. After it boots I can connect it through the laserweb interface and the terminal tells me that is connected and it has found grbl 1.1 and both the $ and $$ commands work. 

<img width="554" alt="first connect" src="https://user-images.githubusercontent.com/12587072/44301493-c03f2200-a30f-11e8-9764-6c2fd309c79a.png">

However as soon as I reset, power cycle, or unplug the board and try and reconnect it tells me I don't have the correct firmware available. 

<img width="557" alt="second connect" src="https://user-images.githubusercontent.com/12587072/44301520-4c514980-a310-11e8-9616-a6744f8f3bdf.png">

I have tried several different cards from a 32GB scandisk to a 128Mb no-name and all have the same results. The only way to get a connection back is to place a fresh version on the card and remove the FIRMWARE.CUR

I have also tried the previous version of grbl-LPC

Any help would be much appreciated.

**Comment by fergusfp** [comment]
This Morning I found a link to this conversation https://github.com/LaserWeb/LaserWeb4/issues/322 and so I altered my .env file to include 

RESET_ON_CONNECT=1
GRBL_WAIT_TIME=10
FIRMWARE_WAIT_TIME=30

But still no difference for me. 

Can you please tell me if I am putting the .env file in the place? I have included this photo, 
<img width="765" alt="place" src="https://user-images.githubusercontent.com/12587072/44307016-e063f500-a392-11e8-8742-bf9d9ba6227e.png">
Thank you

**Comment by fergusfp** [comment]
Just to confirm the board and firmware are working correctly, outside of laserweb coolTerm has no problem talking to the board. 

<img width="689" alt="coolterm" src="https://user-images.githubusercontent.com/12587072/44307155-3174e880-a395-11e8-95a8-8cbd5a5d9fe9.png">

But still no communication with laserWeb after initial boot.

Thanks

**Comment by cprezzi** [comment]
Grbl-LPC (like every grbl) sends a welcome string after each USB connect. LaserWeb is waiting for this string to identify grbl (for communication compatibility) and if the string is not received within GRBL_WAIT_TIME the connection is closed.

Do you use a direct (good quality) USB cable between the Mac and the MKS board? Or some USB2serial modem?

**Comment by cprezzi** [comment]
I also use a MKS SBASE V1.3 with grbl-LPC, but with Raspberry Pi as Server and I don't have these problems.

**Comment by cprezzi** [comment]
I remember that there was a problem with OSX and the .env file. 

@jorgerobles do you remember if this problem was solved an how?
