### ISSUE TITLE
SyntaxError: Unexpected token Raspberry pi install

### ISSUE THREAD

**Issue by Benjin454** [LaserWeb/LaserWeb4#510]
Info:
- Raspberry pi 3 model B
- Running raspbian stretch
- Following install instructions from https://github.com/LaserWeb/LaserWeb4/wiki/1.4-Installation-on-RaspberryPi

Hello, I am trying to install LaserWeb4(lw.comm-server) on my raspberry pi. The install went smoothy until executing this command "node server.js". I am receiving the following error:
![screen shot 2018-08-26](https://user-images.githubusercontent.com/10505629/44633927-7ed5f480-a957-11e8-917f-eb0760b6e65c.png)

Let me know if there is any other information I can provide.

**Comment by cprezzi** [comment]
Ups, my fault. I pushed my changes yesterday before I fixed this error. It's fixed now.

**Comment by cprezzi** [comment]
If you used git to clone the server, you can just execute a **git pull** to fix it.

**Comment by Benjin454** [comment]
Works now! Thanks!
