### ISSUE TITLE
Status Light Integration 

### ISSUE THREAD

**Issue by Benjin454** [LaserWeb/LaserWeb4#512]
This is a request for status light integration(With raspberry pi and lw.comm-server). For example. When the laser is on, a amber light would turn on. When a grbl alarm is triggered, a red light would flash. When the system is idle, a green light would be on. More technically put maybe a python script running in the background monitoring the status of the machine. "flipping a relay"(Turning a light on) based on the status of the machine. Simply put, sending status messages to a python script.

![edwrdsp00002_30_pe_004](https://user-images.githubusercontent.com/10505629/44813443-6821de80-ab9f-11e8-9cb4-90e29258bfaf.jpg)

![220px-stacklightinstall1](https://user-images.githubusercontent.com/10505629/44811989-acab7b00-ab9b-11e8-8d42-a62bd8ef78a0.png)

 My Contribution/Side notes:
 If someone can get a python script to the point where its printing out each Machine status, I can then add the GPIO relay commands in place of the "print" commands(Rough python example below). I can then test and connect everything, getting the GPIO(Lights turning on and off with relays) side of things working. 

If someone can get a python script to communicate with laserweb/grbl to report the machine status: 
![screen shot 2018-08-29 at 4 56 33 pm](https://user-images.githubusercontent.com/10505629/44817890-978b1800-abac-11e8-9b88-7033d822e747.png)

I can then get the GPIO portion working:

![screen shot 2018-08-29 at 4 56 22 pm](https://user-images.githubusercontent.com/10505629/44817910-a8d42480-abac-11e8-901e-f7c5a3954150.png)

**Comment by cprezzi** [comment]
This is the same request as #511.
I don't want to have hardware dependency in lw.comm-server. In 95% of use-cases the lw.comm-server is compiled into the electron app for a Windows, OSX or Linux executable, which has no GPIO options.

But you are free to make a fork and add this feature yourself.

By the way: You can connect the server with multiple clients at the same time. So you could programm a script that connects to the server as a client (via websockets) to get all the status messages and do what you like :)
