### ISSUE TITLE
Some lines in svg missing

### ISSUE THREAD

**Issue by Peetz0r** [LaserWeb/LaserWeb4#514]
I made this svg file on http://www.makercase.com/ and edited it with inkscape 0.92.3, then tried to cut it with Laserweb 4.0.991/4.0.127, and one set of lines went missing in the resulting gcode.

[Workspace.json and svg in .zip](https://github.com/LaserWeb/LaserWeb4/files/2343679/workspace-and-svg.zip)

Document view:
![screenshot from 2018-09-02 20-55-49](https://user-images.githubusercontent.com/527549/44959793-e27e9580-aef4-11e8-9465-7dd84aa85c67.png)

Gcode view:
![screenshot from 2018-09-02 20-55-35](https://user-images.githubusercontent.com/527549/44959792-e27e9580-aef4-11e8-8367-2359310bfaf0.png)

**Comment by Peetz0r** [comment]
Possible duplicate of #442 and #446.

**Comment by cprezzi** [comment]
It's known that LW could have some problems with makercase files. The problem is mostly caused by two lines on top of each other. A possible workaround is to separate the different parts (move apart).

**Comment by valdasa** [comment]
same thing happens with coreldraw exports, but funniest thing that if you use same file on laserweb3 old version everything is ok

**Comment by cprezzi** [comment]
Nothing funny or magic at all. LW4 uses a complete different SVG parser than LW3 used, which has many advantages but unfortunately also some disadvantages.

**Comment by valdasa** [comment]
yeah but lw4 parser isn`t working for my needs, it`s super slow generating takes up to couple minutes on i7... and it generates incorrectly. So for raster i use lw4 for cutting lw3.

**Comment by cprezzi** [comment]
@valdasa It's known that CorelDraw doesn't make perfect SVG files. Did you try to import the file into inkscape and save the svg from there?. That could eventually fix some of the problems.

**Comment by cojarbi** [comment]
> yeah but lw4 parser isn`t working for my needs, it`s super slow generating takes up to couple minutes on i7... and it generates incorrectly. So for raster i use lw4 for cutting lw3.

Try using the segment field with a 0.5 value and try again the cut operation.
