### ISSUE TITLE
Laserweb server

### ISSUE THREAD

**Issue by a7hybnj2** [LaserWeb/LaserWeb4#521]
Can someone please clarify if setting up Laser Web on a raspberry pi as a server would have laser plugged into the raspberry pi?

**Comment by cprezzi** [comment]
Can you please clearify what you mean with "laser plugged into raspberry pi"? Do you mean a laser machine plugged in via USB? LaserWeb only supports controllers with one of the supported firmwares (see README.md).

**Comment by a7hybnj2** [comment]
Correct. The laser plugged into the raspberry pi running laserweb server. I am using laserweb now successfully but have it directly connected to the computer that is running laserweb. I want to be able to control this laser over the network.

**Comment by cprezzi** [comment]
Ok, this is exactly what the raspi installation is for. After installing lw.comm-server to the raspi, you can run the frontend, change the server IP once in the "Comms" tab under "Server Connection" from localhost to the IP of your raspi (with port :8000).
