### ISSUE TITLE
GCODE Generation takes forever for basic shapes

### ISSUE THREAD

**Issue by mzeile** [LaserWeb/LaserWeb4#523]
Hello,

I'm having trouble generating GCODE for the Mill Pocket operation for lot's of shapes I've created. The following hardware/software I have tested always with the same result:

- Windows 10 running the latest executable of Laserweb 4.0.996
- Windows 10 + Chrome 70.0.3538.77 + lw.comm-server running on a Raspberry Pi
- For creation of the SVG file I have used latest version of Inkscape (create a circle, create a rect, convert both objects to path, then union them). 
- For the DXF example I have used DraftSight as saved it as R12 DXF (ASCII)

What happens:
![image](https://user-images.githubusercontent.com/6569845/48272730-a1988500-e43f-11e8-83db-502e81f864e2.png)

The generation takes forever. With some other files I've found that it takes ~15 seconds with a 10mm Tool Size and 30 seconds with 8mm Tool Size. With 6mm or even 2mm (what I actually have) I had it running for 60 minutes after which it automatically stops. When I only calculate the box and circle without any intersection it completes after less than a second. I've found one user in gplus who could generate GCODE quite quickly without any issues (from the same example file back then). I however cannot find any reason for that. I've tried it even on 4 different PCs up to now!

You can find the thread on gplus here: https://plus.google.com/communities/115879488566665599508/stream/474dde06-3789-4bf8-b2a9-4c45e3b28db3 - It also includes a lot of other things I've tried to overcome this issue.

The sample SVG and DXF files are uploaded here (they are the most basic ones I could come up with toe reproduce the issue):

https://jmp.sh/A2mMVCG
https://jmp.sh/Ao8pVhH

Other than this issue I'd point out that Laserweb is the best tool I've used on my CNC router so far! Great job!

**Comment by cprezzi** [comment]
Closing because of duplicate post from G+.
