### ISSUE TITLE
"The file has minor issues. Please check document is correctly loaded!", LaserWeb 4.0.996 error

### ISSUE THREAD

**Issue by asasergio** [LaserWeb/LaserWeb4#533]
Windows 10 (64bits)
LaserWeb 4.0.996
Inkscape 0.92.3

Files -> Documents -> Add Document...

![2019-01-04 12_17_04](https://user-images.githubusercontent.com/16887880/50692576-8a2ee000-101b-11e9-9b77-0d9d8d13d402.jpg)

after "Add Document"...

![2019-01-04 12_17_32 b](https://user-images.githubusercontent.com/16887880/50693721-e5ae9d00-101e-11e9-910d-27527b1335c2.jpg)

after Create Single -> Cut Rate -> GCode Generate -> Filter Stroke...

![2019-01-04 14_16_47](https://user-images.githubusercontent.com/16887880/50698457-2660e300-102c-11e9-8371-76b5874f40ac.jpg)

Have been tried with several other SVG files (Inkscape SVG and SVG flat) all resulting in the same error.

Not corresponding to [Youtube "LaserWeb4 Basics - Working with vectors"](https://youtu.be/_0jwzhZL4OU?list=PLCm8o-62Fu2nwrii2o1TTF5u1QC8zxgK0)

Something I did wrong?

**Comment by cprezzi** [comment]
I guess your SVG has only fill color, but no stroke color. Try creating the operation without filter first. If that works, go back to Inkscape and check that stroke color is set.

**Comment by asasergio** [comment]
Perfect,
I include the strokes in the figures generated by Inkscape and now I have the filter working, even though the LW4 continues to report the error.
Thank You very much.

![2019-01-07 18_43_11](https://user-images.githubusercontent.com/16887880/50793128-5d462b80-12ae-11e9-9ed6-dfe285090528.png)

The figure .svg created in Inkscape that can be downloaded for use in the "LW4 Basics - Working with vectors" tutorial...

![inkscape_svg](https://user-images.githubusercontent.com/16887880/50792811-6387d800-12ad-11e9-8d70-df60d70656b5.png)

**Comment by cprezzi** [comment]
The message is just a warning, not an error. Most of the time it still works.
