### ISSUE TITLE
No supported firmware detected (CR-10S Pro, Marlin with RP3B+)

### ISSUE THREAD

**Issue by bangity** [LaserWeb/LaserWeb4#541]
Since google+ is going away in a couple weeks. I am sorry for posting here.

Hello,

This is the error. I normally use baud rate 250000 for 3d printing. Tried that as well but didn't work.

Connecting Machine @ USB,/dev/ttyAMA0,115200baud
 Machine connected
 No supported firmware detected. Closing port /dev/ttyAMA0
 Server error: Port is not open
 Machine disconnected

Octopi was running, stopped the service but still have problem (did not connect to Octopi)

Thank you.

**Comment by cprezzi** [comment]
As written on the G+ community, the new location for community and support is https://forum.makerforums.info/c/laserweb-cncweb
