### ISSUE TITLE
Noob question here :/

### ISSUE THREAD

**Issue by chismah** [LaserWeb/LaserWeb4#543]
I have currently an Eleksmaker running smoothly with the latest Grbl and LaserWeb 4.
Switching to a laptop configuration for my daily use, if I install LaserWeb 4 server on a Pi 3B+, will it be possible to shutdown my laptop once the engraving task is running?
I am not sure to completely understand what the server do, and if the frontend installed on my laptop should be running as well as the server during a laser task.

Regards,

**Comment by cprezzi** [comment]
The server is mainly a gateway between network and machine. At the moment you press `run` the whole gcode will be sent to the server which caches it and streams it to the machine line by line.

So yes, you can theoretically shut down your laptop a few seconds after clicking the run button, but you loose the option to controll the job (pause/abort)!

Please go to https://forum.makerforums.info/c/laserweb-cncweb for further support. We use git issues only for bug reporting.

**Comment by chismah** [comment]
Thanks!
