### ISSUE TITLE
Laser Raster Issue on MAC OS

### ISSUE THREAD

**Issue by txusballesteros** [LaserWeb/LaserWeb4#544]
### Follow this steps to open an issue ###
Hi everyone,

I'm newbie with LaserWeb and I'm plenty thankful with the work did by this community.

So I would like to report an issue that I'm having when I try to burn a raster Image. The problem is that I'm not able to complete the generate process because it never finish. I mean, the process comes to 100% but never finishes.

I'm using the version 4.0.993 on MAC OS
 

<img width="1360" alt="Screenshot 2019-05-15 at 10 26 23" src="https://user-images.githubusercontent.com/8314542/57766199-3c339280-7707-11e9-93fb-e404174295df.png">

[Workspace.json.txt](https://github.com/LaserWeb/LaserWeb4/files/3181998/Workspace.json.txt)

**Comment by cprezzi** [comment]
Did you scale the picture massively down in LW? If so, try to scale it down in a graphics program and load the smaller image in LW.

Try Laser Diameter 0.2mm. That only creates 1/4 of the data (compared to 0.1mm).

(By the way: the most recent version is 4.0.996)

**Comment by txusballesteros** [comment]
Thanks a lot @cprezzi for your answer.
