### ISSUE TITLE
Tool and Macro menus not availabe.  Not able to import backup into new install...

### ISSUE THREAD

**Issue by qharley** [LaserWeb/LaserWeb4#549]
![Screenshot 2019-06-06 18 16 16](https://user-images.githubusercontent.com/855896/59049239-de1e4900-8887-11e9-8dc2-84ef4bf5da2b.png)

The Tools menu is not reacting to click, and neither is the Macro menu.

I resintalled my laserweb using the manual install instructions.  Normally I would install the backup to get everything going, but this time it will not.

pi@laserweb:~/lw.comm-server $ node -v
v10.16.0
pi@laserweb:~/lw.comm-server $ npm -v
6.9.0

Raspian stretch (up to date), Laserweb 4.0.996

**Comment by cprezzi** [comment]
Please go to https://forum.makerforums.info/c/laserweb-cncweb for community support!
