### ISSUE TITLE
Option in setup/settings to choose between mm/s and mm/min

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#55]
Its simple math but have the option to choose either make it more comfortable

**Comment by jorgerobles** [comment]
@cojarbi Setting is stored, now needs propagation.

**Comment by tbfleming** [comment]
It's now in place, but has a bug. If the setting is empty, the CAM assumes mm/min since that's what gcode normally is. The settings UI shows mm/s when the setting's empty.

**Comment by jorgerobles** [comment]
Changed to react-select and pick default value (mm/min) if none exists

2016-12-11 18:47 GMT+01:00 Todd Fleming <notifications@github.com>:

**Comment by tbfleming** [comment]
react-select gives you an object; you need to get just the value from it.

![image](https://cloud.githubusercontent.com/assets/418464/21082520/03c5b09c-bfab-11e6-8171-522af9f51cbc.png)

**Comment by jorgerobles** [comment]
Overlooked. sorry :|

2016-12-11 20:07 GMT+01:00 Todd Fleming <notifications@github.com>:
