### ISSUE TITLE
Operation still present after deleting path

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#56]
Should the operation still be present after deleting the path?

http://recordit.co/WJi7Mtc3pm

**Comment by tbfleming** [comment]
Yes. It allows switching which path(s) the operation uses:

![add](https://cloud.githubusercontent.com/assets/418464/21011047/62e7be48-bd1d-11e6-8227-316651b8939f.gif)

**Comment by cojarbi** [comment]
Makes sense now :)

**Comment by lautr3k** [comment]
Please add label at issue creation and close issue when resolved ;)
