### ISSUE TITLE
Pass depth increment on Laser cut operation

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#57]
For diode Laser mostly a depth increment option should be added.

**Comment by openhardwarecoza** [comment]
Indeed a requirement - Emblaser has a Z axis we need to support

**Comment by jorgerobles** [comment]
hmm.. We should ping our surgeon @tbfleming for operations :)

**Comment by tbfleming** [comment]
It's easy; I just haven't gotten to it yet.

**Comment by jorgerobles** [comment]
Z Stage Settings #69 are up an running

![zstage](https://cloud.githubusercontent.com/assets/1706080/21079874/e2271c4c-bf9f-11e6-90b2-8ddee3dfdf1b.gif)

**Comment by tbfleming** [comment]
Maybe not so easy? I assumed it'd be like CNC, where user set the work offset so Z=0 is where the focal point hits top of material.

**Comment by tbfleming** [comment]
@DarklyLabs How is the emblaser2's Z coordinate going to work? Will it have the work offset so Z=0 is where the focal point hits top of material, or does the CAM need to compute Z based on the options @jorgerobles added?
* Air assist comp (how does this affect Z?)
* Cutting mat comp (is this thickness?)
* Focus height comp (would the machine coordinate system handle this since it's fixed?)
* Default mat thickness (how is this different than cutting mat comp?)

**Comment by DarklyLabs** [comment]
@tbfleming 
The Emblaser works very similar to a CNC router, with some extra features simplify use for the end customer.

A Z value of 0 will relate to the laser being focused exactly on the base plate. The focal length of the laser is 50mm, this means there will be a 50mm gap between the bottom of the laser unit and the base plate.

The parameters the customer enters are the following:
**Material_Thickness** (MT): This is how thick their material is they are working with.

**Cutting_Mat_Thickness** (CMT): How thick the cutting mat is. (0 if none is being used)

**Focus_Height_Compensation** (FHC) is a number determined by running a calibration file. It will be a small positive or negative number that helps compensate for any small variations in each machine for perfect focus. This number is usually set only once.

Therefore:
Height to top of material from the base = MT+ CMT + FHC
Maximum z-movement = (MT + CMT + FCH) - 50mm
The Emblaser can handle materials up to 50mm thick.

The Air-Assist is a slightly different case. When the Air-Assist nozzle is installed, the amount of movement downwards from the top of the material is restricted to 10mm. This is to prevent the nozzle colliding with the material. A checkbox for AA_Installed needs to be available.

Therefore:
Maximum z-movement (with AA_Installed) = (MT + CMT + FCH) - 10mm

**Comment by tbfleming** [comment]
Does positive Z move the bed down? This is how CNC mills would handle a moving bed (opposite direction of a moving tool head).

**Comment by DarklyLabs** [comment]
Our bed is fixed and the laser (tool) head moved up and down.

So positive Z move moves the tool up, further away from the bed.

**Comment by DarklyLabs** [comment]
One thing I left off the z-moves in the info above is that they should not go below 0. Since z=0 is the lowest position of the laser head, going below this would cause the stepper to stall and loose its position.

**Comment by tbfleming** [comment]
![image](https://cloud.githubusercontent.com/assets/418464/21084158/0116003c-bfcd-11e6-92e6-a344b379cd5e.png)

I tried to generalize this. User provides red values. Z coordinate is focal point.

For Emblazer:
* Max Z = 50
* Cut Z Travel Limit = 50 or 10, depending on if air assist is used. 

No checkbox in the general release since the value it toggles (10) is specific to Emblaser. An Emblaser-specific release could hard code Max Z and set Cut Z based on a checkbox. 

Does this look right?

**Comment by DarklyLabs** [comment]
This looks correct.

**Comment by openhardwarecoza** [comment]
![default material thich](https://cloud.githubusercontent.com/assets/7695323/21088338/db3efb1a-c036-11e6-96d8-a26b36ef2e83.PNG)

Just a maybe, but material thickness probably belongs on the CAM tab, not settings.
Settings should be for things that are rarely changed. Something like material thickness likely changes with every job.  In terms of "defaults" - in LW3 we adopted a "last used autosave" instead (not rolled out to all the fields I wanted to yet) 
I think in LW4 we already do that for G0 feedrate? (Stays at same value between page refreshes) 
So for example If I setup a job at 12mm thick material, next time I open LW4 it defaults back to 12, i change it to 6mm, next time I come back, it defaults to 6mm (that way if you have a couple consecutive jobs on same stock of material you dont need to change it for each)

**Comment by DarklyLabs** [comment]
Yes, I agree. 
The material thickness could change every job.
The Cutting Mat thickness, and focus height compensation are changed much less frequently.

**Comment by openhardwarecoza** [comment]
@DarklyLabs does the emblaser have homing on Z?  (Does it home to top or bottom?)

@FabCreator - mayb just chime in here if you have requirements too so we discuss the plan suitably for both (:

**Comment by openhardwarecoza** [comment]
@darklylabs cutting Mat Fitted can also change between jobs (yes/no
setting)  with its height staying in settings?

**Comment by DarklyLabs** [comment]
Homing on the Z is achieved by driving the z axis upwards 60mm. Since there is only 50mm movement this ensures it is always at the top most position.  This position is then set to z=50mm.

**Comment by DarklyLabs** [comment]
With respect to cutting mat, I would think this thickness is suitably placed in the settings section. Customers generally keep this consistent.
A value of 0 would indicate no mat installed.

**Comment by openhardwarecoza** [comment]
Ahh ok.  Cool then.  I dont know what the mat is for (or not)  thought its
something you install when you cut and remove when you engrave for example
(some commercial machinea have a solid bed for engravings,  and a honeycomb
for cutting -  the solid bed allows a better draft over the work to help
with smoke stains)

**Comment by DarklyLabs** [comment]
The mat is the Emblaser equivalent to a honeycomb bed.
It can be left in place for both cutting or engraving. It does take up 10mm of material height so can be removed for customers needing to work on materials that is more than 40mm thick.

**Comment by jorgerobles** [comment]
I'm going to strip down the default mat thickness. Should I add a Max Z Travel to allow generic stages? (So maybe another machine has 100mm travel instead 50..)

**Comment by openhardwarecoza** [comment]
Whatever we do now would benefit from generic thinking (if the plan is to
attract more machine makers over here in due time)
I've asked @FabCreator to look into this thread as well

**Comment by jorgerobles** [comment]
![zstage_settings](https://cloud.githubusercontent.com/assets/1706080/21091809/f0dccfbc-c048-11e6-9401-c44e8e0c1fee.png)

Not commited yet. I've changed field names to a shorter, generic name. We could add ABBR to popup info balloons.  I will commit if no objections.

**Comment by FabCreator** [comment]
Hi all,

The Fabkit works slightly differently we have a moving z bed with approximately 130mm of movement. however knowing these distances are not important for the user for the most part as our machine homes to the material. or in the case of very thin material it will home to the upper Z endstop.
once it homes it bounces off and positions itself 3mm from the head to ensure the perfect focal distance, no need to set material thickness.
However what we would love is a separate home z button (G28Z) 
Another cool feature we would love is to be able to adjust the z depending on what your doing. de-focusing for an engrave can give some interesting effects. As we home to 0 they would need to offset with - values.  Engrave job Z-20, Cutting job Z0 etc (but i think this may have been added looking above)

Im not sure what the air assist max travel does? also what command is the air assist button say? our compressor turns on and off with M106 and M107.

Kind regards,
Bonne

**Comment by jorgerobles** [comment]
Air assist is an especial flag used for emblaser Z algorithm (see upper in this thread). We should work further allowing an easy and flexible way to customize vendor requirements.

**Comment by jorgerobles** [comment]
Z offset could be added to operation parameters, and in fact automatically reflected on material database operation profiles.

**Comment by tbfleming** [comment]
@jorgerobles remove Air Assist; Z Max Travel handles it. Side note: why do all the settings SHOUT LIKE THIS?

I wish Emblaser homed to top of material, that approach is closest to mill setups.

I think this model will work for fab kit with these values:
* Mat Thickness = 0
* Material Thickness = 0 (may confuse users)

We'll also have to drop the Z movement restrictions (Z Max Travel, Cut Z Travel Limit); we don't enforce them on X and Y; why should we enforce them on Z? Emblaser can add Z movement restrictions to a fork.

**Comment by FabCreator** [comment]
@tbfleming movement restrictions are not needed. In the fabkit if you go too far a limit switch is hit.
perhaps hard jogging limits can be added as an option in setting but they should be user editable if they are there at all. 

As the fabkit does not require mat thickness or material thickness Is it possible to hide and show different options dependent on profile selected?

The only z feature we need is a focal offset which could be set per operation so you can play with different engraving line thicknesses.

**Comment by jorgerobles** [comment]
> @jorgerobles remove Air Assist; Z Max Travel handles it. 

As I've understood, should we drop "Air Assist" and "Air Assist max travel" so Emblaser will reimplement on their fork?  Because "Z Max travel" does not tell the machine not to go down if air assist is connected.


> Side note: why do all the settings SHOUT LIKE THIS?

text-transform:uppercase? I put that on css to increase legibility of smaller font-size. Feel free to remove if anyone is offended by an application setting yelling its name. :grin:

> We'll also have to drop the Z movement restrictions (Z >= 0, Z Max Travel, Cut Z Travel Limit); we don't enforce them on X and Y; why should we enforce them on Z? Emblaser can add Z movement restrictions to a fork.

About Z restrinctions,  Z max travel could be renamed to Machine Depth?

**Comment by openhardwarecoza** [comment]
We definitely dont want to maintain two forks.  I suspect what we are
saying here is: mat is just normal offset less 10mm so might as well just
have that profile set it to 40?

**Comment by FabCreator** [comment]
@openhardwarecoza is it not possible to address these differences in profiles and settings? check boxes to make different features available etc

**Comment by tbfleming** [comment]
> About Z restrinctions, Z max travel could be renamed to Machine Depth?

Renaming doesn't help. Having the Z restrictions at all will break machines which home to the top of the material. Emblaser has an odd setup where Z >= 0. FabKit has a normal milling-style setup where Z <= 0.

**Comment by openhardwarecoza** [comment]
I have a very strong belief in the Cartesian standard. If emblaser isnt
following it it might just be an oversight which we can convince them of?

**Comment by tbfleming** [comment]
> @openhardwarecoza is it not possible to address these differences in profiles and settings? check boxes to make different features available etc

I'm trying to avoid this since having multiple rule sets complicates the CAM code. I think I have a model which works with both machines, except it won't enforce Emblaser's Z restrictions.

**Comment by tbfleming** [comment]
> I have a very strong belief in the Cartesian standard. If emblaser isnt
following it it might just be an oversight which we can convince them of?

Please convince them! Unfortunately it's probably too late; too close to shipping.

**Comment by openhardwarecoza** [comment]
Well,  it really only involves a quick change in the smoothie configs (:

At the end of the day I am very much in favour of standards.  If/else cases
is dev hell.  Stick to the standard then your (product here)  works with
every (other product here)

**Comment by FabCreator** [comment]
@tbfleming fair enough :) 
I think software limits of axis are best left to the firmware config. i know smoothie has plans for implementing this but i am not sure how far away they are from it working. 
Cant the E2 invert the z axis to make 0 the top and -60 the base? this should correct the issue? currently surly you are jogging your axis inverted anyway??

**Comment by tbfleming** [comment]
@openhardwarecoza It means adding a switch to the toolhead which touches off on the material.

**Comment by tbfleming** [comment]
@FabCreator The E2's direction is correct. It's their 0 position that complicates things.

**Comment by tbfleming** [comment]
Here's an ordering of potential Z=0 positions from best to worst:
* Top of material
* Top of base plate (E2)
* Top of travel (will cause massive confusion)

**Comment by openhardwarecoza** [comment]
Ahh ok thought direction was reversed.

As I understand it then, home is to Z max and smoothie is configured with a
max endstop and 50mm axis length.  Homing Z sets workPos to Z50
So if i have a material loaded of 6mm thickness,  and the cutting mat,  my
cut height (if focusing on top of material)  is Z16? As i do a multiple
pass cut i drop down to Z0.5 on the last pass?

**Comment by openhardwarecoza** [comment]
(: we should ask Domenic to stay up tomorrow night so we hash this out
without timezone hell

**Comment by tbfleming** [comment]
@openhardwarecoza yes.

**Comment by tbfleming** [comment]
It's 6am here. I'm online because of sleep troubles.

**Comment by FabCreator** [comment]
mmm what about setting Z zero before the start of every job after its been positioned for the material focused and re home at the end of every job?

**Comment by DarklyLabs** [comment]
I'm here. All this commotion woke me up!

To catch me up, what is the problem with the z=0 being the lowers position for the laser. Why does it make more sense to set the z=0 at the top of the laser height then go negative?

**Comment by tbfleming** [comment]
@FabCreator that'd simplify CAM, but unless E2 adds a touch off sensor that'd be too hard on users.

**Comment by DarklyLabs** [comment]
The Emblaser does not have material height detection and hence relies on customers entering their material thickness.
It does not seem unreasonable so I am not sure what this discussion is trying to get us to change?

**Comment by tbfleming** [comment]
@DarklyLabs top of laser height would be worse that what you have now. The best user experience would be for a sensor to home Z=0 at top of material. It'd also simplify CAM config. If you can't add a sensor, then keep it as is. We just won't enforce the Z restrictions.

**Comment by openhardwarecoza** [comment]
@todd isn't the idea here that homing is irrelevant and start gcode moves
the z offset + mat then sets the WCS to match so work z0=top?

**Comment by DarklyLabs** [comment]
@tbfleming Ok. We can add the z-restrictions to our release of the software since is is very specific to our needs.

**Comment by tbfleming** [comment]
@openhardwarecoza If the user always used the exact same material thickness.

**Comment by openhardwarecoza** [comment]
Thats why i say,  couple lines above,  material height needs to be on cam
tab.  Also what @jorgerobles said,  material height in the material db

**Comment by DarklyLabs** [comment]
@openhardwarecoza We can enforce z-homing at the start of every job. It only takes a couple of seconds to perform. Then we can use the WCS idea and the material height etc to set z=0 being the top of the material as you suggest.

**Comment by tbfleming** [comment]
@DarklyLabs in that case, material height should move to the jog tab.

**Comment by DarklyLabs** [comment]
@tbfleming Do you suggest this to prevent material collision?

**Comment by tbfleming** [comment]
@DarklyLabs Traditionally, setting up WCS is a machine control function, not a CAM function. The Jog tab handles machine control.

**Comment by openhardwarecoza** [comment]
But in this case we do (already in lw3)  handle wcs for the user.  Laser
users are artists mostly.  They dont need to know what wcs is.  Just that
we do it for them

**Comment by DarklyLabs** [comment]
There is a fine line between what is 'traditional' and what makes software easy to use for the end customer. We would hope LW4 was not a 'technical' application to use. There are many of those types of programs out there already.

**Comment by tbfleming** [comment]
We could have this in the jog tab:
* Home Z button. Both machines need this.
* A button that sets WCS Z based on various machine settings + a material thickness field. E2 needs this.

**Comment by tbfleming** [comment]
Operations would have a Z Offset field for defocusing (e.g. for engraving) and a Z depth per pass field.

**Comment by openhardwarecoza** [comment]
@DarklyLabs - agreed on the sentiment - LW must stick to its roots of
hiding the difficult (;

**Comment by tbfleming** [comment]
We don't have to call it WCS. We could call it Set Z0, or Set Material Top. Or maybe roll that functionality into the Home Z button.

**Comment by tbfleming** [comment]
Or, we could drop WCS, and go back to my original idea (the diagram, minus the Z limits).

**Comment by jorgerobles** [comment]
So, any agreement on this front?

**Comment by DarklyLabs** [comment]
We have been thinking about how to generalise our requirements:

- Our preferred scenario is the base plate Z=0.

- A material_thickness value is used to define the top of the material from the base plate.  This material_thickness value would take into account the thickness of any cutting boards or mats being used.

- We use the general principle of 'Tool Offset' to take into account any focus compensation value required. So, after each machine runs a calibration process, the 'tool_offset' value is determined. This value would be entered once and used in gCode calculations.

- A  'tool_offset' variable could be incorporated into the gCode calculations and by default be zero. If this variable is not exposed to general users, we could expose it in the Emblaser release of LW.

- Any specific logic required for limitations to movements etc would be specifically added into the Emblaser release of LW.

This involves Darkly maintaining their own branch of LW, but I can't see any other solution without implementing our specific requirements in the the master branch.

![e2 z-axis theory](https://cloud.githubusercontent.com/assets/14358950/21291281/d63be100-c52c-11e6-85a9-85b506f4e2e6.png)

**Comment by jorgerobles** [comment]
I see generic enough, Tool offset seems a parameter more machines could use, and Material thickness is already stored on material database. I should keep also air assist as a flag any machine could use.

About forking, I propose doing a plugin system (or postprocessor) so you could introduce your requirements easily (@tbfleming, any thoughts )

**Comment by DarklyLabs** [comment]
@jorgerobles I really like the idea of a post processor. This is exactly how we work with the Vectric software on our Emblaser 1 machines.

**Comment by DarklyLabs** [comment]
@jorgerobles  @tbfleming  Just looking at the current LW4, the 'Use A-Axis' feature is very similar to what we would need for our Z-Axis needs.

A button called 'Use Z-Axis' would reveal a parameter for material thickness. That is all that's needed since 'tool offset' is already taken into account in the Machine Settings.

**Comment by jorgerobles** [comment]
And then Z Gcode would be calculated with Material thickness and Number of passes?

**Comment by DarklyLabs** [comment]
Yes.
If the user entered a material thickness of 10mm, then the starting z value for the z axis would be:
First pass = 10mm + tool_offset
Second Pass = 10mm + tool_offset - pass_height
Third pass...

I also now see that there needs to be a pass_height value. This was included in LW3 but I don't see it in LW4. This is the distance the z-axis changes with each pass.

**Comment by tbfleming** [comment]
Here is my revised plan:
* Settings will have
  * Laser Z Stage (won't affect milling)
  * Laser Z Offset
* Laser Operations will have (Only if Laser Z Stage on):
  * Starting Z
  * Pass Height

First pass = Starting Z + Laser Z Offset
Second pass = Starting Z + Pass Height + Laser Z Offset

"Material thickness" would confuse users with machines which touch off on the material top. "Starting Z" seems more clear.

**Comment by tbfleming** [comment]
Correction:
Second pass = Starting Z - Pass Height + Laser Z Offset

**Comment by DarklyLabs** [comment]
@tbfleming Sounds good Todd.

**Comment by jorgerobles** [comment]
@tbfleming, @lautr3k, What would be an scenario where a raster operation will have passes and Z staging? Is feasible?

**Comment by openhardwarecoza** [comment]
3d relief engravings maybe? https://youtu.be/gXc0jnqZYuA

**Comment by jorgerobles** [comment]
Then where's the best place to do this? @lautr3k what do you prefer, adding the passes, startingZ and passHeight on your code, or should be handled by LW4 code?

**Comment by openhardwarecoza** [comment]
I did say maybe,  not sure if @DarklyLabs needs Z on rasters...

**Comment by jorgerobles** [comment]
Yes, I've had a conversation with @DarklyLabs earlier about this. 

> 1: There will be a check-box in the settings which is called ‘use z-axis’, or something like that.
> 2: When selected, users will be presented with some extra options when setting up a **cutting or raster process**:
> 1. top of material height
>This will define the starting height of the z-axis.
> 2. z-move per pass
>This will set the distance the z-axis moves with each pass.

**Comment by jorgerobles** [comment]
Another scenario:
I've got two operations:
One of them use startZ 50, 3 passes, 1mm passDepth
The other use 1 pass, no passDepth, no startZ

Where should be placed the start Z of the second path? should it do a homing before?

**Comment by jorgerobles** [comment]
I've managed to put the raster passes on LW, no need to touch @lautr3k, maybe the header is  generated each pass (the comment headers) if so, please implement a flag to skip these headers on the next passes. `raster.run({headers:false})` by example.

@openhardwarecoza, @DarklyLabs  and others, please take a look and tell me what to do on multiple operations (https://github.com/LaserWeb/LaserWeb4/issues/57#issuecomment-276635993)

**Comment by DarklyLabs** [comment]
Tested gcode generation with the pass depths for both vector and raster and it appears to be working correctly.

The only thing not taken into account is the 'tool offset' value from the machine settings. This value should be added to the 'Starting Height'.

**Comment by DarklyLabs** [comment]
For multiple operations, it looks like it is behaving as expected.
Users would enter their starting height for each operation as required.

**Comment by DarklyLabs** [comment]
@jorgerobles Can this be closed now?
