### ISSUE TITLE
Where is the AppImage for linux?

### ISSUE THREAD

**Issue by emteeoh** [LaserWeb/LaserWeb4#578]
All the documentation says there's a build for linux in LaserWeb4-binaries, but every link seems to be dead. https://github.com/LaserWeb/LaserWeb4-Binaries/releases doesn't have anything for Linux, and the readme.md at https://github.com/LaserWeb/LaserWeb4-Binaries/ refers to a non-existent Amazon S3 bucket ( http://laserweb-release.s3-website-us-east-1.amazonaws.com/ ) Is there an AppImage build? Or is the documentation out of date?

**Comment by cprezzi** [comment]
@emteeoh Please read the other issues before asking the same question again. See: https://github.com/LaserWeb/LaserWeb4/issues/576
