### ISSUE TITLE
job simulation whith relative cordinates (G90)

### ISSUE THREAD

**Issue by ithinkido** [LaserWeb/LaserWeb4#586]
When I am running a job from Gcode using relative co-ordinates , I get a perfect rendering on screen of the job, but the actual blue laser pointer is not moving on the rendering when the job is running, rather the whole rendering + blue dot ( laser) is moving around the screen.  Is there a way to see the simulated position of the laser durring the job ?

[Laserweb-Workspace.zip](https://github.com/LaserWeb/LaserWeb4/files/4136763/Laserweb-Workspace.zip)

**Comment by cprezzi** [comment]
Do you use a GRBL baser controller? 
If so, do you have conigured $10=0 as recommended?

**Comment by ithinkido** [comment]
Nope, I was not using $10=0. That was my problem. Thanks.
