### ISSUE TITLE
Multiple passes on each element, with one full path?

### ISSUE THREAD

**Issue by RafaLibrenz** [LaserWeb/LaserWeb4#598]
I'm using LaserWeb4 in Windows 10.

It is possible to do multiple passes on each element, with the machine doing the full path just one time? 

And I like to create the gcode with 1 command at all, not 1 command per ellement. 

Example of time-efficient cutting path:
- Positioning to cut circle A. 
- Cut circle A, pass1. 
- Cut circle A, pass2.
- Positioning to cut circle B.
- Cut circle B, pass1. 
- Cut circle B, pass2.

Example of time-inefficient cutting path:
- Positioning to cut circle A. 
- Cut circle A, pass1. 
- Positioning to cut circle B.
- Cut circle B, pass1. 
- Positioning to cut circle A. 
- Cut circle A, pass2. 
- Positioning to cut circle B.
- Cut circle B, pass2.

Imagine this example with hundreds of elements. It's a lot of work of positioning, for nothing. 

Thanks.

**Comment by cprezzi** [comment]
Unfortunately this is not possible in LaserWeb.

You could segment your file into different areas with different colors, so you could use the color filter of LW to define operations for these color areas instead of the whole file.
