### ISSUE TITLE
laserweb not recognizing filled vector shapes when saving an SVG out of Illustrator CC2019

### ISSUE THREAD

**Issue by hannahloh** [LaserWeb/LaserWeb4#600]
Hi,  I am having issues with SVG files saved out of Illustrator CC2019 on my macbook pro. I am saving them out with the correct SVG settings (style attributes etc.), but laserweb keeps turning a solid shape into an outline. See the green in the attached file. Everything in the file is either a vector shape or outline. I am trying to run a Laser Fill Path for the green area. I have been running laser web for a few years (on a PC), and this has never been an issue until the last couple months on my new Mac. Sometimes, if I unistall and reinstall Laserweb, the Laser Fill Path will work the first time. But then, when I reopen laserweb and try to duplicate the same file, Laserweb no longer recognizes the filled shape. The Laserweb version I have is the last one I could find with a .dmg file for a Mac, and doesn't look like it might be the most recent version. Is this an issues that's been fixed and there just isn't an update version for Mac? Can you help?
![pasque flower 2](https://user-images.githubusercontent.com/67527627/85935509-fe63e000-b8ae-11ea-8a0f-4d481e403772.jpg)

**Comment by cprezzi** [comment]
That's how LaserWeb works. Only outlines are detected. LW does not know what to do with fill colors. 
Instead you need to define a "laser fill path" operation in LaserWeb with the params you like for the infill.
