### ISSUE TITLE
Electron-Packager: syntax error: cannot use import statement outside a module......

### ISSUE THREAD

**Issue by mfadel85** [LaserWeb/LaserWeb4#602]
Thank you everyone,
I am trying to generate an executable file in windows using electron-packager, no error happened but when I run the generated execuatble file in windows 10 it shows 
syntax error: cannot use import statement outside a module......
How can I solve this problem? Or how can I force electron-packager to use node 10, will it work?
I attached a screenshot of the message error when running the generated windows application

>node -v
v10.16.3

![screenshot-syntax-error](https://user-images.githubusercontent.com/612694/89497867-db89ed00-d7c5-11ea-8244-605f71edb53e.png)

tried to pakage only the server part: lw.comm-server and got this error 

![screenshot-syntax-error-server](https://user-images.githubusercontent.com/612694/89500192-fb231480-d7c9-11ea-969c-bec43dec1f8d.png)

Best Regards

**Comment by cprezzi** [comment]
Did you follow the "How to compile" giude in the wiki?
https://github.com/LaserWeb/LaserWeb4/wiki/How-to-compile

**Comment by mfadel85** [comment]
> Did you follow the "How to compile" giude in the wiki?
> https://github.com/LaserWeb/LaserWeb4/wiki/How-to-compile

it worked, thanks,
