### ISSUE TITLE
Gcode pocket generation hangs on this simple SVG outline

### ISSUE THREAD

**Issue by nuxeh** [LaserWeb/LaserWeb4#603]
Thanks for the really useful program!

This simple SVG outline hangs each time I try to generate a mill pocket for it, but works fine for other kinds of machining.

[Laserweb-Workspace.json.txt](https://github.com/LaserWeb/LaserWeb4/files/5040286/Laserweb-Workspace.json.txt)
[base-pt2-cutout.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/5040293/base-pt2-cutout.svg.txt)

**Comment by nuxeh** [comment]
Actually, seems similar to #601

**Comment by nuxeh** [comment]
Changing stepover to 80% seems to get it to work

**Comment by cprezzi** [comment]
Thank's for the info. 
This seems to have something to do with memory usage, as 80% stepover reduses the amount of lines.
