### ISSUE TITLE
Send messages if job is done

### ISSUE THREAD

**Issue by Dane809** [LaserWeb/LaserWeb4#604]
Is there an option like mqtt or something like that to send a message at the end of a job?

**Comment by cprezzi** [comment]
There is an option to run shell commands at jobStart, jobAbort or jobEnd. This only works with the source version of lw.comm-server, but not with the compiled installer (exe)! 

You just need to add one of the following lines to config.js in the installation folder:
```
config.jobOnStart = 'your command';
config.jobOnFinish = 'your command';
config.jobOnAbort = 'your command';
```

**Comment by Dane809** [comment]
Thx, that´s what i´m searching for
