### ISSUE TITLE
Export/import machine settings

### ISSUE THREAD

**Issue by Dane809** [LaserWeb/LaserWeb4#605]
I want to export/import my individual machine settings. LaserWeb run on a raspberry. 
On my tower and notebook are different settings. So I think the settings were stored in the browser cache.
If i clean my browsercache, cookies, ... all settings are on default.
Can someone help?

**Comment by cprezzi** [comment]
There are buttons to load/save Settings and Machine Profiles in the Settings Tab under Tools.
