### ISSUE TITLE
Support for Marlin 2.X?

### ISSUE THREAD

**Issue by Sebbb** [LaserWeb/LaserWeb4#606]
Hello,

is be possible to add support for Marlin inline power commands?

E.g.
```
G1 X1 S255
```

The generated gcode is already very similar, but for me, with the Marlin profile the S attribute is "stripped" (I tried to understand the source, but I don't understand why that happens). When using the normal profile, the G1 prefix is missing on most lines, which does not work with Marlin.

So, with the "Default" generator it looks like
```
G1 X21.36 Y4.90 S9.0000
X21.46 Y4.90 S39.0000
X21.56 Y4.90 S80.0000
```
and I need to add G1 to line 2+3

With "Marlin" generator
it looks like
```
; stripped: S0.0000
G0 X21.31 Y4.90
; stripped: S9.0000
G1 X21.36 Y4.90
```
It's easy to add the G1 in the normal output with sed, but that's an additional step.

So, if just the "S" attribute would not be stripped when using the Marlin generator, that would be perfect.

Sebastian

**Comment by cprezzi** [comment]
I don't know much about Marlin, but according to the gcode specs G0 to G3 should be modal, which means the Gx is not needed on consecutive moves of the same type. This makes the command line shorter and therefore the transfer faster.

You should open an issue at the marlin repo to let them make G0-G3 modal.

**Comment by Sebbb** [comment]
Thanks for the reply. As you already have a Marlin gcode generator, would it not be good to have the generated gcode complete -> to add the S attribute also to the generated code, instead of stripping it (why is it stripped anyway)?

**Comment by cprezzi** [comment]
That would make the generator icnompatible with older marlin versions. The S param was stripped away because marlin did not accept it until now.

**Comment by Sebbb** [comment]
That makes sense. As it's implemented since Marlin 2.0.6 now, would it be possible to have a flag, for which Marlin version gcode should be generated, or to disable stripping of params?

**Comment by Sebbb** [comment]
Short update:

Marlin has an option to make Group-1 g-codes modal:

#define GCODE_MOTION_MODES  // Remember the motion mode (G0 G1 G2 G3 G5 G38.X) and apply for X Y Z E F, etc.

So maybe it makes sense to simply rename the "Marlin" gcode generator to "Marlin 1", as Marlin >=2.0.6 perfectly works with the default generator. And to document the needed compile flag.

Unfortunately, this is incompatible with Octoprint for now, as it does not wait for "ok" confirmations anymore, but tries to spool the whole file at once. But that's a different story..

**Comment by cprezzi** [comment]
Good catch! Thank you.

PS: I don't see the relation between Octoprint and LaserWeb. LW does not need Octoprint (we have our own lw.comm-server, which can be installed on a network PC or Raspberry Pi for machine connection.

**Comment by Sebbb** [comment]
You know, never change a running workflow :) But I see the benefits of using specialized software. So I'll definitely give it a try 👍
