### ISSUE TITLE
Limit Switch Functionality 

### ISSUE THREAD

**Issue by mfadel85** [LaserWeb/LaserWeb4#610]
Hi everyone,
I searched for Limit Switch functioanality in the software, but I could not find, 
if the CNC machine has passed a certain limit is there a way to send signal to stop? We have the Limit Switch in our CNC, but couldnot find it in the software,

any clues?
Best Wishes

**Comment by cprezzi** [comment]
LaserWeb doesn't control your machine, it just creates gcode and sends it to the controller. The only thing you can configure in LaserWeb is the (theoretical) work area of your machine (see settings / machine / dimensions).

The limit switches are handled by your controller firmware. The settings depend on the firmware used. Please check the documentation of your controller firmware.

**Comment by mfadel85** [comment]
thank you
