### ISSUE TITLE
GCode from Lightburn not valid

### ISSUE THREAD

**Issue by JoeCotty** [LaserWeb/LaserWeb4#616]
Hello,

if I create gcode from Lightburn and load it in Laserweb the file isn't showing correct and can not be printed.
I reduced the gcode to a small example. Loading it to online gcode interpreters it is shown correct.

; LightBurn 0.9.18
; GRBL device profile, absolute coords
; Bounds: X0.5 Y0.55 to X25.5 Y25.45
G00 G17 G40 G21 G54
G90
M4
; Scan @ 1250 mm/min, 100% power
M8
G0X15.34Y0.55
; Layer C00
G91
G1X0.68F1250S255
G1X0.17Y0.1S0
G1X-1.04S255
G1X-0.09Y0.1S0
G1X1.24S255
G1X0.07Y0.1S0
G1X-1.47S255
G1X-0.16Y0.1S0
G1X1.69S255
G1X0.04Y0.1S0
G1X-1.88S255
G1X-0.15Y0.1S0
G1X2.06S255
G1X0.03Y0.1S0
G1X-2.24S255
G1X-0.14Y0.1S0
G1X1.37S255
G1X0.24S0
G1X0.78S255
G1Y0.1S0
G1X-0.71S255
G1X-0.55S0
G1X-1.26S255
G1X-0.13Y0.1S0
G1X1.19S255
G1X0.69S0
G1X0.77S255
G1X-0.01Y0.1S0
G1X-0.81S255

Any ideas ?

**Comment by cprezzi** [comment]
This is not the way LaserWeb is ment to be used. You should load your graphic (svg, jpg, png) into LaserWeb, and use the integrated operations & gcode generator. LW4 is not just another gcode streamer.
