### ISSUE TITLE
Step and repeat function missing + rotated table (-Y, -X) and homing help + newer OSX version?

### ISSUE THREAD

**Issue by NikhajZzz** [LaserWeb/LaserWeb4#617]
OSX, Laserweb 4.0.966

1. is there a newer version for OSX than 4.0.996? 4.0.998-136 dmg file?

2. Missing step&repeat a lot. We cut boxes from paper for testing the new constructions.

3. Our laser has a turned table, our home with sensors is upper right corner. This is because we need to place larger sheets into the machine. I cannot solve to turn the table in laserweb settings, using $3=3 sets the home position wrong. Machine bounds problems. I have to use negative coordinates now, but i want to turn it into positive, so -250mm should be translated into 250mm - same as the table with bottom left homing. Please help me to solve this! 
 
![screenshot 2020-12-04 o 9 34 21](https://user-images.githubusercontent.com/16097676/101141120-2270dd80-3614-11eb-8626-7287be8d12ee.png)
![screenshot 2020-12-04 o 9 33 16](https://user-images.githubusercontent.com/16097676/101141129-24d33780-3614-11eb-8b0c-eecc932a0983.png)

**Comment by ghost** [comment]
I wonder if the homing direction config parameters would help you?
https://3dtechworks.ca/2020/02/12/grbl-settings-and-calibration/

$22=1 (homing cycle, bool) – enable/disable homing cycle
**$23=3 (homing dir. invert mask: 00000011)** – sets direction of travel for homing cycle for each axis. Last 3 bits set direction for ZYX respectively
$24=200.000 (homing feed, mm/min) – speed of movement for last part of homing cycle
$25=1000.000 (homing seek, mm/min) – speed of movement for first part of homing cycle
$26=50 (homing debounce, msec) – debounce time in milliseconds for homing switches
$27=1.0 (homing pull-off, mm) – amount of pullback when homing routine hits a switch. Ensures that switches are not still activated after homing cycle if limit switches are enabled.

**Comment by cprezzi** [comment]
1. The newer releases are in the Binaries Repo: under https://github.com/LaserWeb/LaserWeb4-Binaries/releases

2. If step&repeat means to cut an object, then move to a unused material position and cut the same object again then you might solve this by using macros. 

    For exapmle, if your object is 90x90mm, then "program" the folowing macros:
    -  Macro 1: move the work origin by 100mm in x direction
    -  Macro 2: move the work origin by 100mm in y direction

    This way you could run the job, then run macro 1, run the job, run macro 1, run the job... (until you reach max x), then     home, run macro 2, run job, run macro 1, run job...

3. Homing is a grbl configuration, not LaserWeb. Please read the soft limits, hard limits and homing sections of grbl wiki:  
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Configuration#20---soft-limits-boolean

    There is a machine coordinate system, which origin is set by homing, and there is the work coordinate system, which origin can be set by clicking the set zero button. LW only works with the work coordinate system ($10=1)!
 
    Having the homing switches on top right means that the machine bed is in negative X/Y according to machine coordinates, but if you set the work origin to front left, you work in the positive space.
