### ISSUE TITLE
Inkscape "hershey text" stroke font not parsed properly (groups/transforms) 

### ISSUE THREAD

**Issue by risacher** [LaserWeb/LaserWeb4#619]
Rendered some text in Inkscape, then used Hershey Text extension to convert to a stoke-font path.   When imported into LaserWeb, all the letters are on top of each other and the wrong scale.  

Workaround: if I ungroup the paths completely, it imports okay.   I suspect that this is a problem with processing the translation and scaling of grouped paths.

examples attached

[ssa-address.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/5767092/ssa-address.svg.txt)
[ssa-address2.svg.txt](https://github.com/LaserWeb/LaserWeb4/files/5767094/ssa-address2.svg.txt)

**Comment by cprezzi** [comment]
I guess this is either a problem in the Hershey Text extension or the SVG parser we use in LW4. Neither of them is under our control.
