### ISSUE TITLE
gitignore missing dist?

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#62]
Not sure, but I just commited some code (git add -A as usual lazynss) and the /dist/ files got included. 
Shouldnt dist be gitignored?

**Comment by jorgerobles** [comment]
uhm, In my opinion, yes it should (#13). First shot on google thrown
http://stephenplusplus.github.io/yeoman.io/deployment.html that tell that moving dist to a subtree is a good idea.

**Comment by openhardwarecoza** [comment]
Doh!  @tbfleming says exactly that in
https://github.com/LaserWeb/LaserWeb4/issues/13#issuecomment-254563520
Sorry!  Wont happen again (: 'git add src'  then next time

On Dec 10, 2016 10:57 AM, "jorgerobles" <notifications@github.com> wrote:

uhm, In my opinion, yes it should (#13
<https://github.com/LaserWeb/LaserWeb4/issues/13>). First shot on google
thrown
http://stephenplusplus.github.io/yeoman.io/deployment.html that tell that
moving dist to a subtree is a good idea.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/62#issuecomment-266190911>,
or mute the thread

**Comment by openhardwarecoza** [comment]
http://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore
says there are ways of handling existing files...

**Comment by jorgerobles** [comment]
Done and running!

**Comment by openhardwarecoza** [comment]
Thanks (:

**Comment by tbfleming** [comment]
I'll purge the existing generated files from dist, that way .gitignore can do its job well.
