### ISSUE TITLE
Live view of cutting / engraving process

### ISSUE THREAD

**Issue by bman2000** [LaserWeb/LaserWeb4#622]
### Follow this steps to open an issue ###

Feature request

Love the program but would like to have the live preview show the spindle / laser head move indicating it's location and job progress.

The live jog seems to provide this but disables itself once the run job button is pressed

Thank you

Bernie

**Comment by cprezzi** [comment]
LaserWeb should show the live head position while a job is running. If it doesn't, you need to check your firmware configuration. 

If you use grbl (for example), then make sure that $10=0.
Check https://laserweb.yurl.ch/documentation/initial-configuration for details.
