### ISSUE TITLE
Reprap firmware issue

### ISSUE THREAD

**Issue by tomlop33** [LaserWeb/LaserWeb4#626]
I I’m using laser web with reprap firmrware and i have a problem with laser cuting.

Reprap firmware need a S power in each Line on the gcode note only at the begining

Something like that :
G1 x15 S255
G1 x25 x10 S255
…

How can I do this or is that possible to implement this functionality ?

Thanks !

**Comment by cprezzi** [comment]
Just apply the "Generic GRBL machine" profile. This loads the default settings for this style of gcode.
Eventually you need to change "GCODE START" from M4 to M3 and adjust the "PWM MAX S VALUE".
