### ISSUE TITLE
RasPi 4 install?

### ISSUE THREAD

**Issue by SiegeMstr** [LaserWeb/LaserWeb4#629]
I am trying to install LW4 on a RPI4/8Gb, and have vigorously searched but have been unable to find updated install instructions.

I have tried these, each with a clean install of the OS: 
1. https://laserweb.yurl.ch/documentation/installation/36-install-raspberry-pi
2. https://github.com/LaserWeb/lw.comm-server/wiki/Manual-Installation-(RasPi)
3. https://forum.makerforums.info/t/installing-server-on-a-raspberry-pi-zero-w/84007 (last ditch effort)

**Comment by cprezzi** [comment]
Please provide more details! What errors do you get?

**Comment by SiegeMstr** [comment]
The error I was able to read was something about the serial port. I am running the install one more time to get the errors

**Comment by SiegeMstr** [comment]
I discovered the source of the error...I had mistakenly installed a new version of Node than Node 10. After forcing install of Node 10 it is working properly.
