### ISSUE TITLE
Is Raspberry Pi support still maintained?

### ISSUE THREAD

**Issue by github-throwaway** [LaserWeb/LaserWeb4#632]
I tried to install LaserWeb on my Raspberry Pi 3 B+, which is already running OctoPrint. However, I was unable to get this to work. Logs will follow in the new year. 🎄

**Comment by cprezzi** [comment]
Yes, it is. But the wiki was not up to date. We need Node 12 now. 
Please see https://laserweb.yurl.ch/documentation/installation/36-install-raspberry-pi.
