### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by remi75** [LaserWeb/LaserWeb4#654]
Hi,
I think a graphical status view/preview would be nice and

the number of lines in the queue, in the top left,is ok but meaningless without what the total is, so we see a ration...kinda of percentage left/done.

the virtual tool on the graphic preview in the approximate real position too, it is being done by most cnc/engraver software.

also maybe a cursor following thru the view of the g-code ... help-full in debugging situations (gcode-wise)

cheers

**Comment by cprezzi** [comment]
The virtual tool position alredy follows the machine if grbl is correctly configured. Especially $10=0 is important for this to work.

**Comment by remi75** [comment]
$10=0 made it, thank you.
