### ISSUE TITLE
Scaling changes origin point

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#66]
Place a path into some coordinates. Scale it and see the coordinates change as the scaling seem to be to the center. Should it be like this or scale to the origin point?

http://recordit.co/YdiBxdHIer

**Comment by tbfleming** [comment]
If it scaled based on origin (x0y0) then it could move a long distance, which could be frustrating, especially to new users.

**Comment by cojarbi** [comment]
This way is far easier to center 2 objects between one another but i was trying to get my path into the 0,0 location to reference it to the stock and if i scale then i have to move it again to 0,0

**Comment by tbfleming** [comment]
You want it to scale relative to the lower-left point of the selected objects instead of their center?

**Comment by openhardwarecoza** [comment]
We had the same workflow in LW3: scale first,  then move (:

**Comment by cojarbi** [comment]
Maybe both options?

**Comment by tbfleming** [comment]
I'm afraid that adding a bunch of options will confuse new users. Users abandoned Mozilla and switched to Firefox partly because Firefox stripped out most of the options. Eventually the Mozilla org gave up on Mozilla because everyone stopped using it. Firefox became the official replacement.

**Comment by cojarbi** [comment]
Agreed. Then maybe need to be part of the documentation
