### ISSUE TITLE
Cut internal first

### ISSUE THREAD

**Issue by loiz** [LaserWeb/LaserWeb4#665]
I'm trying tu use LaserWeb for laser cutting.

IS there a way to cut inside shape and outline in a second Time ?

Best regards
Loiz

**Comment by harlock999** [comment]
Absolutely!
Select the inside paths for inside and put it in a first GCODE group.
After that, select the outside path and create another GCODE group.
When you generate the GCODE, they will be generated in the order of the groups listed.

Cheers!
