### ISSUE TITLE
laser test button

### ISSUE THREAD

**Issue by faisalzahid12** [LaserWeb/LaserWeb4#668]
the laser test button is not working when I click the button it does not turn on and if I click on check size laser steel won't turn on but when I start the job then the laser turns on and cuts the material I am having a hard time and wasting material because I can't tall ware the laser is please hele'

**Comment by cprezzi** [comment]
By default, the "TOOL TEST POWER" (in settings/gcode) is set to zero for safety reason.

- If you have a diode laser (visible beam) then you can set "TOOL TEST POWER" to a low value so it does not burn but is visible. Additionally set "TOOL TEST DURATION" to 0 for unlimited duration.
- If you have a CO2 laser (invisible beam) you should only use this function for a short pulse. Set a low "TOOL TEST POWER" and a short duration like 100ms in "TOOL TEST DURATION", so that it only marks a point on your material.

**Comment by cprezzi** [comment]
The "check size" function does not activate the laser (for safety reason).

- On a diode laser (after configuring tool test power and duration), you can first click "Laser Test" and then "Check Size" to see the outline of your job. Click "Laser Test" after this again to switch the laser off.

**Comment by faisalzahid12** [comment]
then you for the advice but can you give me some stap-by-stap guides I will be grateful

**Comment by faisalzahid12** [comment]
thank you for your quick answer can you also tell me how to max my diode laser power my laser has one line in one duration but a little line in another duration is there a way to fix that without by any new laser but by changing the lens of the laser I have a 40w laser but having a hard time controlling its seating like speed and passes if want 3mm the wood it takes 4 passes for fully cut
but if I decrease the speed the cat area has a crisp burn

**Comment by cprezzi** [comment]
I have no idea what machine you have, but many chinese vendors tell you it's 40W, but in reality it is only 5W continous. The cutting power is primarily depending on laser power, speed and focus. Lower speed results in more cutting power, bad focus means less power. If your material is not flat, then focus is not constant and so is power.

**Comment by faisalzahid12** [comment]
how to check the true watt of my diode laser

**Comment by faisalzahid12** [comment]
I tested a cut speed on a 3mm strip my x =280 and 150 and1 pass power 100% for some reason (x) has thean line but (y) has the line

**Comment by faisalzahid12** [comment]
![Uploading 20240411_222715[1].jpg…]()

**Comment by faisalzahid12** [comment]
![Uploading 20240411_222715[1].jpg…]()

**Comment by faisalzahid12** [comment]
![Uploading 20240411_222715[1].jpg…]()

**Comment by faisalzahid12** [comment]
![Uploading 20240411_222715[1].jpg…]()

**Comment by faisalzahid12** [comment]
![Alert_RA_Y 1](https://github.com/LaserWeb/LaserWeb4/assets/166581988/444de460-26a5-467c-be2c-e2a71c666ab3)

**Comment by faisalzahid12** [comment]
![MostlyClearNight 1](https://github.com/LaserWeb/LaserWeb4/assets/166581988/69fc8ff9-6755-43a6-a1c3-44d3ce8e8fae)

**Comment by faisalzahid12** [comment]
![20240411_222715 1](https://github.com/LaserWeb/LaserWeb4/assets/166581988/be005d1d-3e82-4031-84ec-97f35e23f959)

**Comment by cprezzi** [comment]
There are Laser Power Meters, but they are very expensive. For example: https://www.cloudraylaser.com/products/cloudray-0-60w-high-accuracy-laser-beam-power-and-energy-meter?_pos=3&_sid=eb92f5c36&_ss=r

The beam of a diode laser is not round, it is rectangular. It has different dimentions in x and y direction. The result on your picture is normal.

But this is the wrong place for such questions. This is the issue tracker for LaserWeb!
Please serach for a general lasercutter forum. I don't have time to be your general supporter ;)

**Comment by faisalzahid12** [comment]
ok thank you for all your help good bay
