### ISSUE TITLE
Laser cut cam: Solves path too much

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#67]
Case in point: test file: http://vignette2.wikia.nocookie.net/simpsons/images/e/e7/Homer_Simpson.svg/revision/latest?cb=20150412145104

![homer-3v4](https://cloud.githubusercontent.com/assets/7695323/21078875/3e9660cc-bf88-11e6-9697-3b54159a8fca.PNG)

LW4 (right) misses the inside lines, LW3 (left) handled them

**Comment by tbfleming** [comment]
union is now optional
