### ISSUE TITLE
Supported hardware

### ISSUE THREAD

**Issue by emteeoh** [LaserWeb/LaserWeb4#7]
Just a comment, I think we should aim for the same support as LW3, at a minimum. Personally, I'll do my best to support grbl, and I'll occasionally be able to test smoothie.

**Comment by openhardwarecoza** [comment]
Seconded.  I also have a TinyG I can send to whoever wants to add that?

**Comment by openhardwarecoza** [comment]
Sorry closed by accident

**Comment by funinthefalls** [comment]
I would love to help out with TinyG, but I do not think my js coding skills are good enough. I have been studying the commits as much as possible to try and speed up my learni4ng process. For now I think I ned to stick to doing the documentation, let me know when you guys are ready for some LaserWeb4 Wiki pages.

**Comment by lautr3k** [comment]
What is the purpose of this issue ? Request feature to support firmware specifics features ? 
Thank you for clarifying.

**Comment by openhardwarecoza** [comment]
Adding tinyg and marlin mostly.  Tinyg is already in

**Comment by openhardwarecoza** [comment]
Closing this issue: TinyG is now implemented into the backend on LW3 - we'll just port this over once solid
