### ISSUE TITLE
gcodeMoveUnits?

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#71]
@jorgerobles Are there any controllers which use mm/s for F instead of mm/min?

**Comment by openhardwarecoza** [comment]
Negative.  Marlin, smoothie,  grbl and tinyg are all mm/min.  The mm/s
laser setting comes from user habits.  Laserdrw,  Corel Plugin and
Moshidraw are all mm/s therefore we eventually switched to mm/s inputs and
x60 before sending the gcode.

**Comment by jorgerobles** [comment]
Hmm not as far as I know, but some users like to use mm/s when introducing
the settings. Maybe is not a Gcode setting, but an application one

2016-12-11 17:04 GMT+01:00 Todd Fleming <notifications@github.com>:

**Comment by openhardwarecoza** [comment]
...  Primarily to ease users who knew what speed they used under the stock
controller

**Comment by tbfleming** [comment]
It should be an application setting then.

**Comment by jorgerobles** [comment]
Ok :)

2016-12-11 17:06 GMT+01:00 Jorge Robles <jorge.diego.robles@gmail.com>:

**Comment by jorgerobles** [comment]
Done!

2016-12-11 17:09 GMT+01:00 Jorge Robles <jorge.diego.robles@gmail.com>:

**Comment by tbfleming** [comment]
What does "select" mean? Also a better name would be "Feed Units" (variable: feedUnits)

![select](https://cloud.githubusercontent.com/assets/418464/21081493/22e92f4a-bf96-11e6-8700-4626ad7a8683.gif)

**Comment by jorgerobles** [comment]
Select is just a placeholder when none was selected (value=""). I could change to any other label too, or strip from the select field, but I experienced some bug on change event if not present.
About the name of the Variable I will change to Feed Units for better understanding.

**Comment by tbfleming** [comment]
I used ```react-select``` for Operation; it handles that case nicely.

**Comment by tbfleming** [comment]
You'll just have to give it an option to disable the 'X' it adds.
