### ISSUE TITLE
Job order sequence

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#72]
I assume the current order is based on the order i drag the path. Is/will it possible then to reorder/add a path in the middle ?

**Comment by tbfleming** [comment]
Operations execute top to bottom. It reoders the paths within each operation to try to minimize G0 moves. If you need paths to cut in a certain order, then create multiple operations.

**Comment by tbfleming** [comment]
Right now there's not an easy way to reorder the operations.

**Comment by cojarbi** [comment]
Understood but lets say i forgot or need to add something in the middle as the correct order is not working for me, at this point i would need to delete from that point forward?

**Comment by tbfleming** [comment]
For now. Keep this ticket open; it's a feature request.

**Comment by jorgerobles** [comment]
@tbfleming will reordering operations in state be enough?

![image](https://cloud.githubusercontent.com/assets/1706080/21099868/eea5f8ae-c070-11e6-85e7-d19b64b16b4a.png)

**Comment by tbfleming** [comment]
@jorgerobles yes. Maybe put up/down icons before the X icon.

**Comment by jorgerobles** [comment]
Ok, I will take a look

2016-12-12 15:12 GMT+01:00 Todd Fleming <notifications@github.com>:

**Comment by jorgerobles** [comment]
Done! I wished to use sortables but I could not make them work no matter what.

**Comment by tbfleming** [comment]
@jorgerobles 

We need to use something other than ```array.prototype.move```. It modifies a built-in prototype, something that is incredibly dangerous and should only be done by polyfills.

Please stop adding random newlines:
![image](https://cloud.githubusercontent.com/assets/418464/21123101/914400fa-c0a4-11e6-891a-c0f2dbb0f50e.png)

Please use an autoformatter. I recommend the one that comes built-in to vscode.

![image](https://cloud.githubusercontent.com/assets/418464/21123136/d50fca58-c0a4-11e6-9d36-cd36464905e3.png)

**Comment by jorgerobles** [comment]
[Sir, yes, Sir](http://www.firearmsnews.com/files/2011/09/Eastwood.jpg) 😆 
I usually check my commits before for nonsense whitespace. This time was not one of them, though.
Please, tell me: do you have any preferred extensions on VSCode? I use Komodo Edit, and autoformatter has done its work well last 8 years.

**Comment by tbfleming** [comment]
I use the Bookmarks extension, the C++ Extension, and changed a bunch of keybindings and settings. The most relevant setting tells the formatter and syntax highlighter to assume .js files are JSX. Maybe Komodo edit's autoformatter will work if it has a setting for JSX.
