### ISSUE TITLE
Identify already added paths to operations on the grid

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#73]
Once the path is added and multiple path are on the list, there needs to be a ways that the user can click the path and get the selection shown on the grid. Unless the user names each path which already gets read from the file buts highly unlikely the user will.
<img width="1772" alt="screen shot 2016-12-12 at 6 21 29 pm" src="https://cloud.githubusercontent.com/assets/16444438/21121098/900cff4a-c098-11e6-913e-b92f0d1292b9.png">
 do

**Comment by jorgerobles** [comment]
![pickpath](https://cloud.githubusercontent.com/assets/1706080/21202655/8b1c82b8-c24f-11e6-96e4-bec7aebb8972.gif)

**Comment by cojarbi** [comment]
Exactly. That's solves that and will also help on reordering paths as well
