### ISSUE TITLE
List of OSX features not working

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#75]
As i test and use LW4 im not sure if the issues are all related or not so i will list here and update accordingly if needed.

V-carve Generation crashes the browser
Clicking path directly on the grid does not select it

**Comment by jorgerobles** [comment]
@cojarbi, please attach osx version, web browser, and if possible the svg file you are using, some photo/screencap. 
_Also your tshirt size, and bank account._

**Comment by cojarbi** [comment]
OSX 10.12
Chrome Version 54.0.2840.98 (64-bit)

Note that Ive compared all this to Windows 8.1 which works perfectly

Do you need my credit card pin also??

**Comment by tbfleming** [comment]
He also wants your passport.

**Comment by cojarbi** [comment]
My passport will not be of any good as it analog still

⁣Ariel Yahni​

**Comment by jorgerobles** [comment]
Hmm gonna try with Sierra.. On 10.9 works enough (Lags a bit after computation - Vcarve is CPU intensive) Chrome Version 55.0.2883.87 (64-bit)
I have no Path issue neither. 

![path](https://cloud.githubusercontent.com/assets/1706080/21156778/5f86de7e-c177-11e6-8ffe-23a7d3b172d3.gif)
![vcarve](https://cloud.githubusercontent.com/assets/1706080/21156779/5f8a179c-c177-11e6-9c17-77e3f95fe22e.gif)

_... My shoes are 9 1/2 ..._

**Comment by jorgerobles** [comment]
.. Testing on Sierra and Chrome  55.0.2883.95 (64-bit) works fine.
Sorry @cojarbi, cannot reproduce your issues.

**Comment by cojarbi** [comment]
I also see you don't have issue with the bubble. Strange is that I don't get update for Chrome 55.

My pant size is 34

**Comment by cojarbi** [comment]
Ok im on Chrome 55 and definitely something is not right. I get multiple lock ups, computer freezes etc. Below some errors from the developer window in case it means anything for you guys

<img width="461" alt="screen shot 2016-12-13 at 6 48 01 pm" src="https://cloud.githubusercontent.com/assets/16444438/21164098/f59c8cf0-c164-11e6-8088-4f5a9d5badc6.png">
<img width="466" alt="screen shot 2016-12-13 at 6 46 19 pm" src="https://cloud.githubusercontent.com/assets/16444438/21164097/f59c41aa-c164-11e6-8546-6a8482bb53d9.png">
<img width="474" alt="screen shot 2016-12-13 at 6 45 58 pm" src="https://cloud.githubusercontent.com/assets/16444438/21164099/f5a0d21a-c164-11e6-9b7b-09957b6065d9.png">
<img width="1770" alt="screen shot 2016-12-13 at 6 44 42 pm" src="https://cloud.githubusercontent.com/assets/16444438/21164100/f5a10500-c164-11e6-8fbe-99b705d0d242.png">

**Comment by tbfleming** [comment]
Does your Mac have a discrete GPU? I wonder if the problem is with integrated graphics.

**Comment by cojarbi** [comment]
O yes it does. Please note that i can run under LW4 on VM with Windows 8.1 with no issues

<img width="581" alt="screen shot 2016-12-13 at 7 02 01 pm" src="https://cloud.githubusercontent.com/assets/16444438/21164405/b9045ad2-c166-11e6-8889-5b5894d7d2f1.png">

**Comment by tbfleming** [comment]
Dang that's perplexing. There should be more overhead running on a VM. The regl errors are WebGL crashing.

**Comment by kaosat-dev** [comment]
General FYI : it seems Chrome messed things up with webgl in Chrome 55, I don't have the same issues as above , but a few Webgl features that even work on safari & mobile (support for LineWidth other than 1 for example )  do not on Chrome55 on Mac anymore

**Comment by openhardwarecoza** [comment]
Regl was replaced yes?  @cojarbi is this still an issue?

**Comment by cojarbi** [comment]
Haven't tried v carve since then but selecting a path the grid is still not possible

**Comment by cojarbi** [comment]
Ok so whom do I need to bribe to get OSX Sierra ( seems ) issues fixed. 

Bubble is driving me crazy, click and drag item on the grid not working.

I do have latest OS, latest video drivers, latest chrome, latest .....

**Comment by tbfleming** [comment]
We may have to wait until Google fixes Chrome for Mac and Linux.

**Comment by openhardwarecoza** [comment]
Did you remember to sacrifice a kidney?

**Comment by cojarbi** [comment]
Damm you Google. Kidney was for OB Makerlinks, I can live without a heart tho

**Comment by openhardwarecoza** [comment]
Awww sweet.  #makerlinks.  Bonus to the first person who does a 3 way
corner,  with double miters all 3 beams,  joined with makerlinks...  (;

**Comment by jorgerobles** [comment]
@cojarbi Seems Sierra is working well here 😞 

![drag](https://cloud.githubusercontent.com/assets/1706080/22759772/fb6b91dc-ee53-11e6-80f1-121bc014cdb7.gif)

**Comment by cojarbi** [comment]
Nooooooooooooooooo :(. Post your current version please or validate mines

**Comment by DarklyLabs** [comment]
We just checked Sierra 10.12.3 and things seem to be working correctly as well.
Perhaps a cache clean may help? It has helped us with isolated problems in the past.

**Comment by cojarbi** [comment]
Browser cache is cleaned constantly. But I could try fixing data structure of the entire machine. But it's good to know that it's only me an other clients will not suffer. Do you see resize of the bubble correctly?

**Comment by DarklyLabs** [comment]
Yes, it behaves the same as Jorge's gif above.

**Comment by maudette01432** [comment]
Except your’s doesn’t render the “T”s as well.  It should say “TUIT” not UI.


-Mike

**Comment by maudette01432** [comment]
Where are the two T’s?  It should say TUIT.  Yours mis-renders the same as mine.  Open the SVG in inkscape or look at the ticket.  When I see a RED T and a BLACK UIT then it’ll be good ;)

-Mike

**Comment by jorgerobles** [comment]
@maudette01432 the issue of the t does not relate to sierra. Misbehaves as well on mavericks. I've pinged the lw.svg parser author to check the problem with your file. (I have picked your file as I was checking that also) :)

**Comment by maudette01432** [comment]
Cool,

Just wanted to make sure.  I’ll open a second ticket for the vCarve operation unless you think it might be somehow linked to the rendering issue (not sure it is since the other operations seem to be good).

-Mike

**Comment by cojarbi** [comment]
Mike this is another thread. I think I already logged the vcarve issue

**Comment by cojarbi** [comment]
Looking for solution. Are any of you running CUDA drivers?

**Comment by jorgerobles** [comment]
Yes, I am

**Comment by cojarbi** [comment]
oh come on @jorgerobles give me a brake :). So what else could it be?
Running same OSX, Chrome, video drivers ( what version you are running )

**Comment by jorgerobles** [comment]
![image](https://cloud.githubusercontent.com/assets/1706080/22783549/a00c63d8-eecc-11e6-96e4-c301aedf2f0b.png)

@cojarbi I don't know the drivers I'm using, maybe http://www.nvidia.com/download/driverResults.aspx/110844/

**Comment by cojarbi** [comment]
ok downgrading the drivers did not work, so its must be something else

**Comment by jorgerobles** [comment]
Could you open developer tools on Chrome (console) to see anything abnormal?

**Comment by cojarbi** [comment]
http://recordit.co/sJNu9Q39V2

**Comment by cojarbi** [comment]
Im going to close this as i havent found anyone else with this issue and seems only related to me. I did start a fresh os with same results
