### ISSUE TITLE
Operations: Accordian style? 

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#76]
I little niggle I personally experience with the operations component:
If I drag a new job down, it get appended to the bottom, so
a) If any operations are already expanded the user will always first need to scroll
b) the user also always has to click the expand button (since there are always unvalued inputs to fill in)

Wouldnt it be better to adopt an accordian style (expanding one operation collapses the others?) and then when dragging in a new job, default it to expanded (which collapses the others in the accordian, and thus saving the user a scroll and a click?)

**Comment by tbfleming** [comment]
done.

**Comment by openhardwarecoza** [comment]
![accordian](https://cloud.githubusercontent.com/assets/7695323/21320194/cc48a588-c618-11e6-942b-3db8c22770a2.gif)

Works awesome thanks!
