### ISSUE TITLE
Operations: Drop area is inside scrollable area

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#77]
The drop target scrolls off screen with a long operation, might be best to place it in another seperator between the document tree and operations so its always visible?

![drag area](https://cloud.githubusercontent.com/assets/7695323/21171288/92d66162-c1d3-11e6-942d-57c3a37762f4.PNG)

**Comment by jorgerobles** [comment]
Some tweaks to keep that fixed. But I don't know how to use that GetBound black magic to keep the balloons in the correct area, @tbfleming  could you teach us a bit?

**Comment by tbfleming** [comment]
I did that to save vertical space. Probably OK to not scroll once the operations are accordianed. To stop it from scrolling, move it up the hierarchy.

**Comment by jorgerobles** [comment]
only use className="scaleHalf" (not commited yet) and done :P 

![tada](https://cloud.githubusercontent.com/assets/1706080/21185359/a54c99dc-c210-11e6-8af2-509c32a2da94.png)

**Comment by openhardwarecoza** [comment]
(: wrong issue.  But i love the look.

**Comment by jorgerobles** [comment]
OOPs moooving

**Comment by jorgerobles** [comment]
This is done. May I close?

**Comment by openhardwarecoza** [comment]
Very happy yes!  Close away!
