### ISSUE TITLE
SettingsValidator: Change to Badge over Settings Sidebar?

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#80]
@jorgerobles 
The SettingsValidator Icon on the CAM tab confused me for a while, till I realised it relates to the Settings tab not the CAM params? (Unless I am still confused?)

If it is, how about making it a notification on the Sidebar menu (If something is wrong, it also gives a user a clue as to where to click)

Like:   http://stackoverflow.com/questions/23790721/overlap-notification-badge-on-glyph-in-bootstrap-3

![fok0e](https://cloud.githubusercontent.com/assets/7695323/21268006/805cc0d8-c3b5-11e6-8cf1-a45c2ed8279f.jpg)

But over the icon on the sidebar?

**Comment by jorgerobles** [comment]
No problem. I did that way to get a clue near a disabled gcode button. But
your solution makes perfect sense.

**Comment by openhardwarecoza** [comment]
Maybe a tooltip over a disabled gcode button mentioning a Setting is off,
is a worthy thing too. Users can be stupid sometimes

**Comment by jorgerobles** [comment]
The balloon seems enough cue :)

**Comment by openhardwarecoza** [comment]
I love it! 

I tweaked it a little (made it 20x20px and increased line-height to 22px to center the icon vertically)

![icons](https://cloud.githubusercontent.com/assets/7695323/21284265/c2706190-c41f-11e6-92d4-019c3a099123.png)

**Comment by openhardwarecoza** [comment]
Oh and the tooltip is an extra great bonus since it tells 'em whats wrong
