### ISSUE TITLE
Wasted Space

### ISSUE THREAD

**Issue by tbfleming** [LaserWeb/LaserWeb4#83]
There's a lot of new margins eating up vertical space.

![image](https://cloud.githubusercontent.com/assets/418464/21288237/747f7936-c44b-11e6-8ac2-18b0691695de.png)

**Comment by openhardwarecoza** [comment]
(; aww man but it looks so good.  Lol

**Comment by jorgerobles** [comment]
It looks nice to me. Anyways we could tweak space later with css. I like
MaterializeCSS also, but is waste(rer) if such word exists.

2016-12-17 17:41 GMT+01:00 Peter van der Walt <notifications@github.com>:

> (; aww man but it looks so good. Lol
>

**Comment by tbfleming** [comment]
Yes it looks nice, but is looking nice worth forcing users to scroll?

**Comment by tbfleming** [comment]
Except the checkmark. That looks confusing instead of nice.

**Comment by openhardwarecoza** [comment]
The main reason I did this is to make a clearer differentiation between Documents and Operations:
We had it really nicely polished in LW3 (No scroll needed)
even more so, the previous issue I asked for, to make operations an accordian, that really cuts down scrolling, not the extra 80px or so this wouldve added (;

Checkmark; Again, something we had working nicer in Lw3 (;

History lesson in the evolution of that UI: https://github.com/LaserWeb/LaserWeb3/issues/52

(Less space and checkboxes)
 ![panels](https://cloud.githubusercontent.com/assets/7695323/17524810/60e2d9c8-5e60-11e6-9597-88fd1b32b2ca.PNG)

**Comment by tbfleming** [comment]
LW3 didn't have these in the tab:
* The Tip
* The diagram (it was on a modal)
* The Drag target

These mean there are more vertical margins to deal with.

Checkboxes are horrible for selections. LW3 and jscut were stuck with them because no one coded up a real selection mechanism. LW4 doesn't have that limit.

**Comment by openhardwarecoza** [comment]
Alright you win. Will remove all that after dinner.  Sit tight on cam.js,
document.js so we dont have a merge conflict

**Comment by tbfleming** [comment]
Just to be clear, the only things I'd like to see removed:
* Some of the vertical margins
* Checkmarks

I like the clarity you got by moving stuff around. I fixed the error bubble clipping to exclude the non-scrolling drag target.

**Comment by openhardwarecoza** [comment]
Just about doesnt fit into 1280x720
![capture](https://cloud.githubusercontent.com/assets/7695323/21289095/81e2454e-c49c-11e6-9dbf-764af657a675.PNG)

But our smallest realistic target is the Pipo X9 on the Fabkit (1920x1200 8.9" display)
Th resolution is quite good but making things fingerable (oops) is harder because of the 8.9" display

As is right now it fits with tonnes of space to spare... 
![img_20161217_210353_hdr](https://cloud.githubusercontent.com/assets/7695323/21289101/b0910b5a-c49c-11e6-9351-e9077a8e7f60.jpg)

But... dragging documents isnt very fingerable on touch (; which brings me back to bargaining for checkboxes

**Comment by openhardwarecoza** [comment]
(;  
Playing your own arguments against you (;

![capture](https://cloud.githubusercontent.com/assets/7695323/21289112/1aa07b0c-c49d-11e6-9938-f79c7bb31f23.PNG)

Enabling touch on Windows th "native selection" is checkboxes (;

**Comment by openhardwarecoza** [comment]
I'll open seperate issue for Pipo / drag / select

**Comment by tbfleming** [comment]
Wow that's a change; I've never looked at Windows' touch mode. I thought you once said LW4 wouldn't support touch devices. Something about it opening a can of worms with layout...

**Comment by openhardwarecoza** [comment]
I said we wont support a "mobile" interface,ie none of the bootstrap responsive layout crap - thats just hell to make look good (horisontal and vertical layouts, scalable to small screens) 

But the Pipo is a "desktop" with a 8.9" touchscreen ... We had it fully supported in LW3 (play a little with LW3 - there are some history lessons worth learning from.   Settings -> Tool -> Enable Touch Numpads being another)

**Comment by openhardwarecoza** [comment]
Opened #86 to continue that discussion....

For now I cleaned up space and removed my FA checkboxes... Will leave you to think of fingerable solutions in #86
