### ISSUE TITLE
Cannot multiple select or drag documents on pipo

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#86]
So we spent a lot of time talking Fabcreator into fitting  Pipo X9s onto all their machines: http://www.banggood.com/PIPO-X9-Intel-Z3736F-Quad-Core-8_9-Inch-Dual-Boot-Mini-PC-TV-Box-Tablet-p-997056.html?p=HO1614632392201406RX and https://plus.google.com/+BonneWilce/posts/2UnLfyQ1rp4

Now, in LW3 we gave them numeric keypads, large jog buttons, and in the planned treecam we used checkboxes with an "add to job" button to allow some touch ease of use... Dragging and dropping isnt touch friendly...

in LW4 I cannot get any documents into Operations (; deadend

**Comment by openhardwarecoza** [comment]
![pipo](https://cloud.githubusercontent.com/assets/7695323/21289154/632c0f34-c49e-11e6-9f5f-5df616a423de.PNG)

**Comment by openhardwarecoza** [comment]
![select-multiple-files-in-windows-8-tablet-2_thumb](https://cloud.githubusercontent.com/assets/7695323/21289183/17d5f9e0-c49f-11e6-83ad-1f17e5dd0bc9.jpg)
![img_20161217_210353_hdr](https://cloud.githubusercontent.com/assets/7695323/21289184/17dbd98c-c49f-11e6-8e91-01a1df8eb04c.jpg)

**Comment by openhardwarecoza** [comment]
We had this in LaserWeb2 already!  Yikes long ago
![lw2 days](https://cloud.githubusercontent.com/assets/7695323/21289190/624f2c12-c49f-11e6-9126-ade9f741ee95.PNG)

**Comment by tbfleming** [comment]
For the CAM pane, maybe this?
* Make touch click act like CTRL+click
* Listen for correct touch events for touch drag to work

**Comment by openhardwarecoza** [comment]
We'll have to give it a whirl

Touch event for pan/zoom on the Viewer too.

**Comment by openhardwarecoza** [comment]
(; the pipo is awesome by the way - get one for the significant other for xmas, in two weeks when their bored of it move it to the workshop
Since it runs win10 - and its an intel x86 machine even our Electron EXE deploys fine on it

**Comment by openhardwarecoza** [comment]
@jorgerobles just tagging you to make sure you also keep touch in mind (;

**Comment by openhardwarecoza** [comment]
(;  I would like an "Add to new Operation" button in addition to drag and drop if I had my way too

**Comment by tbfleming** [comment]
Touch D&D is ready to try. I still need to add touch support to the splitters and workspace.

**Comment by openhardwarecoza** [comment]
Multi select works excellently (:

Drag works but needs some sort of visual clue that you are dragging...

**Comment by tbfleming** [comment]
Don't have a cursor to set, so probably need to play games with CSS.

**Comment by cojarbi** [comment]
I can confirm touch / multiple files for selecting and drag and drop working on Surface Pro. I can touch buttons on the workspace and images themselves

**Comment by openhardwarecoza** [comment]
All working nicely now, even on Android! Closing!
