### ISSUE TITLE
[Help] Creating an Electron Branch

### ISSUE THREAD

**Issue by jorgerobles** [LaserWeb/LaserWeb4#90]
Hi, due the ReGL issues (who I am lucky and not being affected yet) I'm trying to make an Electron Build (Chromium 53)... without luck. 

I was following this guide https://medium.com/@ad_harmonium/build-to-both-electron-js-and-browser-targets-using-webpack-59266bdb76a, but got stuck on when thrown several errors regarding ES6 transliteration.
Then I went for https://github.com/paulcbetts/electron-prebuilt-compile without luck.

Any Electron savvy out there?

**Comment by openhardwarecoza** [comment]
@montekrol @copet80

**Comment by openhardwarecoza** [comment]
Not webpack,  but maybe helpful https://github.com/LaserWeb/LaserWeb3-Electron

**Comment by jorgerobles** [comment]
Thanks @openhardwarecoza already check LW3 branch but seems webpack does things its own way.

**Comment by kaosat-dev** [comment]
Can you share the errors ? I would love to help out on this.

**Comment by jorgerobles** [comment]
I will post tomorrow @kaosat-dev, gonna try a fresh start :)

**Comment by kaosat-dev** [comment]
@jorgerobles  :) ok

**Comment by openhardwarecoza** [comment]
(; Skip the seperate branch

Make the Electron app serve two purposes:  

Web server serving /dist/  and also the Electron UI

The reason for this is that LW is always nice to access over the LAN from another PC.  With the current LW3 branch, the app is only accessible via the electron gui's chrome.  node-static/http doesnt play nice with Electron (Open issue here https://github.com/electron-userland/electron-builder/issues/974 ) once built into an exe.  

This way, the Electron app can be used, or while its running, we can open a browser to localhost:8080 or from another machine on the lan

We are definitely going electron (about a month of fights in the LW3 branch determined it works well enough (though real Chrome was faster than Electron, so therefore an even bigger wish to get the webserver going too))

**Comment by openhardwarecoza** [comment]
@jorgerobles : done see https://github.com/LaserWeb/LaserWeb4/issues/79#issuecomment-267953205

**Comment by kaosat-dev** [comment]
@openhardwarecoza actually that is a different thing I believe, the one in #79 is merely a test for regl /os issues,  it does not use webpack or anything specific to LW4 so I doubt It can be use for this issue :)

**Comment by jorgerobles** [comment]
Indeed. I'm struggling to get a webpack-react-electron-app-of-hell. I'm sure a quantum dynamics pHd is easier.

**Comment by openhardwarecoza** [comment]
Run the distribution build,  copy /dist and host that?

**Comment by jorgerobles** [comment]
Something interferes in the middle. Its the webpack middleware or Hot..
I've lot the lead.
I'm now trying from scratch, with a test project to reproduce the issue.
All the tutorials I've found tell this is easy, hence, I'm doing something
wrong. :)

2016-12-19 18:23 GMT+01:00 Peter van der Walt <notifications@github.com>:

> Run the distribution build, copy /dist and host that?
>

**Comment by openhardwarecoza** [comment]
I ran /dist/ from another webserver and it worked

**Comment by jorgerobles** [comment]
I'll take into account 👍
