### ISSUE TITLE
Work on Comms module 

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#92]
@openhardwarecoza said: "If i can offer some advice, finish up a perfect backend first and we'll make the frontend plug into it
With that I mean, get server.js to wrap comms into websocket and handle events for connect, send gcode, skip queue gcode, overrides and return status info. Ie cleanup and extend exactly what we were talking about?"

@cprezzi said "Ok. I do the server part first. :)
I will try to define a uniform interface for the client and handle all the firmware / machine interface specific stuff in the server."

@openhardwarecoza said: 

(: thats the big dream!

See if you supply a server, documented with which ws events it emits (and sample strings/objects) as well as which events it expects (and sample data) thats going to make the rest sooo easy

In LW3 we already have it quite simple

| Events Listening  | Events Emitted |
| ------------- | ------------- |
|  socket.on('firstLoad') (Tells the server a web interface was loaded) |  socket.emit('config', config);  (Send some config data from the backend) |
|  socket.on('stop') (Abort job)  |  socket.emit("firmware", firmware); (tell frontend which firmware and version is in use) |
|  socket.on('pause') (pause job) | socket.emit("activePorts", port.path + ',' + port.options.baudRate); (not even sure we really use this)  |
|  socket.on('unpause') (unpause job) |  |
| socket.on('serialSend') (Send command/gcode/mcode to serialport)  |  socket.emit("connectStatus", 'strings here'); (tells UI something about the serialport connection events as they happen) |
| socket.on('feedOverride') (FRO)  |   |
| socket.on('spindleOverride') (Power/spindle override) |   |
| socket.on('laserTest') (Too laser specific? Maybe rather a predefined macro?)  |   |
| socket.on('clearAlarm') (clears machine alarm state) |   |
| socket.on('getFirmware') (frontend request backend to report firmware) |   |
| socket.on('refreshPorts') (check for new serialports) |   |
| socket.on('closePort') (close serialport) |   |
| socket.on('areWeLive') (I think this was if you open a browser and backend is already connected)  |   |
| socket.on('connectTo') (open a serialport) |   |

**Comment by jorgerobles** [comment]
@cprezzi Although react could be used to develop on serverside (in theory) there's no need to use it, so start a cozy server with a well defined api and we will connect to it without problem.

I think the one that has a solid idea of how to use react is @tbfleming. I'm rather a well fed monkey.

**Comment by openhardwarecoza** [comment]
Agreed on keeping server like we have now.  Then we can also reuse the existing electron packing

**Comment by cprezzi** [comment]
Ok, I'll go for it. 
I think it makes sense to emit a result for most client commands so the clients can react on it, like change button "Pause" to "Play" (instead of guessing the state on it's own).

**Comment by openhardwarecoza** [comment]
Indeed it makes more sense!

**Comment by openhardwarecoza** [comment]
Note Keep this issue open till https://github.com/LaserWeb/lw.comm-server is nearer ready
