### ISSUE TITLE
3D Viewer: Support Opacity as S value

### ISSUE THREAD

**Issue by openhardwarecoza** [LaserWeb/LaserWeb4#96]
![opacity needed](https://cloud.githubusercontent.com/assets/7695323/21337938/71dc72ca-c67a-11e6-9eda-781b49a34f49.PNG)

Works in LW3, needed in LW4:

Note: Opacity scals between 0-100% opaque, based on the S value but S differs between various firmwares so kep in mind to read scale from settings

**Comment by openhardwarecoza** [comment]
LW3: https://github.com/LaserWeb/LaserWeb3/blob/master/public/lib/gcode-viewer/gcode-parser.js#L299-L306

**Comment by tbfleming** [comment]
Might need a different approach that doesn't mess up the laser preview. Turn off gcode and documents but leave laser on for that example. Zoom in and out.

**Comment by openhardwarecoza** [comment]
![perfect](https://cloud.githubusercontent.com/assets/7695323/21338665/e1ee4b32-c680-11e6-9d90-01612a0c6729.PNG)

Aha! Thats what I was looking for! thick lines (0.1mm bam, 0.5mm stepover to show effect above)  makes zoomed in view look better than lw3! Just need to document hiding gcode...

**Comment by tbfleming** [comment]
Also try with diagonal and the Sim slider :)

**Comment by openhardwarecoza** [comment]
blown away! See thats why you need to post screen2gifs in development news again!

**Comment by tbfleming** [comment]
Been too busy coding. I think I did screen2gifs of laser preview a while back.

**Comment by openhardwarecoza** [comment]
you did yes... will post some today (; keep on coding!
